// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GCM_AE_HW_1x8_GHASH (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hash_payload_0_address0,
        hash_payload_0_ce0,
        hash_payload_0_q0,
        hash_payload_0_address1,
        hash_payload_0_ce1,
        hash_payload_0_q1,
        hash_payload_1_address0,
        hash_payload_1_ce0,
        hash_payload_1_q0,
        hash_payload_1_address1,
        hash_payload_1_ce1,
        hash_payload_1_q1,
        hash_payload_2_address0,
        hash_payload_2_ce0,
        hash_payload_2_q0,
        hash_payload_2_address1,
        hash_payload_2_ce1,
        hash_payload_2_q1,
        hash_payload_3_address0,
        hash_payload_3_ce0,
        hash_payload_3_q0,
        hash_payload_3_address1,
        hash_payload_3_ce1,
        hash_payload_3_q1,
        hblock_len,
        H_matrix_7,
        H_matrix_6,
        H_matrix_5,
        H_matrix_4,
        H_matrix_3,
        H_matrix_2,
        H_matrix_1,
        H_matrix_0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] hash_payload_0_address0;
output   hash_payload_0_ce0;
input  [127:0] hash_payload_0_q0;
output  [7:0] hash_payload_0_address1;
output   hash_payload_0_ce1;
input  [127:0] hash_payload_0_q1;
output  [7:0] hash_payload_1_address0;
output   hash_payload_1_ce0;
input  [127:0] hash_payload_1_q0;
output  [7:0] hash_payload_1_address1;
output   hash_payload_1_ce1;
input  [127:0] hash_payload_1_q1;
output  [7:0] hash_payload_2_address0;
output   hash_payload_2_ce0;
input  [127:0] hash_payload_2_q0;
output  [7:0] hash_payload_2_address1;
output   hash_payload_2_ce1;
input  [127:0] hash_payload_2_q1;
output  [7:0] hash_payload_3_address0;
output   hash_payload_3_ce0;
input  [127:0] hash_payload_3_q0;
output  [7:0] hash_payload_3_address1;
output   hash_payload_3_ce1;
input  [127:0] hash_payload_3_q1;
input  [25:0] hblock_len;
input  [127:0] H_matrix_7;
input  [127:0] H_matrix_6;
input  [127:0] H_matrix_5;
input  [127:0] H_matrix_4;
input  [127:0] H_matrix_3;
input  [127:0] H_matrix_2;
input  [127:0] H_matrix_1;
input  [127:0] H_matrix_0;
output  [127:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] hash_payload_0_address0;
reg hash_payload_0_ce0;
reg hash_payload_0_ce1;
reg[7:0] hash_payload_1_address0;
reg hash_payload_1_ce0;
reg hash_payload_1_ce1;
reg[7:0] hash_payload_2_address0;
reg hash_payload_2_ce0;
reg hash_payload_2_ce1;
reg[7:0] hash_payload_3_address0;
reg hash_payload_3_ce0;
reg hash_payload_3_ce1;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [22:0] trunc_ln_fu_118_p4;
reg   [22:0] trunc_ln_reg_162;
wire   [2:0] ret_V_fu_129_p1;
reg   [2:0] ret_V_reg_167;
wire   [0:0] icmp_ln1035_fu_133_p2;
reg   [0:0] icmp_ln1035_reg_172;
wire   [127:0] grp_GHASH_multi_8x_fu_70_ap_return;
wire    ap_CS_fsm_state2;
reg   [6:0] tmp_reg_181;
wire    grp_GHASH_multi_8x_fu_70_ap_start;
wire    grp_GHASH_multi_8x_fu_70_ap_done;
wire    grp_GHASH_multi_8x_fu_70_ap_idle;
wire    grp_GHASH_multi_8x_fu_70_ap_ready;
wire   [7:0] grp_GHASH_multi_8x_fu_70_hash_payload_0_address0;
wire    grp_GHASH_multi_8x_fu_70_hash_payload_0_ce0;
wire   [7:0] grp_GHASH_multi_8x_fu_70_hash_payload_0_address1;
wire    grp_GHASH_multi_8x_fu_70_hash_payload_0_ce1;
wire   [7:0] grp_GHASH_multi_8x_fu_70_hash_payload_1_address0;
wire    grp_GHASH_multi_8x_fu_70_hash_payload_1_ce0;
wire   [7:0] grp_GHASH_multi_8x_fu_70_hash_payload_1_address1;
wire    grp_GHASH_multi_8x_fu_70_hash_payload_1_ce1;
wire   [7:0] grp_GHASH_multi_8x_fu_70_hash_payload_2_address0;
wire    grp_GHASH_multi_8x_fu_70_hash_payload_2_ce0;
wire   [7:0] grp_GHASH_multi_8x_fu_70_hash_payload_2_address1;
wire    grp_GHASH_multi_8x_fu_70_hash_payload_2_ce1;
wire   [7:0] grp_GHASH_multi_8x_fu_70_hash_payload_3_address0;
wire    grp_GHASH_multi_8x_fu_70_hash_payload_3_ce0;
wire   [7:0] grp_GHASH_multi_8x_fu_70_hash_payload_3_address1;
wire    grp_GHASH_multi_8x_fu_70_hash_payload_3_ce1;
wire   [127:0] grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_din1;
wire   [127:0] grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_din2;
wire    grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_ce;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_done;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_idle;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_ready;
wire   [7:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_0_address0;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_0_ce0;
wire   [7:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_1_address0;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_1_ce0;
wire   [7:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_2_address0;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_2_ce0;
wire   [7:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_3_address0;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_3_ce0;
wire   [127:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_99_X_V_out;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_X_V_out_ap_vld;
wire   [127:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_din1;
wire   [127:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_din2;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_ce;
reg   [127:0] grp_GHASH_H1_fu_186_X;
reg   [127:0] grp_GHASH_H1_fu_186_H_matrix_0;
wire   [127:0] grp_GHASH_H1_fu_186_ap_return;
reg    grp_GHASH_H1_fu_186_ap_ce;
reg   [127:0] agg_result_0_reg_58;
reg    ap_block_state2_on_subcall_done;
reg    grp_GHASH_multi_8x_fu_70_ap_start_reg;
reg    grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_GHASH_multi_8x_fu_70_ap_start_reg = 1'b0;
#0 grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start_reg = 1'b0;
end

GCM_AE_HW_1x8_GHASH_multi_8x grp_GHASH_multi_8x_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GHASH_multi_8x_fu_70_ap_start),
    .ap_done(grp_GHASH_multi_8x_fu_70_ap_done),
    .ap_idle(grp_GHASH_multi_8x_fu_70_ap_idle),
    .ap_ready(grp_GHASH_multi_8x_fu_70_ap_ready),
    .hash_payload_0_address0(grp_GHASH_multi_8x_fu_70_hash_payload_0_address0),
    .hash_payload_0_ce0(grp_GHASH_multi_8x_fu_70_hash_payload_0_ce0),
    .hash_payload_0_q0(hash_payload_0_q0),
    .hash_payload_0_address1(grp_GHASH_multi_8x_fu_70_hash_payload_0_address1),
    .hash_payload_0_ce1(grp_GHASH_multi_8x_fu_70_hash_payload_0_ce1),
    .hash_payload_0_q1(hash_payload_0_q1),
    .hash_payload_1_address0(grp_GHASH_multi_8x_fu_70_hash_payload_1_address0),
    .hash_payload_1_ce0(grp_GHASH_multi_8x_fu_70_hash_payload_1_ce0),
    .hash_payload_1_q0(hash_payload_1_q0),
    .hash_payload_1_address1(grp_GHASH_multi_8x_fu_70_hash_payload_1_address1),
    .hash_payload_1_ce1(grp_GHASH_multi_8x_fu_70_hash_payload_1_ce1),
    .hash_payload_1_q1(hash_payload_1_q1),
    .hash_payload_2_address0(grp_GHASH_multi_8x_fu_70_hash_payload_2_address0),
    .hash_payload_2_ce0(grp_GHASH_multi_8x_fu_70_hash_payload_2_ce0),
    .hash_payload_2_q0(hash_payload_2_q0),
    .hash_payload_2_address1(grp_GHASH_multi_8x_fu_70_hash_payload_2_address1),
    .hash_payload_2_ce1(grp_GHASH_multi_8x_fu_70_hash_payload_2_ce1),
    .hash_payload_2_q1(hash_payload_2_q1),
    .hash_payload_3_address0(grp_GHASH_multi_8x_fu_70_hash_payload_3_address0),
    .hash_payload_3_ce0(grp_GHASH_multi_8x_fu_70_hash_payload_3_ce0),
    .hash_payload_3_q0(hash_payload_3_q0),
    .hash_payload_3_address1(grp_GHASH_multi_8x_fu_70_hash_payload_3_address1),
    .hash_payload_3_ce1(grp_GHASH_multi_8x_fu_70_hash_payload_3_ce1),
    .hash_payload_3_q1(hash_payload_3_q1),
    .no_block_ops_Q(trunc_ln_reg_162),
    .H_matrix_7(H_matrix_7),
    .H_matrix_6(H_matrix_6),
    .H_matrix_5(H_matrix_5),
    .H_matrix_4(H_matrix_4),
    .H_matrix_3(H_matrix_3),
    .H_matrix_2(H_matrix_2),
    .H_matrix_1(H_matrix_1),
    .H_matrix_0(H_matrix_0),
    .ap_return(grp_GHASH_multi_8x_fu_70_ap_return),
    .grp_GHASH_H1_fu_186_p_din1(grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_din1),
    .grp_GHASH_H1_fu_186_p_din2(grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_din2),
    .grp_GHASH_H1_fu_186_p_dout0(grp_GHASH_H1_fu_186_ap_return),
    .grp_GHASH_H1_fu_186_p_ce(grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_ce)
);

GCM_AE_HW_1x8_GHASH_Pipeline_Remainder_R_loop grp_GHASH_Pipeline_Remainder_R_loop_fu_99(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start),
    .ap_done(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_done),
    .ap_idle(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_idle),
    .ap_ready(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_ready),
    .agg_result_0(agg_result_0_reg_58),
    .ret_V(ret_V_reg_167),
    .tmp(tmp_reg_181),
    .hash_payload_0_address0(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_0_address0),
    .hash_payload_0_ce0(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_0_ce0),
    .hash_payload_0_q0(hash_payload_0_q0),
    .hash_payload_1_address0(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_1_address0),
    .hash_payload_1_ce0(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_1_ce0),
    .hash_payload_1_q0(hash_payload_1_q0),
    .hash_payload_2_address0(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_2_address0),
    .hash_payload_2_ce0(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_2_ce0),
    .hash_payload_2_q0(hash_payload_2_q0),
    .hash_payload_3_address0(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_3_address0),
    .hash_payload_3_ce0(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_3_ce0),
    .hash_payload_3_q0(hash_payload_3_q0),
    .X_V_out(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_X_V_out),
    .X_V_out_ap_vld(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_X_V_out_ap_vld),
    .H_matrix_0(H_matrix_0),
    .grp_GHASH_H1_fu_186_p_din1(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_din1),
    .grp_GHASH_H1_fu_186_p_din2(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_din2),
    .grp_GHASH_H1_fu_186_p_dout0(grp_GHASH_H1_fu_186_ap_return),
    .grp_GHASH_H1_fu_186_p_ce(grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_ce)
);

GCM_AE_HW_1x8_GHASH_H1 grp_GHASH_H1_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(grp_GHASH_H1_fu_186_X),
    .H_matrix_0(grp_GHASH_H1_fu_186_H_matrix_0),
    .ap_return(grp_GHASH_H1_fu_186_ap_return),
    .ap_ce(grp_GHASH_H1_fu_186_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start_reg <= 1'b1;
        end else if ((grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_ready == 1'b1)) begin
            grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GHASH_multi_8x_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1035_fu_133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_GHASH_multi_8x_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_GHASH_multi_8x_fu_70_ap_ready == 1'b1)) begin
            grp_GHASH_multi_8x_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1035_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        agg_result_0_reg_58 <= 128'd0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        agg_result_0_reg_58 <= grp_GHASH_multi_8x_fu_70_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln1035_reg_172 <= icmp_ln1035_fu_133_p2;
        ret_V_reg_167 <= ret_V_fu_129_p1;
        trunc_ln_reg_162 <= {{hblock_len[25:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_reg_181 <= {{hblock_len[9:3]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_GHASH_H1_fu_186_H_matrix_0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_din2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_GHASH_H1_fu_186_H_matrix_0 = grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_din2;
    end else begin
        grp_GHASH_H1_fu_186_H_matrix_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_GHASH_H1_fu_186_X = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_GHASH_H1_fu_186_X = grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_din1;
    end else begin
        grp_GHASH_H1_fu_186_X = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_GHASH_H1_fu_186_ap_ce = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_grp_GHASH_H1_fu_186_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_GHASH_H1_fu_186_ap_ce = grp_GHASH_multi_8x_fu_70_grp_GHASH_H1_fu_186_p_ce;
    end else if (~(1'b1 == 1'b1)) begin
        grp_GHASH_H1_fu_186_ap_ce = 1'b0;
    end else begin
        grp_GHASH_H1_fu_186_ap_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_0_address0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_0_address0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_0_address0 = grp_GHASH_multi_8x_fu_70_hash_payload_0_address0;
    end else begin
        hash_payload_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_0_ce0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_0_ce0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_0_ce0 = grp_GHASH_multi_8x_fu_70_hash_payload_0_ce0;
    end else begin
        hash_payload_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_0_ce1 = grp_GHASH_multi_8x_fu_70_hash_payload_0_ce1;
    end else begin
        hash_payload_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_1_address0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_1_address0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_1_address0 = grp_GHASH_multi_8x_fu_70_hash_payload_1_address0;
    end else begin
        hash_payload_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_1_ce0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_1_ce0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_1_ce0 = grp_GHASH_multi_8x_fu_70_hash_payload_1_ce0;
    end else begin
        hash_payload_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_1_ce1 = grp_GHASH_multi_8x_fu_70_hash_payload_1_ce1;
    end else begin
        hash_payload_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_2_address0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_2_address0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_2_address0 = grp_GHASH_multi_8x_fu_70_hash_payload_2_address0;
    end else begin
        hash_payload_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_2_ce0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_2_ce0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_2_ce0 = grp_GHASH_multi_8x_fu_70_hash_payload_2_ce0;
    end else begin
        hash_payload_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_2_ce1 = grp_GHASH_multi_8x_fu_70_hash_payload_2_ce1;
    end else begin
        hash_payload_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_3_address0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_3_address0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_3_address0 = grp_GHASH_multi_8x_fu_70_hash_payload_3_address0;
    end else begin
        hash_payload_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_3_ce0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_hash_payload_3_ce0;
    end else if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_3_ce0 = grp_GHASH_multi_8x_fu_70_hash_payload_3_ce0;
    end else begin
        hash_payload_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1035_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        hash_payload_3_ce1 = grp_GHASH_multi_8x_fu_70_hash_payload_3_ce1;
    end else begin
        hash_payload_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_GHASH_multi_8x_fu_70_ap_done == 1'b0) & (icmp_ln1035_reg_172 == 1'd0));
end

assign ap_return = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_X_V_out;

assign grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start = grp_GHASH_Pipeline_Remainder_R_loop_fu_99_ap_start_reg;

assign grp_GHASH_multi_8x_fu_70_ap_start = grp_GHASH_multi_8x_fu_70_ap_start_reg;

assign hash_payload_0_address1 = grp_GHASH_multi_8x_fu_70_hash_payload_0_address1;

assign hash_payload_1_address1 = grp_GHASH_multi_8x_fu_70_hash_payload_1_address1;

assign hash_payload_2_address1 = grp_GHASH_multi_8x_fu_70_hash_payload_2_address1;

assign hash_payload_3_address1 = grp_GHASH_multi_8x_fu_70_hash_payload_3_address1;

assign icmp_ln1035_fu_133_p2 = ((trunc_ln_fu_118_p4 == 23'd0) ? 1'b1 : 1'b0);

assign ret_V_fu_129_p1 = hblock_len[2:0];

assign trunc_ln_fu_118_p4 = {{hblock_len[25:3]}};

endmodule //GCM_AE_HW_1x8_GHASH
