// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GCM_AE_HW_1x8_H_operand_gen_8x (
        ap_clk,
        ap_rst,
        X1_operand,
        X2_operand,
        X3_operand,
        X4_operand,
        X5_operand,
        X6_operand,
        X7_operand,
        X8_operand,
        H8_operand_V_read,
        H7_operand_V_read,
        H6_operand_V_read,
        H5_operand_V_read,
        H4_operand_V_read,
        H3_operand_V_read,
        H2_operand_V_read,
        H1_operand_V_read,
        H_matrix_7,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);


input   ap_clk;
input   ap_rst;
input  [127:0] X1_operand;
input  [127:0] X2_operand;
input  [127:0] X3_operand;
input  [127:0] X4_operand;
input  [127:0] X5_operand;
input  [127:0] X6_operand;
input  [127:0] X7_operand;
input  [127:0] X8_operand;
input  [127:0] H8_operand_V_read;
input  [127:0] H7_operand_V_read;
input  [127:0] H6_operand_V_read;
input  [127:0] H5_operand_V_read;
input  [127:0] H4_operand_V_read;
input  [127:0] H3_operand_V_read;
input  [127:0] H2_operand_V_read;
input  [127:0] H1_operand_V_read;
input  [127:0] H_matrix_7;
output  [127:0] ap_return_0;
output  [127:0] ap_return_1;
output  [127:0] ap_return_2;
output  [127:0] ap_return_3;
output  [127:0] ap_return_4;
output  [127:0] ap_return_5;
output  [127:0] ap_return_6;
output  [127:0] ap_return_7;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_pp0_stage0_11001;
wire   [127:0] grp_GHASH_H_operand_gen_fu_136_ap_return;
reg    grp_GHASH_H_operand_gen_fu_136_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call16;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call16;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call16;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call16;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call16;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call16;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call16;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call16;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call16;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call16;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call16;
wire    ap_block_pp0_stage0_11001_ignoreCallOp28;
wire   [127:0] grp_GHASH_H_operand_gen_fu_146_ap_return;
reg    grp_GHASH_H_operand_gen_fu_146_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call17;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call17;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call17;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call17;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call17;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call17;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call17;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call17;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call17;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call17;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call17;
wire    ap_block_pp0_stage0_11001_ignoreCallOp29;
wire   [127:0] grp_GHASH_H_operand_gen_fu_156_ap_return;
reg    grp_GHASH_H_operand_gen_fu_156_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call18;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call18;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call18;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call18;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call18;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call18;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call18;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call18;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call18;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call18;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call18;
wire    ap_block_pp0_stage0_11001_ignoreCallOp30;
wire   [127:0] grp_GHASH_H_operand_gen_fu_166_ap_return;
reg    grp_GHASH_H_operand_gen_fu_166_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call19;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call19;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call19;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call19;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call19;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call19;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call19;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call19;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call19;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call19;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call19;
wire    ap_block_pp0_stage0_11001_ignoreCallOp31;
wire   [127:0] grp_GHASH_H_operand_gen_fu_176_ap_return;
reg    grp_GHASH_H_operand_gen_fu_176_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call20;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call20;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call20;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call20;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call20;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call20;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call20;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call20;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call20;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call20;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call20;
wire    ap_block_pp0_stage0_11001_ignoreCallOp32;
wire   [127:0] grp_GHASH_H_operand_gen_fu_186_ap_return;
reg    grp_GHASH_H_operand_gen_fu_186_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call21;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call21;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call21;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call21;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call21;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call21;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call21;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call21;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call21;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call21;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call21;
wire    ap_block_pp0_stage0_11001_ignoreCallOp33;
wire   [127:0] grp_GHASH_H_operand_gen_fu_196_ap_return;
reg    grp_GHASH_H_operand_gen_fu_196_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call22;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call22;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call22;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call22;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call22;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call22;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call22;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call22;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call22;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call22;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call22;
wire    ap_block_pp0_stage0_11001_ignoreCallOp34;
wire   [127:0] grp_GHASH_H_operand_gen_fu_206_ap_return;
reg    grp_GHASH_H_operand_gen_fu_206_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call23;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call23;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call23;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call23;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call23;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call23;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call23;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call23;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call23;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call23;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call23;
wire    ap_block_pp0_stage0_11001_ignoreCallOp35;
wire    ap_block_pp0_stage0;
reg   [127:0] X1_operand_int_reg;
reg   [127:0] X2_operand_int_reg;
reg   [127:0] X3_operand_int_reg;
reg   [127:0] X4_operand_int_reg;
reg   [127:0] X5_operand_int_reg;
reg   [127:0] X6_operand_int_reg;
reg   [127:0] X7_operand_int_reg;
reg   [127:0] X8_operand_int_reg;
reg   [127:0] H8_operand_V_read_int_reg;
reg   [127:0] H7_operand_V_read_int_reg;
reg   [127:0] H6_operand_V_read_int_reg;
reg   [127:0] H5_operand_V_read_int_reg;
reg   [127:0] H4_operand_V_read_int_reg;
reg   [127:0] H3_operand_V_read_int_reg;
reg   [127:0] H2_operand_V_read_int_reg;
reg   [127:0] H1_operand_V_read_int_reg;
reg   [127:0] H_matrix_7_int_reg;
wire    ap_ce_reg;

GCM_AE_HW_1x8_GHASH_H_operand_gen grp_GHASH_H_operand_gen_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(X1_operand_int_reg),
    .H_operand_V_read(H8_operand_V_read_int_reg),
    .H_matrix_7(H_matrix_7_int_reg),
    .ap_return(grp_GHASH_H_operand_gen_fu_136_ap_return),
    .ap_ce(grp_GHASH_H_operand_gen_fu_136_ap_ce)
);

GCM_AE_HW_1x8_GHASH_H_operand_gen grp_GHASH_H_operand_gen_fu_146(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(X2_operand_int_reg),
    .H_operand_V_read(H7_operand_V_read_int_reg),
    .H_matrix_7(H_matrix_7_int_reg),
    .ap_return(grp_GHASH_H_operand_gen_fu_146_ap_return),
    .ap_ce(grp_GHASH_H_operand_gen_fu_146_ap_ce)
);

GCM_AE_HW_1x8_GHASH_H_operand_gen grp_GHASH_H_operand_gen_fu_156(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(X3_operand_int_reg),
    .H_operand_V_read(H6_operand_V_read_int_reg),
    .H_matrix_7(H_matrix_7_int_reg),
    .ap_return(grp_GHASH_H_operand_gen_fu_156_ap_return),
    .ap_ce(grp_GHASH_H_operand_gen_fu_156_ap_ce)
);

GCM_AE_HW_1x8_GHASH_H_operand_gen grp_GHASH_H_operand_gen_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(X4_operand_int_reg),
    .H_operand_V_read(H5_operand_V_read_int_reg),
    .H_matrix_7(H_matrix_7_int_reg),
    .ap_return(grp_GHASH_H_operand_gen_fu_166_ap_return),
    .ap_ce(grp_GHASH_H_operand_gen_fu_166_ap_ce)
);

GCM_AE_HW_1x8_GHASH_H_operand_gen grp_GHASH_H_operand_gen_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(X5_operand_int_reg),
    .H_operand_V_read(H4_operand_V_read_int_reg),
    .H_matrix_7(H_matrix_7_int_reg),
    .ap_return(grp_GHASH_H_operand_gen_fu_176_ap_return),
    .ap_ce(grp_GHASH_H_operand_gen_fu_176_ap_ce)
);

GCM_AE_HW_1x8_GHASH_H_operand_gen grp_GHASH_H_operand_gen_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(X6_operand_int_reg),
    .H_operand_V_read(H3_operand_V_read_int_reg),
    .H_matrix_7(H_matrix_7_int_reg),
    .ap_return(grp_GHASH_H_operand_gen_fu_186_ap_return),
    .ap_ce(grp_GHASH_H_operand_gen_fu_186_ap_ce)
);

GCM_AE_HW_1x8_GHASH_H_operand_gen grp_GHASH_H_operand_gen_fu_196(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(X7_operand_int_reg),
    .H_operand_V_read(H2_operand_V_read_int_reg),
    .H_matrix_7(H_matrix_7_int_reg),
    .ap_return(grp_GHASH_H_operand_gen_fu_196_ap_return),
    .ap_ce(grp_GHASH_H_operand_gen_fu_196_ap_ce)
);

GCM_AE_HW_1x8_GHASH_H_operand_gen grp_GHASH_H_operand_gen_fu_206(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(X8_operand_int_reg),
    .H_operand_V_read(H1_operand_V_read_int_reg),
    .H_matrix_7(H_matrix_7_int_reg),
    .ap_return(grp_GHASH_H_operand_gen_fu_206_ap_return),
    .ap_ce(grp_GHASH_H_operand_gen_fu_206_ap_ce)
);

always @ (posedge ap_clk) begin
    H1_operand_V_read_int_reg <= H1_operand_V_read;
end

always @ (posedge ap_clk) begin
    H2_operand_V_read_int_reg <= H2_operand_V_read;
end

always @ (posedge ap_clk) begin
    H3_operand_V_read_int_reg <= H3_operand_V_read;
end

always @ (posedge ap_clk) begin
    H4_operand_V_read_int_reg <= H4_operand_V_read;
end

always @ (posedge ap_clk) begin
    H5_operand_V_read_int_reg <= H5_operand_V_read;
end

always @ (posedge ap_clk) begin
    H6_operand_V_read_int_reg <= H6_operand_V_read;
end

always @ (posedge ap_clk) begin
    H7_operand_V_read_int_reg <= H7_operand_V_read;
end

always @ (posedge ap_clk) begin
    H8_operand_V_read_int_reg <= H8_operand_V_read;
end

always @ (posedge ap_clk) begin
    H_matrix_7_int_reg <= H_matrix_7;
end

always @ (posedge ap_clk) begin
    X1_operand_int_reg <= X1_operand;
end

always @ (posedge ap_clk) begin
    X2_operand_int_reg <= X2_operand;
end

always @ (posedge ap_clk) begin
    X3_operand_int_reg <= X3_operand;
end

always @ (posedge ap_clk) begin
    X4_operand_int_reg <= X4_operand;
end

always @ (posedge ap_clk) begin
    X5_operand_int_reg <= X5_operand;
end

always @ (posedge ap_clk) begin
    X6_operand_int_reg <= X6_operand;
end

always @ (posedge ap_clk) begin
    X7_operand_int_reg <= X7_operand;
end

always @ (posedge ap_clk) begin
    X8_operand_int_reg <= X8_operand;
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp28)) begin
        grp_GHASH_H_operand_gen_fu_136_ap_ce = 1'b1;
    end else begin
        grp_GHASH_H_operand_gen_fu_136_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp29)) begin
        grp_GHASH_H_operand_gen_fu_146_ap_ce = 1'b1;
    end else begin
        grp_GHASH_H_operand_gen_fu_146_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp30)) begin
        grp_GHASH_H_operand_gen_fu_156_ap_ce = 1'b1;
    end else begin
        grp_GHASH_H_operand_gen_fu_156_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp31)) begin
        grp_GHASH_H_operand_gen_fu_166_ap_ce = 1'b1;
    end else begin
        grp_GHASH_H_operand_gen_fu_166_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp32)) begin
        grp_GHASH_H_operand_gen_fu_176_ap_ce = 1'b1;
    end else begin
        grp_GHASH_H_operand_gen_fu_176_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp33)) begin
        grp_GHASH_H_operand_gen_fu_186_ap_ce = 1'b1;
    end else begin
        grp_GHASH_H_operand_gen_fu_186_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp34)) begin
        grp_GHASH_H_operand_gen_fu_196_ap_ce = 1'b1;
    end else begin
        grp_GHASH_H_operand_gen_fu_196_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp35)) begin
        grp_GHASH_H_operand_gen_fu_206_ap_ce = 1'b1;
    end else begin
        grp_GHASH_H_operand_gen_fu_206_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp28 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp29 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp30 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp31 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp32 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp33 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp34 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp35 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call16 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call17 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call19 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call20 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call21 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call22 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_return_0 = grp_GHASH_H_operand_gen_fu_136_ap_return;

assign ap_return_1 = grp_GHASH_H_operand_gen_fu_146_ap_return;

assign ap_return_2 = grp_GHASH_H_operand_gen_fu_156_ap_return;

assign ap_return_3 = grp_GHASH_H_operand_gen_fu_166_ap_return;

assign ap_return_4 = grp_GHASH_H_operand_gen_fu_176_ap_return;

assign ap_return_5 = grp_GHASH_H_operand_gen_fu_186_ap_return;

assign ap_return_6 = grp_GHASH_H_operand_gen_fu_196_ap_return;

assign ap_return_7 = grp_GHASH_H_operand_gen_fu_206_ap_return;

endmodule //GCM_AE_HW_1x8_H_operand_gen_8x
