// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GCM_AE_HW_1x8_GCTR_Pipeline_enc_CB_store (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        CB_blocks_V_1,
        CB_V_address0,
        CB_V_ce0,
        CB_V_q0,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63,
        p_read64,
        p_read65,
        p_read66,
        p_read67,
        p_read68,
        p_read69,
        p_read70,
        p_read71,
        p_read72,
        p_read73,
        p_read74,
        p_read75,
        p_read76,
        p_read77,
        p_read78,
        p_read79,
        p_read80,
        p_read81,
        p_read82,
        p_read83,
        p_read84,
        p_read85,
        p_read86,
        p_read87,
        p_read88,
        p_read89,
        p_read90,
        p_read91,
        p_read92,
        p_read93,
        p_read94,
        p_read95,
        p_read96,
        p_read97,
        p_read98,
        p_read99,
        p_read100,
        p_read101,
        p_read102,
        p_read103,
        p_read104,
        p_read105,
        p_read106,
        p_read107,
        p_read108,
        p_read109,
        p_read110,
        p_read111,
        p_read112,
        p_read113,
        p_read114,
        p_read115,
        p_read116,
        p_read117,
        p_read118,
        p_read119,
        p_read120,
        p_read121,
        p_read122,
        p_read123,
        p_read124,
        p_read125,
        p_read126,
        p_read127,
        p_read128,
        p_read129,
        p_read130,
        p_read131,
        p_read132,
        p_read133,
        p_read134,
        p_read135,
        p_read136,
        p_read137,
        p_read138,
        p_read139,
        p_read140,
        p_read141,
        p_read142,
        p_read143,
        p_read144,
        p_read145,
        p_read146,
        p_read147,
        p_read148,
        p_read149,
        p_read150,
        p_read151,
        p_read152,
        p_read153,
        p_read154,
        p_read155,
        p_read156,
        p_read157,
        p_read158,
        p_read159,
        p_read160,
        p_read161,
        p_read162,
        p_read163,
        p_read164,
        p_read165,
        p_read166,
        p_read167,
        p_read168,
        p_read169,
        p_read170,
        p_read171,
        p_read172,
        p_read173,
        p_read174,
        p_read175,
        p_read176,
        p_read177,
        p_read178,
        p_read179,
        p_read180,
        p_read181,
        p_read182,
        p_read183,
        p_read184,
        p_read185,
        p_read186,
        p_read187,
        p_read188,
        p_read189,
        p_read190,
        p_read191,
        p_read192,
        p_read193,
        p_read194,
        p_read195,
        p_read196,
        p_read197,
        p_read198,
        p_read199,
        p_read200,
        p_read201,
        p_read202,
        p_read203,
        p_read204,
        p_read205,
        p_read206,
        p_read207,
        p_read208,
        p_read209,
        p_read210,
        p_read211,
        p_read212,
        p_read213,
        p_read214,
        p_read215,
        p_read216,
        p_read217,
        p_read218,
        p_read219,
        p_read220,
        p_read221,
        p_read222,
        p_read223,
        p_read224,
        p_read225,
        p_read226,
        p_read227,
        p_read228,
        p_read229,
        p_read230,
        p_read231,
        p_read232,
        p_read233,
        p_read234,
        p_read235,
        p_read236,
        p_read237,
        p_read238,
        p_read239,
        enc_CB_V_address0,
        enc_CB_V_ce0,
        enc_CB_V_we0,
        enc_CB_V_d0,
        grp_AES_cipher_fu_3942_p_din1,
        grp_AES_cipher_fu_3942_p_din2,
        grp_AES_cipher_fu_3942_p_din3,
        grp_AES_cipher_fu_3942_p_din4,
        grp_AES_cipher_fu_3942_p_din5,
        grp_AES_cipher_fu_3942_p_din6,
        grp_AES_cipher_fu_3942_p_din7,
        grp_AES_cipher_fu_3942_p_din8,
        grp_AES_cipher_fu_3942_p_din9,
        grp_AES_cipher_fu_3942_p_din10,
        grp_AES_cipher_fu_3942_p_din11,
        grp_AES_cipher_fu_3942_p_din12,
        grp_AES_cipher_fu_3942_p_din13,
        grp_AES_cipher_fu_3942_p_din14,
        grp_AES_cipher_fu_3942_p_din15,
        grp_AES_cipher_fu_3942_p_din16,
        grp_AES_cipher_fu_3942_p_din17,
        grp_AES_cipher_fu_3942_p_din18,
        grp_AES_cipher_fu_3942_p_din19,
        grp_AES_cipher_fu_3942_p_din20,
        grp_AES_cipher_fu_3942_p_din21,
        grp_AES_cipher_fu_3942_p_din22,
        grp_AES_cipher_fu_3942_p_din23,
        grp_AES_cipher_fu_3942_p_din24,
        grp_AES_cipher_fu_3942_p_din25,
        grp_AES_cipher_fu_3942_p_din26,
        grp_AES_cipher_fu_3942_p_din27,
        grp_AES_cipher_fu_3942_p_din28,
        grp_AES_cipher_fu_3942_p_din29,
        grp_AES_cipher_fu_3942_p_din30,
        grp_AES_cipher_fu_3942_p_din31,
        grp_AES_cipher_fu_3942_p_din32,
        grp_AES_cipher_fu_3942_p_din33,
        grp_AES_cipher_fu_3942_p_din34,
        grp_AES_cipher_fu_3942_p_din35,
        grp_AES_cipher_fu_3942_p_din36,
        grp_AES_cipher_fu_3942_p_din37,
        grp_AES_cipher_fu_3942_p_din38,
        grp_AES_cipher_fu_3942_p_din39,
        grp_AES_cipher_fu_3942_p_din40,
        grp_AES_cipher_fu_3942_p_din41,
        grp_AES_cipher_fu_3942_p_din42,
        grp_AES_cipher_fu_3942_p_din43,
        grp_AES_cipher_fu_3942_p_din44,
        grp_AES_cipher_fu_3942_p_din45,
        grp_AES_cipher_fu_3942_p_din46,
        grp_AES_cipher_fu_3942_p_din47,
        grp_AES_cipher_fu_3942_p_din48,
        grp_AES_cipher_fu_3942_p_din49,
        grp_AES_cipher_fu_3942_p_din50,
        grp_AES_cipher_fu_3942_p_din51,
        grp_AES_cipher_fu_3942_p_din52,
        grp_AES_cipher_fu_3942_p_din53,
        grp_AES_cipher_fu_3942_p_din54,
        grp_AES_cipher_fu_3942_p_din55,
        grp_AES_cipher_fu_3942_p_din56,
        grp_AES_cipher_fu_3942_p_din57,
        grp_AES_cipher_fu_3942_p_din58,
        grp_AES_cipher_fu_3942_p_din59,
        grp_AES_cipher_fu_3942_p_din60,
        grp_AES_cipher_fu_3942_p_din61,
        grp_AES_cipher_fu_3942_p_din62,
        grp_AES_cipher_fu_3942_p_din63,
        grp_AES_cipher_fu_3942_p_din64,
        grp_AES_cipher_fu_3942_p_din65,
        grp_AES_cipher_fu_3942_p_din66,
        grp_AES_cipher_fu_3942_p_din67,
        grp_AES_cipher_fu_3942_p_din68,
        grp_AES_cipher_fu_3942_p_din69,
        grp_AES_cipher_fu_3942_p_din70,
        grp_AES_cipher_fu_3942_p_din71,
        grp_AES_cipher_fu_3942_p_din72,
        grp_AES_cipher_fu_3942_p_din73,
        grp_AES_cipher_fu_3942_p_din74,
        grp_AES_cipher_fu_3942_p_din75,
        grp_AES_cipher_fu_3942_p_din76,
        grp_AES_cipher_fu_3942_p_din77,
        grp_AES_cipher_fu_3942_p_din78,
        grp_AES_cipher_fu_3942_p_din79,
        grp_AES_cipher_fu_3942_p_din80,
        grp_AES_cipher_fu_3942_p_din81,
        grp_AES_cipher_fu_3942_p_din82,
        grp_AES_cipher_fu_3942_p_din83,
        grp_AES_cipher_fu_3942_p_din84,
        grp_AES_cipher_fu_3942_p_din85,
        grp_AES_cipher_fu_3942_p_din86,
        grp_AES_cipher_fu_3942_p_din87,
        grp_AES_cipher_fu_3942_p_din88,
        grp_AES_cipher_fu_3942_p_din89,
        grp_AES_cipher_fu_3942_p_din90,
        grp_AES_cipher_fu_3942_p_din91,
        grp_AES_cipher_fu_3942_p_din92,
        grp_AES_cipher_fu_3942_p_din93,
        grp_AES_cipher_fu_3942_p_din94,
        grp_AES_cipher_fu_3942_p_din95,
        grp_AES_cipher_fu_3942_p_din96,
        grp_AES_cipher_fu_3942_p_din97,
        grp_AES_cipher_fu_3942_p_din98,
        grp_AES_cipher_fu_3942_p_din99,
        grp_AES_cipher_fu_3942_p_din100,
        grp_AES_cipher_fu_3942_p_din101,
        grp_AES_cipher_fu_3942_p_din102,
        grp_AES_cipher_fu_3942_p_din103,
        grp_AES_cipher_fu_3942_p_din104,
        grp_AES_cipher_fu_3942_p_din105,
        grp_AES_cipher_fu_3942_p_din106,
        grp_AES_cipher_fu_3942_p_din107,
        grp_AES_cipher_fu_3942_p_din108,
        grp_AES_cipher_fu_3942_p_din109,
        grp_AES_cipher_fu_3942_p_din110,
        grp_AES_cipher_fu_3942_p_din111,
        grp_AES_cipher_fu_3942_p_din112,
        grp_AES_cipher_fu_3942_p_din113,
        grp_AES_cipher_fu_3942_p_din114,
        grp_AES_cipher_fu_3942_p_din115,
        grp_AES_cipher_fu_3942_p_din116,
        grp_AES_cipher_fu_3942_p_din117,
        grp_AES_cipher_fu_3942_p_din118,
        grp_AES_cipher_fu_3942_p_din119,
        grp_AES_cipher_fu_3942_p_din120,
        grp_AES_cipher_fu_3942_p_din121,
        grp_AES_cipher_fu_3942_p_din122,
        grp_AES_cipher_fu_3942_p_din123,
        grp_AES_cipher_fu_3942_p_din124,
        grp_AES_cipher_fu_3942_p_din125,
        grp_AES_cipher_fu_3942_p_din126,
        grp_AES_cipher_fu_3942_p_din127,
        grp_AES_cipher_fu_3942_p_din128,
        grp_AES_cipher_fu_3942_p_din129,
        grp_AES_cipher_fu_3942_p_din130,
        grp_AES_cipher_fu_3942_p_din131,
        grp_AES_cipher_fu_3942_p_din132,
        grp_AES_cipher_fu_3942_p_din133,
        grp_AES_cipher_fu_3942_p_din134,
        grp_AES_cipher_fu_3942_p_din135,
        grp_AES_cipher_fu_3942_p_din136,
        grp_AES_cipher_fu_3942_p_din137,
        grp_AES_cipher_fu_3942_p_din138,
        grp_AES_cipher_fu_3942_p_din139,
        grp_AES_cipher_fu_3942_p_din140,
        grp_AES_cipher_fu_3942_p_din141,
        grp_AES_cipher_fu_3942_p_din142,
        grp_AES_cipher_fu_3942_p_din143,
        grp_AES_cipher_fu_3942_p_din144,
        grp_AES_cipher_fu_3942_p_din145,
        grp_AES_cipher_fu_3942_p_din146,
        grp_AES_cipher_fu_3942_p_din147,
        grp_AES_cipher_fu_3942_p_din148,
        grp_AES_cipher_fu_3942_p_din149,
        grp_AES_cipher_fu_3942_p_din150,
        grp_AES_cipher_fu_3942_p_din151,
        grp_AES_cipher_fu_3942_p_din152,
        grp_AES_cipher_fu_3942_p_din153,
        grp_AES_cipher_fu_3942_p_din154,
        grp_AES_cipher_fu_3942_p_din155,
        grp_AES_cipher_fu_3942_p_din156,
        grp_AES_cipher_fu_3942_p_din157,
        grp_AES_cipher_fu_3942_p_din158,
        grp_AES_cipher_fu_3942_p_din159,
        grp_AES_cipher_fu_3942_p_din160,
        grp_AES_cipher_fu_3942_p_din161,
        grp_AES_cipher_fu_3942_p_din162,
        grp_AES_cipher_fu_3942_p_din163,
        grp_AES_cipher_fu_3942_p_din164,
        grp_AES_cipher_fu_3942_p_din165,
        grp_AES_cipher_fu_3942_p_din166,
        grp_AES_cipher_fu_3942_p_din167,
        grp_AES_cipher_fu_3942_p_din168,
        grp_AES_cipher_fu_3942_p_din169,
        grp_AES_cipher_fu_3942_p_din170,
        grp_AES_cipher_fu_3942_p_din171,
        grp_AES_cipher_fu_3942_p_din172,
        grp_AES_cipher_fu_3942_p_din173,
        grp_AES_cipher_fu_3942_p_din174,
        grp_AES_cipher_fu_3942_p_din175,
        grp_AES_cipher_fu_3942_p_din176,
        grp_AES_cipher_fu_3942_p_din177,
        grp_AES_cipher_fu_3942_p_din178,
        grp_AES_cipher_fu_3942_p_din179,
        grp_AES_cipher_fu_3942_p_din180,
        grp_AES_cipher_fu_3942_p_din181,
        grp_AES_cipher_fu_3942_p_din182,
        grp_AES_cipher_fu_3942_p_din183,
        grp_AES_cipher_fu_3942_p_din184,
        grp_AES_cipher_fu_3942_p_din185,
        grp_AES_cipher_fu_3942_p_din186,
        grp_AES_cipher_fu_3942_p_din187,
        grp_AES_cipher_fu_3942_p_din188,
        grp_AES_cipher_fu_3942_p_din189,
        grp_AES_cipher_fu_3942_p_din190,
        grp_AES_cipher_fu_3942_p_din191,
        grp_AES_cipher_fu_3942_p_din192,
        grp_AES_cipher_fu_3942_p_din193,
        grp_AES_cipher_fu_3942_p_din194,
        grp_AES_cipher_fu_3942_p_din195,
        grp_AES_cipher_fu_3942_p_din196,
        grp_AES_cipher_fu_3942_p_din197,
        grp_AES_cipher_fu_3942_p_din198,
        grp_AES_cipher_fu_3942_p_din199,
        grp_AES_cipher_fu_3942_p_din200,
        grp_AES_cipher_fu_3942_p_din201,
        grp_AES_cipher_fu_3942_p_din202,
        grp_AES_cipher_fu_3942_p_din203,
        grp_AES_cipher_fu_3942_p_din204,
        grp_AES_cipher_fu_3942_p_din205,
        grp_AES_cipher_fu_3942_p_din206,
        grp_AES_cipher_fu_3942_p_din207,
        grp_AES_cipher_fu_3942_p_din208,
        grp_AES_cipher_fu_3942_p_din209,
        grp_AES_cipher_fu_3942_p_din210,
        grp_AES_cipher_fu_3942_p_din211,
        grp_AES_cipher_fu_3942_p_din212,
        grp_AES_cipher_fu_3942_p_din213,
        grp_AES_cipher_fu_3942_p_din214,
        grp_AES_cipher_fu_3942_p_din215,
        grp_AES_cipher_fu_3942_p_din216,
        grp_AES_cipher_fu_3942_p_din217,
        grp_AES_cipher_fu_3942_p_din218,
        grp_AES_cipher_fu_3942_p_din219,
        grp_AES_cipher_fu_3942_p_din220,
        grp_AES_cipher_fu_3942_p_din221,
        grp_AES_cipher_fu_3942_p_din222,
        grp_AES_cipher_fu_3942_p_din223,
        grp_AES_cipher_fu_3942_p_din224,
        grp_AES_cipher_fu_3942_p_din225,
        grp_AES_cipher_fu_3942_p_din226,
        grp_AES_cipher_fu_3942_p_din227,
        grp_AES_cipher_fu_3942_p_din228,
        grp_AES_cipher_fu_3942_p_din229,
        grp_AES_cipher_fu_3942_p_din230,
        grp_AES_cipher_fu_3942_p_din231,
        grp_AES_cipher_fu_3942_p_din232,
        grp_AES_cipher_fu_3942_p_din233,
        grp_AES_cipher_fu_3942_p_din234,
        grp_AES_cipher_fu_3942_p_din235,
        grp_AES_cipher_fu_3942_p_din236,
        grp_AES_cipher_fu_3942_p_din237,
        grp_AES_cipher_fu_3942_p_din238,
        grp_AES_cipher_fu_3942_p_din239,
        grp_AES_cipher_fu_3942_p_din240,
        grp_AES_cipher_fu_3942_p_din241,
        grp_AES_cipher_fu_3942_p_dout0,
        grp_AES_cipher_fu_3942_p_ce,
        grp_AES_cipher_fu_3942_p_start,
        grp_AES_cipher_fu_3942_p_ready,
        grp_AES_cipher_fu_3942_p_done,
        grp_AES_cipher_fu_3942_p_idle
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [57:0] CB_blocks_V_1;
output  [9:0] CB_V_address0;
output   CB_V_ce0;
input  [127:0] CB_V_q0;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;
input  [7:0] p_read9;
input  [7:0] p_read10;
input  [7:0] p_read11;
input  [7:0] p_read12;
input  [7:0] p_read13;
input  [7:0] p_read14;
input  [7:0] p_read15;
input  [7:0] p_read16;
input  [7:0] p_read17;
input  [7:0] p_read18;
input  [7:0] p_read19;
input  [7:0] p_read20;
input  [7:0] p_read21;
input  [7:0] p_read22;
input  [7:0] p_read23;
input  [7:0] p_read24;
input  [7:0] p_read25;
input  [7:0] p_read26;
input  [7:0] p_read27;
input  [7:0] p_read28;
input  [7:0] p_read29;
input  [7:0] p_read30;
input  [7:0] p_read31;
input  [7:0] p_read32;
input  [7:0] p_read33;
input  [7:0] p_read34;
input  [7:0] p_read35;
input  [7:0] p_read36;
input  [7:0] p_read37;
input  [7:0] p_read38;
input  [7:0] p_read39;
input  [7:0] p_read40;
input  [7:0] p_read41;
input  [7:0] p_read42;
input  [7:0] p_read43;
input  [7:0] p_read44;
input  [7:0] p_read45;
input  [7:0] p_read46;
input  [7:0] p_read47;
input  [7:0] p_read48;
input  [7:0] p_read49;
input  [7:0] p_read50;
input  [7:0] p_read51;
input  [7:0] p_read52;
input  [7:0] p_read53;
input  [7:0] p_read54;
input  [7:0] p_read55;
input  [7:0] p_read56;
input  [7:0] p_read57;
input  [7:0] p_read58;
input  [7:0] p_read59;
input  [7:0] p_read60;
input  [7:0] p_read61;
input  [7:0] p_read62;
input  [7:0] p_read63;
input  [7:0] p_read64;
input  [7:0] p_read65;
input  [7:0] p_read66;
input  [7:0] p_read67;
input  [7:0] p_read68;
input  [7:0] p_read69;
input  [7:0] p_read70;
input  [7:0] p_read71;
input  [7:0] p_read72;
input  [7:0] p_read73;
input  [7:0] p_read74;
input  [7:0] p_read75;
input  [7:0] p_read76;
input  [7:0] p_read77;
input  [7:0] p_read78;
input  [7:0] p_read79;
input  [7:0] p_read80;
input  [7:0] p_read81;
input  [7:0] p_read82;
input  [7:0] p_read83;
input  [7:0] p_read84;
input  [7:0] p_read85;
input  [7:0] p_read86;
input  [7:0] p_read87;
input  [7:0] p_read88;
input  [7:0] p_read89;
input  [7:0] p_read90;
input  [7:0] p_read91;
input  [7:0] p_read92;
input  [7:0] p_read93;
input  [7:0] p_read94;
input  [7:0] p_read95;
input  [7:0] p_read96;
input  [7:0] p_read97;
input  [7:0] p_read98;
input  [7:0] p_read99;
input  [7:0] p_read100;
input  [7:0] p_read101;
input  [7:0] p_read102;
input  [7:0] p_read103;
input  [7:0] p_read104;
input  [7:0] p_read105;
input  [7:0] p_read106;
input  [7:0] p_read107;
input  [7:0] p_read108;
input  [7:0] p_read109;
input  [7:0] p_read110;
input  [7:0] p_read111;
input  [7:0] p_read112;
input  [7:0] p_read113;
input  [7:0] p_read114;
input  [7:0] p_read115;
input  [7:0] p_read116;
input  [7:0] p_read117;
input  [7:0] p_read118;
input  [7:0] p_read119;
input  [7:0] p_read120;
input  [7:0] p_read121;
input  [7:0] p_read122;
input  [7:0] p_read123;
input  [7:0] p_read124;
input  [7:0] p_read125;
input  [7:0] p_read126;
input  [7:0] p_read127;
input  [7:0] p_read128;
input  [7:0] p_read129;
input  [7:0] p_read130;
input  [7:0] p_read131;
input  [7:0] p_read132;
input  [7:0] p_read133;
input  [7:0] p_read134;
input  [7:0] p_read135;
input  [7:0] p_read136;
input  [7:0] p_read137;
input  [7:0] p_read138;
input  [7:0] p_read139;
input  [7:0] p_read140;
input  [7:0] p_read141;
input  [7:0] p_read142;
input  [7:0] p_read143;
input  [7:0] p_read144;
input  [7:0] p_read145;
input  [7:0] p_read146;
input  [7:0] p_read147;
input  [7:0] p_read148;
input  [7:0] p_read149;
input  [7:0] p_read150;
input  [7:0] p_read151;
input  [7:0] p_read152;
input  [7:0] p_read153;
input  [7:0] p_read154;
input  [7:0] p_read155;
input  [7:0] p_read156;
input  [7:0] p_read157;
input  [7:0] p_read158;
input  [7:0] p_read159;
input  [7:0] p_read160;
input  [7:0] p_read161;
input  [7:0] p_read162;
input  [7:0] p_read163;
input  [7:0] p_read164;
input  [7:0] p_read165;
input  [7:0] p_read166;
input  [7:0] p_read167;
input  [7:0] p_read168;
input  [7:0] p_read169;
input  [7:0] p_read170;
input  [7:0] p_read171;
input  [7:0] p_read172;
input  [7:0] p_read173;
input  [7:0] p_read174;
input  [7:0] p_read175;
input  [7:0] p_read176;
input  [7:0] p_read177;
input  [7:0] p_read178;
input  [7:0] p_read179;
input  [7:0] p_read180;
input  [7:0] p_read181;
input  [7:0] p_read182;
input  [7:0] p_read183;
input  [7:0] p_read184;
input  [7:0] p_read185;
input  [7:0] p_read186;
input  [7:0] p_read187;
input  [7:0] p_read188;
input  [7:0] p_read189;
input  [7:0] p_read190;
input  [7:0] p_read191;
input  [7:0] p_read192;
input  [7:0] p_read193;
input  [7:0] p_read194;
input  [7:0] p_read195;
input  [7:0] p_read196;
input  [7:0] p_read197;
input  [7:0] p_read198;
input  [7:0] p_read199;
input  [7:0] p_read200;
input  [7:0] p_read201;
input  [7:0] p_read202;
input  [7:0] p_read203;
input  [7:0] p_read204;
input  [7:0] p_read205;
input  [7:0] p_read206;
input  [7:0] p_read207;
input  [7:0] p_read208;
input  [7:0] p_read209;
input  [7:0] p_read210;
input  [7:0] p_read211;
input  [7:0] p_read212;
input  [7:0] p_read213;
input  [7:0] p_read214;
input  [7:0] p_read215;
input  [7:0] p_read216;
input  [7:0] p_read217;
input  [7:0] p_read218;
input  [7:0] p_read219;
input  [7:0] p_read220;
input  [7:0] p_read221;
input  [7:0] p_read222;
input  [7:0] p_read223;
input  [7:0] p_read224;
input  [7:0] p_read225;
input  [7:0] p_read226;
input  [7:0] p_read227;
input  [7:0] p_read228;
input  [7:0] p_read229;
input  [7:0] p_read230;
input  [7:0] p_read231;
input  [7:0] p_read232;
input  [7:0] p_read233;
input  [7:0] p_read234;
input  [7:0] p_read235;
input  [7:0] p_read236;
input  [7:0] p_read237;
input  [7:0] p_read238;
input  [7:0] p_read239;
output  [9:0] enc_CB_V_address0;
output   enc_CB_V_ce0;
output   enc_CB_V_we0;
output  [127:0] enc_CB_V_d0;
output  [127:0] grp_AES_cipher_fu_3942_p_din1;
output  [7:0] grp_AES_cipher_fu_3942_p_din2;
output  [7:0] grp_AES_cipher_fu_3942_p_din3;
output  [7:0] grp_AES_cipher_fu_3942_p_din4;
output  [7:0] grp_AES_cipher_fu_3942_p_din5;
output  [7:0] grp_AES_cipher_fu_3942_p_din6;
output  [7:0] grp_AES_cipher_fu_3942_p_din7;
output  [7:0] grp_AES_cipher_fu_3942_p_din8;
output  [7:0] grp_AES_cipher_fu_3942_p_din9;
output  [7:0] grp_AES_cipher_fu_3942_p_din10;
output  [7:0] grp_AES_cipher_fu_3942_p_din11;
output  [7:0] grp_AES_cipher_fu_3942_p_din12;
output  [7:0] grp_AES_cipher_fu_3942_p_din13;
output  [7:0] grp_AES_cipher_fu_3942_p_din14;
output  [7:0] grp_AES_cipher_fu_3942_p_din15;
output  [7:0] grp_AES_cipher_fu_3942_p_din16;
output  [7:0] grp_AES_cipher_fu_3942_p_din17;
output  [7:0] grp_AES_cipher_fu_3942_p_din18;
output  [7:0] grp_AES_cipher_fu_3942_p_din19;
output  [7:0] grp_AES_cipher_fu_3942_p_din20;
output  [7:0] grp_AES_cipher_fu_3942_p_din21;
output  [7:0] grp_AES_cipher_fu_3942_p_din22;
output  [7:0] grp_AES_cipher_fu_3942_p_din23;
output  [7:0] grp_AES_cipher_fu_3942_p_din24;
output  [7:0] grp_AES_cipher_fu_3942_p_din25;
output  [7:0] grp_AES_cipher_fu_3942_p_din26;
output  [7:0] grp_AES_cipher_fu_3942_p_din27;
output  [7:0] grp_AES_cipher_fu_3942_p_din28;
output  [7:0] grp_AES_cipher_fu_3942_p_din29;
output  [7:0] grp_AES_cipher_fu_3942_p_din30;
output  [7:0] grp_AES_cipher_fu_3942_p_din31;
output  [7:0] grp_AES_cipher_fu_3942_p_din32;
output  [7:0] grp_AES_cipher_fu_3942_p_din33;
output  [7:0] grp_AES_cipher_fu_3942_p_din34;
output  [7:0] grp_AES_cipher_fu_3942_p_din35;
output  [7:0] grp_AES_cipher_fu_3942_p_din36;
output  [7:0] grp_AES_cipher_fu_3942_p_din37;
output  [7:0] grp_AES_cipher_fu_3942_p_din38;
output  [7:0] grp_AES_cipher_fu_3942_p_din39;
output  [7:0] grp_AES_cipher_fu_3942_p_din40;
output  [7:0] grp_AES_cipher_fu_3942_p_din41;
output  [7:0] grp_AES_cipher_fu_3942_p_din42;
output  [7:0] grp_AES_cipher_fu_3942_p_din43;
output  [7:0] grp_AES_cipher_fu_3942_p_din44;
output  [7:0] grp_AES_cipher_fu_3942_p_din45;
output  [7:0] grp_AES_cipher_fu_3942_p_din46;
output  [7:0] grp_AES_cipher_fu_3942_p_din47;
output  [7:0] grp_AES_cipher_fu_3942_p_din48;
output  [7:0] grp_AES_cipher_fu_3942_p_din49;
output  [7:0] grp_AES_cipher_fu_3942_p_din50;
output  [7:0] grp_AES_cipher_fu_3942_p_din51;
output  [7:0] grp_AES_cipher_fu_3942_p_din52;
output  [7:0] grp_AES_cipher_fu_3942_p_din53;
output  [7:0] grp_AES_cipher_fu_3942_p_din54;
output  [7:0] grp_AES_cipher_fu_3942_p_din55;
output  [7:0] grp_AES_cipher_fu_3942_p_din56;
output  [7:0] grp_AES_cipher_fu_3942_p_din57;
output  [7:0] grp_AES_cipher_fu_3942_p_din58;
output  [7:0] grp_AES_cipher_fu_3942_p_din59;
output  [7:0] grp_AES_cipher_fu_3942_p_din60;
output  [7:0] grp_AES_cipher_fu_3942_p_din61;
output  [7:0] grp_AES_cipher_fu_3942_p_din62;
output  [7:0] grp_AES_cipher_fu_3942_p_din63;
output  [7:0] grp_AES_cipher_fu_3942_p_din64;
output  [7:0] grp_AES_cipher_fu_3942_p_din65;
output  [7:0] grp_AES_cipher_fu_3942_p_din66;
output  [7:0] grp_AES_cipher_fu_3942_p_din67;
output  [7:0] grp_AES_cipher_fu_3942_p_din68;
output  [7:0] grp_AES_cipher_fu_3942_p_din69;
output  [7:0] grp_AES_cipher_fu_3942_p_din70;
output  [7:0] grp_AES_cipher_fu_3942_p_din71;
output  [7:0] grp_AES_cipher_fu_3942_p_din72;
output  [7:0] grp_AES_cipher_fu_3942_p_din73;
output  [7:0] grp_AES_cipher_fu_3942_p_din74;
output  [7:0] grp_AES_cipher_fu_3942_p_din75;
output  [7:0] grp_AES_cipher_fu_3942_p_din76;
output  [7:0] grp_AES_cipher_fu_3942_p_din77;
output  [7:0] grp_AES_cipher_fu_3942_p_din78;
output  [7:0] grp_AES_cipher_fu_3942_p_din79;
output  [7:0] grp_AES_cipher_fu_3942_p_din80;
output  [7:0] grp_AES_cipher_fu_3942_p_din81;
output  [7:0] grp_AES_cipher_fu_3942_p_din82;
output  [7:0] grp_AES_cipher_fu_3942_p_din83;
output  [7:0] grp_AES_cipher_fu_3942_p_din84;
output  [7:0] grp_AES_cipher_fu_3942_p_din85;
output  [7:0] grp_AES_cipher_fu_3942_p_din86;
output  [7:0] grp_AES_cipher_fu_3942_p_din87;
output  [7:0] grp_AES_cipher_fu_3942_p_din88;
output  [7:0] grp_AES_cipher_fu_3942_p_din89;
output  [7:0] grp_AES_cipher_fu_3942_p_din90;
output  [7:0] grp_AES_cipher_fu_3942_p_din91;
output  [7:0] grp_AES_cipher_fu_3942_p_din92;
output  [7:0] grp_AES_cipher_fu_3942_p_din93;
output  [7:0] grp_AES_cipher_fu_3942_p_din94;
output  [7:0] grp_AES_cipher_fu_3942_p_din95;
output  [7:0] grp_AES_cipher_fu_3942_p_din96;
output  [7:0] grp_AES_cipher_fu_3942_p_din97;
output  [7:0] grp_AES_cipher_fu_3942_p_din98;
output  [7:0] grp_AES_cipher_fu_3942_p_din99;
output  [7:0] grp_AES_cipher_fu_3942_p_din100;
output  [7:0] grp_AES_cipher_fu_3942_p_din101;
output  [7:0] grp_AES_cipher_fu_3942_p_din102;
output  [7:0] grp_AES_cipher_fu_3942_p_din103;
output  [7:0] grp_AES_cipher_fu_3942_p_din104;
output  [7:0] grp_AES_cipher_fu_3942_p_din105;
output  [7:0] grp_AES_cipher_fu_3942_p_din106;
output  [7:0] grp_AES_cipher_fu_3942_p_din107;
output  [7:0] grp_AES_cipher_fu_3942_p_din108;
output  [7:0] grp_AES_cipher_fu_3942_p_din109;
output  [7:0] grp_AES_cipher_fu_3942_p_din110;
output  [7:0] grp_AES_cipher_fu_3942_p_din111;
output  [7:0] grp_AES_cipher_fu_3942_p_din112;
output  [7:0] grp_AES_cipher_fu_3942_p_din113;
output  [7:0] grp_AES_cipher_fu_3942_p_din114;
output  [7:0] grp_AES_cipher_fu_3942_p_din115;
output  [7:0] grp_AES_cipher_fu_3942_p_din116;
output  [7:0] grp_AES_cipher_fu_3942_p_din117;
output  [7:0] grp_AES_cipher_fu_3942_p_din118;
output  [7:0] grp_AES_cipher_fu_3942_p_din119;
output  [7:0] grp_AES_cipher_fu_3942_p_din120;
output  [7:0] grp_AES_cipher_fu_3942_p_din121;
output  [7:0] grp_AES_cipher_fu_3942_p_din122;
output  [7:0] grp_AES_cipher_fu_3942_p_din123;
output  [7:0] grp_AES_cipher_fu_3942_p_din124;
output  [7:0] grp_AES_cipher_fu_3942_p_din125;
output  [7:0] grp_AES_cipher_fu_3942_p_din126;
output  [7:0] grp_AES_cipher_fu_3942_p_din127;
output  [7:0] grp_AES_cipher_fu_3942_p_din128;
output  [7:0] grp_AES_cipher_fu_3942_p_din129;
output  [7:0] grp_AES_cipher_fu_3942_p_din130;
output  [7:0] grp_AES_cipher_fu_3942_p_din131;
output  [7:0] grp_AES_cipher_fu_3942_p_din132;
output  [7:0] grp_AES_cipher_fu_3942_p_din133;
output  [7:0] grp_AES_cipher_fu_3942_p_din134;
output  [7:0] grp_AES_cipher_fu_3942_p_din135;
output  [7:0] grp_AES_cipher_fu_3942_p_din136;
output  [7:0] grp_AES_cipher_fu_3942_p_din137;
output  [7:0] grp_AES_cipher_fu_3942_p_din138;
output  [7:0] grp_AES_cipher_fu_3942_p_din139;
output  [7:0] grp_AES_cipher_fu_3942_p_din140;
output  [7:0] grp_AES_cipher_fu_3942_p_din141;
output  [7:0] grp_AES_cipher_fu_3942_p_din142;
output  [7:0] grp_AES_cipher_fu_3942_p_din143;
output  [7:0] grp_AES_cipher_fu_3942_p_din144;
output  [7:0] grp_AES_cipher_fu_3942_p_din145;
output  [7:0] grp_AES_cipher_fu_3942_p_din146;
output  [7:0] grp_AES_cipher_fu_3942_p_din147;
output  [7:0] grp_AES_cipher_fu_3942_p_din148;
output  [7:0] grp_AES_cipher_fu_3942_p_din149;
output  [7:0] grp_AES_cipher_fu_3942_p_din150;
output  [7:0] grp_AES_cipher_fu_3942_p_din151;
output  [7:0] grp_AES_cipher_fu_3942_p_din152;
output  [7:0] grp_AES_cipher_fu_3942_p_din153;
output  [7:0] grp_AES_cipher_fu_3942_p_din154;
output  [7:0] grp_AES_cipher_fu_3942_p_din155;
output  [7:0] grp_AES_cipher_fu_3942_p_din156;
output  [7:0] grp_AES_cipher_fu_3942_p_din157;
output  [7:0] grp_AES_cipher_fu_3942_p_din158;
output  [7:0] grp_AES_cipher_fu_3942_p_din159;
output  [7:0] grp_AES_cipher_fu_3942_p_din160;
output  [7:0] grp_AES_cipher_fu_3942_p_din161;
output  [7:0] grp_AES_cipher_fu_3942_p_din162;
output  [7:0] grp_AES_cipher_fu_3942_p_din163;
output  [7:0] grp_AES_cipher_fu_3942_p_din164;
output  [7:0] grp_AES_cipher_fu_3942_p_din165;
output  [7:0] grp_AES_cipher_fu_3942_p_din166;
output  [7:0] grp_AES_cipher_fu_3942_p_din167;
output  [7:0] grp_AES_cipher_fu_3942_p_din168;
output  [7:0] grp_AES_cipher_fu_3942_p_din169;
output  [7:0] grp_AES_cipher_fu_3942_p_din170;
output  [7:0] grp_AES_cipher_fu_3942_p_din171;
output  [7:0] grp_AES_cipher_fu_3942_p_din172;
output  [7:0] grp_AES_cipher_fu_3942_p_din173;
output  [7:0] grp_AES_cipher_fu_3942_p_din174;
output  [7:0] grp_AES_cipher_fu_3942_p_din175;
output  [7:0] grp_AES_cipher_fu_3942_p_din176;
output  [7:0] grp_AES_cipher_fu_3942_p_din177;
output  [7:0] grp_AES_cipher_fu_3942_p_din178;
output  [7:0] grp_AES_cipher_fu_3942_p_din179;
output  [7:0] grp_AES_cipher_fu_3942_p_din180;
output  [7:0] grp_AES_cipher_fu_3942_p_din181;
output  [7:0] grp_AES_cipher_fu_3942_p_din182;
output  [7:0] grp_AES_cipher_fu_3942_p_din183;
output  [7:0] grp_AES_cipher_fu_3942_p_din184;
output  [7:0] grp_AES_cipher_fu_3942_p_din185;
output  [7:0] grp_AES_cipher_fu_3942_p_din186;
output  [7:0] grp_AES_cipher_fu_3942_p_din187;
output  [7:0] grp_AES_cipher_fu_3942_p_din188;
output  [7:0] grp_AES_cipher_fu_3942_p_din189;
output  [7:0] grp_AES_cipher_fu_3942_p_din190;
output  [7:0] grp_AES_cipher_fu_3942_p_din191;
output  [7:0] grp_AES_cipher_fu_3942_p_din192;
output  [7:0] grp_AES_cipher_fu_3942_p_din193;
output  [7:0] grp_AES_cipher_fu_3942_p_din194;
output  [7:0] grp_AES_cipher_fu_3942_p_din195;
output  [7:0] grp_AES_cipher_fu_3942_p_din196;
output  [7:0] grp_AES_cipher_fu_3942_p_din197;
output  [7:0] grp_AES_cipher_fu_3942_p_din198;
output  [7:0] grp_AES_cipher_fu_3942_p_din199;
output  [7:0] grp_AES_cipher_fu_3942_p_din200;
output  [7:0] grp_AES_cipher_fu_3942_p_din201;
output  [7:0] grp_AES_cipher_fu_3942_p_din202;
output  [7:0] grp_AES_cipher_fu_3942_p_din203;
output  [7:0] grp_AES_cipher_fu_3942_p_din204;
output  [7:0] grp_AES_cipher_fu_3942_p_din205;
output  [7:0] grp_AES_cipher_fu_3942_p_din206;
output  [7:0] grp_AES_cipher_fu_3942_p_din207;
output  [7:0] grp_AES_cipher_fu_3942_p_din208;
output  [7:0] grp_AES_cipher_fu_3942_p_din209;
output  [7:0] grp_AES_cipher_fu_3942_p_din210;
output  [7:0] grp_AES_cipher_fu_3942_p_din211;
output  [7:0] grp_AES_cipher_fu_3942_p_din212;
output  [7:0] grp_AES_cipher_fu_3942_p_din213;
output  [7:0] grp_AES_cipher_fu_3942_p_din214;
output  [7:0] grp_AES_cipher_fu_3942_p_din215;
output  [7:0] grp_AES_cipher_fu_3942_p_din216;
output  [7:0] grp_AES_cipher_fu_3942_p_din217;
output  [7:0] grp_AES_cipher_fu_3942_p_din218;
output  [7:0] grp_AES_cipher_fu_3942_p_din219;
output  [7:0] grp_AES_cipher_fu_3942_p_din220;
output  [7:0] grp_AES_cipher_fu_3942_p_din221;
output  [7:0] grp_AES_cipher_fu_3942_p_din222;
output  [7:0] grp_AES_cipher_fu_3942_p_din223;
output  [7:0] grp_AES_cipher_fu_3942_p_din224;
output  [7:0] grp_AES_cipher_fu_3942_p_din225;
output  [7:0] grp_AES_cipher_fu_3942_p_din226;
output  [7:0] grp_AES_cipher_fu_3942_p_din227;
output  [7:0] grp_AES_cipher_fu_3942_p_din228;
output  [7:0] grp_AES_cipher_fu_3942_p_din229;
output  [7:0] grp_AES_cipher_fu_3942_p_din230;
output  [7:0] grp_AES_cipher_fu_3942_p_din231;
output  [7:0] grp_AES_cipher_fu_3942_p_din232;
output  [7:0] grp_AES_cipher_fu_3942_p_din233;
output  [7:0] grp_AES_cipher_fu_3942_p_din234;
output  [7:0] grp_AES_cipher_fu_3942_p_din235;
output  [7:0] grp_AES_cipher_fu_3942_p_din236;
output  [7:0] grp_AES_cipher_fu_3942_p_din237;
output  [7:0] grp_AES_cipher_fu_3942_p_din238;
output  [7:0] grp_AES_cipher_fu_3942_p_din239;
output  [7:0] grp_AES_cipher_fu_3942_p_din240;
output  [7:0] grp_AES_cipher_fu_3942_p_din241;
input  [127:0] grp_AES_cipher_fu_3942_p_dout0;
output   grp_AES_cipher_fu_3942_p_ce;
output   grp_AES_cipher_fu_3942_p_start;
input   grp_AES_cipher_fu_3942_p_ready;
input   grp_AES_cipher_fu_3942_p_done;
input   grp_AES_cipher_fu_3942_p_idle;

reg ap_idle;
reg CB_V_ce0;
reg enc_CB_V_ce0;
reg enc_CB_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1027_fu_2259_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln1027_3_fu_2271_p1;
reg   [63:0] zext_ln1027_3_reg_3492;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter1_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter2_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter3_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter4_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter5_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter6_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter7_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter8_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter9_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter10_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter11_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter12_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter13_reg;
reg   [63:0] zext_ln1027_3_reg_3492_pp0_iter14_reg;
wire    grp_AES_cipher_fu_1998_ap_ready;
reg    grp_AES_cipher_fu_1998_ap_start_reg;
wire    ap_block_pp0_stage0;
reg   [9:0] i_fu_522;
wire   [9:0] add_ln915_fu_2265_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_8;
wire   [57:0] zext_ln1027_fu_2255_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 grp_AES_cipher_fu_1998_ap_start_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

GCM_AE_HW_1x8_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AES_cipher_fu_1998_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_AES_cipher_fu_1998_ap_start_reg <= 1'b1;
        end else if ((grp_AES_cipher_fu_1998_ap_ready == 1'b1)) begin
            grp_AES_cipher_fu_1998_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1027_fu_2259_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_522 <= add_ln915_fu_2265_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_522 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        zext_ln1027_3_reg_3492_pp0_iter10_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter9_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter11_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter10_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter12_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter11_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter13_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter12_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter14_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter13_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter2_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter1_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter3_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter2_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter4_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter3_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter5_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter4_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter6_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter5_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter7_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter6_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter8_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter7_reg[9 : 0];
        zext_ln1027_3_reg_3492_pp0_iter9_reg[9 : 0] <= zext_ln1027_3_reg_3492_pp0_iter8_reg[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        zext_ln1027_3_reg_3492_pp0_iter1_reg[9 : 0] <= zext_ln1027_3_reg_3492[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_2259_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln1027_3_reg_3492[9 : 0] <= zext_ln1027_3_fu_2271_p1[9 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        CB_V_ce0 = 1'b1;
    end else begin
        CB_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_2259_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_8 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_8 = i_fu_522;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        enc_CB_V_ce0 = 1'b1;
    end else begin
        enc_CB_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        enc_CB_V_we0 = 1'b1;
    end else begin
        enc_CB_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CB_V_address0 = zext_ln1027_3_fu_2271_p1;

assign add_ln915_fu_2265_p2 = (ap_sig_allocacmp_i_8 + 10'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign enc_CB_V_address0 = zext_ln1027_3_reg_3492_pp0_iter14_reg;

assign enc_CB_V_d0 = grp_AES_cipher_fu_3942_p_dout0;

assign grp_AES_cipher_fu_1998_ap_ready = grp_AES_cipher_fu_3942_p_ready;

assign grp_AES_cipher_fu_3942_p_ce = 1'b1;

assign grp_AES_cipher_fu_3942_p_din1 = CB_V_q0;

assign grp_AES_cipher_fu_3942_p_din10 = p_read8;

assign grp_AES_cipher_fu_3942_p_din100 = p_read98;

assign grp_AES_cipher_fu_3942_p_din101 = p_read99;

assign grp_AES_cipher_fu_3942_p_din102 = p_read100;

assign grp_AES_cipher_fu_3942_p_din103 = p_read101;

assign grp_AES_cipher_fu_3942_p_din104 = p_read102;

assign grp_AES_cipher_fu_3942_p_din105 = p_read103;

assign grp_AES_cipher_fu_3942_p_din106 = p_read104;

assign grp_AES_cipher_fu_3942_p_din107 = p_read105;

assign grp_AES_cipher_fu_3942_p_din108 = p_read106;

assign grp_AES_cipher_fu_3942_p_din109 = p_read107;

assign grp_AES_cipher_fu_3942_p_din11 = p_read9;

assign grp_AES_cipher_fu_3942_p_din110 = p_read108;

assign grp_AES_cipher_fu_3942_p_din111 = p_read109;

assign grp_AES_cipher_fu_3942_p_din112 = p_read110;

assign grp_AES_cipher_fu_3942_p_din113 = p_read111;

assign grp_AES_cipher_fu_3942_p_din114 = p_read112;

assign grp_AES_cipher_fu_3942_p_din115 = p_read113;

assign grp_AES_cipher_fu_3942_p_din116 = p_read114;

assign grp_AES_cipher_fu_3942_p_din117 = p_read115;

assign grp_AES_cipher_fu_3942_p_din118 = p_read116;

assign grp_AES_cipher_fu_3942_p_din119 = p_read117;

assign grp_AES_cipher_fu_3942_p_din12 = p_read10;

assign grp_AES_cipher_fu_3942_p_din120 = p_read118;

assign grp_AES_cipher_fu_3942_p_din121 = p_read119;

assign grp_AES_cipher_fu_3942_p_din122 = p_read120;

assign grp_AES_cipher_fu_3942_p_din123 = p_read121;

assign grp_AES_cipher_fu_3942_p_din124 = p_read122;

assign grp_AES_cipher_fu_3942_p_din125 = p_read123;

assign grp_AES_cipher_fu_3942_p_din126 = p_read124;

assign grp_AES_cipher_fu_3942_p_din127 = p_read125;

assign grp_AES_cipher_fu_3942_p_din128 = p_read126;

assign grp_AES_cipher_fu_3942_p_din129 = p_read127;

assign grp_AES_cipher_fu_3942_p_din13 = p_read11;

assign grp_AES_cipher_fu_3942_p_din130 = p_read128;

assign grp_AES_cipher_fu_3942_p_din131 = p_read129;

assign grp_AES_cipher_fu_3942_p_din132 = p_read130;

assign grp_AES_cipher_fu_3942_p_din133 = p_read131;

assign grp_AES_cipher_fu_3942_p_din134 = p_read132;

assign grp_AES_cipher_fu_3942_p_din135 = p_read133;

assign grp_AES_cipher_fu_3942_p_din136 = p_read134;

assign grp_AES_cipher_fu_3942_p_din137 = p_read135;

assign grp_AES_cipher_fu_3942_p_din138 = p_read136;

assign grp_AES_cipher_fu_3942_p_din139 = p_read137;

assign grp_AES_cipher_fu_3942_p_din14 = p_read12;

assign grp_AES_cipher_fu_3942_p_din140 = p_read138;

assign grp_AES_cipher_fu_3942_p_din141 = p_read139;

assign grp_AES_cipher_fu_3942_p_din142 = p_read140;

assign grp_AES_cipher_fu_3942_p_din143 = p_read141;

assign grp_AES_cipher_fu_3942_p_din144 = p_read142;

assign grp_AES_cipher_fu_3942_p_din145 = p_read143;

assign grp_AES_cipher_fu_3942_p_din146 = p_read144;

assign grp_AES_cipher_fu_3942_p_din147 = p_read145;

assign grp_AES_cipher_fu_3942_p_din148 = p_read146;

assign grp_AES_cipher_fu_3942_p_din149 = p_read147;

assign grp_AES_cipher_fu_3942_p_din15 = p_read13;

assign grp_AES_cipher_fu_3942_p_din150 = p_read148;

assign grp_AES_cipher_fu_3942_p_din151 = p_read149;

assign grp_AES_cipher_fu_3942_p_din152 = p_read150;

assign grp_AES_cipher_fu_3942_p_din153 = p_read151;

assign grp_AES_cipher_fu_3942_p_din154 = p_read152;

assign grp_AES_cipher_fu_3942_p_din155 = p_read153;

assign grp_AES_cipher_fu_3942_p_din156 = p_read154;

assign grp_AES_cipher_fu_3942_p_din157 = p_read155;

assign grp_AES_cipher_fu_3942_p_din158 = p_read156;

assign grp_AES_cipher_fu_3942_p_din159 = p_read157;

assign grp_AES_cipher_fu_3942_p_din16 = p_read14;

assign grp_AES_cipher_fu_3942_p_din160 = p_read158;

assign grp_AES_cipher_fu_3942_p_din161 = p_read159;

assign grp_AES_cipher_fu_3942_p_din162 = p_read160;

assign grp_AES_cipher_fu_3942_p_din163 = p_read161;

assign grp_AES_cipher_fu_3942_p_din164 = p_read162;

assign grp_AES_cipher_fu_3942_p_din165 = p_read163;

assign grp_AES_cipher_fu_3942_p_din166 = p_read164;

assign grp_AES_cipher_fu_3942_p_din167 = p_read165;

assign grp_AES_cipher_fu_3942_p_din168 = p_read166;

assign grp_AES_cipher_fu_3942_p_din169 = p_read167;

assign grp_AES_cipher_fu_3942_p_din17 = p_read15;

assign grp_AES_cipher_fu_3942_p_din170 = p_read168;

assign grp_AES_cipher_fu_3942_p_din171 = p_read169;

assign grp_AES_cipher_fu_3942_p_din172 = p_read170;

assign grp_AES_cipher_fu_3942_p_din173 = p_read171;

assign grp_AES_cipher_fu_3942_p_din174 = p_read172;

assign grp_AES_cipher_fu_3942_p_din175 = p_read173;

assign grp_AES_cipher_fu_3942_p_din176 = p_read174;

assign grp_AES_cipher_fu_3942_p_din177 = p_read175;

assign grp_AES_cipher_fu_3942_p_din178 = p_read176;

assign grp_AES_cipher_fu_3942_p_din179 = p_read177;

assign grp_AES_cipher_fu_3942_p_din18 = p_read16;

assign grp_AES_cipher_fu_3942_p_din180 = p_read178;

assign grp_AES_cipher_fu_3942_p_din181 = p_read179;

assign grp_AES_cipher_fu_3942_p_din182 = p_read180;

assign grp_AES_cipher_fu_3942_p_din183 = p_read181;

assign grp_AES_cipher_fu_3942_p_din184 = p_read182;

assign grp_AES_cipher_fu_3942_p_din185 = p_read183;

assign grp_AES_cipher_fu_3942_p_din186 = p_read184;

assign grp_AES_cipher_fu_3942_p_din187 = p_read185;

assign grp_AES_cipher_fu_3942_p_din188 = p_read186;

assign grp_AES_cipher_fu_3942_p_din189 = p_read187;

assign grp_AES_cipher_fu_3942_p_din19 = p_read17;

assign grp_AES_cipher_fu_3942_p_din190 = p_read188;

assign grp_AES_cipher_fu_3942_p_din191 = p_read189;

assign grp_AES_cipher_fu_3942_p_din192 = p_read190;

assign grp_AES_cipher_fu_3942_p_din193 = p_read191;

assign grp_AES_cipher_fu_3942_p_din194 = p_read192;

assign grp_AES_cipher_fu_3942_p_din195 = p_read193;

assign grp_AES_cipher_fu_3942_p_din196 = p_read194;

assign grp_AES_cipher_fu_3942_p_din197 = p_read195;

assign grp_AES_cipher_fu_3942_p_din198 = p_read196;

assign grp_AES_cipher_fu_3942_p_din199 = p_read197;

assign grp_AES_cipher_fu_3942_p_din2 = p_read;

assign grp_AES_cipher_fu_3942_p_din20 = p_read18;

assign grp_AES_cipher_fu_3942_p_din200 = p_read198;

assign grp_AES_cipher_fu_3942_p_din201 = p_read199;

assign grp_AES_cipher_fu_3942_p_din202 = p_read200;

assign grp_AES_cipher_fu_3942_p_din203 = p_read201;

assign grp_AES_cipher_fu_3942_p_din204 = p_read202;

assign grp_AES_cipher_fu_3942_p_din205 = p_read203;

assign grp_AES_cipher_fu_3942_p_din206 = p_read204;

assign grp_AES_cipher_fu_3942_p_din207 = p_read205;

assign grp_AES_cipher_fu_3942_p_din208 = p_read206;

assign grp_AES_cipher_fu_3942_p_din209 = p_read207;

assign grp_AES_cipher_fu_3942_p_din21 = p_read19;

assign grp_AES_cipher_fu_3942_p_din210 = p_read208;

assign grp_AES_cipher_fu_3942_p_din211 = p_read209;

assign grp_AES_cipher_fu_3942_p_din212 = p_read210;

assign grp_AES_cipher_fu_3942_p_din213 = p_read211;

assign grp_AES_cipher_fu_3942_p_din214 = p_read212;

assign grp_AES_cipher_fu_3942_p_din215 = p_read213;

assign grp_AES_cipher_fu_3942_p_din216 = p_read214;

assign grp_AES_cipher_fu_3942_p_din217 = p_read215;

assign grp_AES_cipher_fu_3942_p_din218 = p_read216;

assign grp_AES_cipher_fu_3942_p_din219 = p_read217;

assign grp_AES_cipher_fu_3942_p_din22 = p_read20;

assign grp_AES_cipher_fu_3942_p_din220 = p_read218;

assign grp_AES_cipher_fu_3942_p_din221 = p_read219;

assign grp_AES_cipher_fu_3942_p_din222 = p_read220;

assign grp_AES_cipher_fu_3942_p_din223 = p_read221;

assign grp_AES_cipher_fu_3942_p_din224 = p_read222;

assign grp_AES_cipher_fu_3942_p_din225 = p_read223;

assign grp_AES_cipher_fu_3942_p_din226 = p_read224;

assign grp_AES_cipher_fu_3942_p_din227 = p_read225;

assign grp_AES_cipher_fu_3942_p_din228 = p_read226;

assign grp_AES_cipher_fu_3942_p_din229 = p_read227;

assign grp_AES_cipher_fu_3942_p_din23 = p_read21;

assign grp_AES_cipher_fu_3942_p_din230 = p_read228;

assign grp_AES_cipher_fu_3942_p_din231 = p_read229;

assign grp_AES_cipher_fu_3942_p_din232 = p_read230;

assign grp_AES_cipher_fu_3942_p_din233 = p_read231;

assign grp_AES_cipher_fu_3942_p_din234 = p_read232;

assign grp_AES_cipher_fu_3942_p_din235 = p_read233;

assign grp_AES_cipher_fu_3942_p_din236 = p_read234;

assign grp_AES_cipher_fu_3942_p_din237 = p_read235;

assign grp_AES_cipher_fu_3942_p_din238 = p_read236;

assign grp_AES_cipher_fu_3942_p_din239 = p_read237;

assign grp_AES_cipher_fu_3942_p_din24 = p_read22;

assign grp_AES_cipher_fu_3942_p_din240 = p_read238;

assign grp_AES_cipher_fu_3942_p_din241 = p_read239;

assign grp_AES_cipher_fu_3942_p_din25 = p_read23;

assign grp_AES_cipher_fu_3942_p_din26 = p_read24;

assign grp_AES_cipher_fu_3942_p_din27 = p_read25;

assign grp_AES_cipher_fu_3942_p_din28 = p_read26;

assign grp_AES_cipher_fu_3942_p_din29 = p_read27;

assign grp_AES_cipher_fu_3942_p_din3 = p_read1;

assign grp_AES_cipher_fu_3942_p_din30 = p_read28;

assign grp_AES_cipher_fu_3942_p_din31 = p_read29;

assign grp_AES_cipher_fu_3942_p_din32 = p_read30;

assign grp_AES_cipher_fu_3942_p_din33 = p_read31;

assign grp_AES_cipher_fu_3942_p_din34 = p_read32;

assign grp_AES_cipher_fu_3942_p_din35 = p_read33;

assign grp_AES_cipher_fu_3942_p_din36 = p_read34;

assign grp_AES_cipher_fu_3942_p_din37 = p_read35;

assign grp_AES_cipher_fu_3942_p_din38 = p_read36;

assign grp_AES_cipher_fu_3942_p_din39 = p_read37;

assign grp_AES_cipher_fu_3942_p_din4 = p_read2;

assign grp_AES_cipher_fu_3942_p_din40 = p_read38;

assign grp_AES_cipher_fu_3942_p_din41 = p_read39;

assign grp_AES_cipher_fu_3942_p_din42 = p_read40;

assign grp_AES_cipher_fu_3942_p_din43 = p_read41;

assign grp_AES_cipher_fu_3942_p_din44 = p_read42;

assign grp_AES_cipher_fu_3942_p_din45 = p_read43;

assign grp_AES_cipher_fu_3942_p_din46 = p_read44;

assign grp_AES_cipher_fu_3942_p_din47 = p_read45;

assign grp_AES_cipher_fu_3942_p_din48 = p_read46;

assign grp_AES_cipher_fu_3942_p_din49 = p_read47;

assign grp_AES_cipher_fu_3942_p_din5 = p_read3;

assign grp_AES_cipher_fu_3942_p_din50 = p_read48;

assign grp_AES_cipher_fu_3942_p_din51 = p_read49;

assign grp_AES_cipher_fu_3942_p_din52 = p_read50;

assign grp_AES_cipher_fu_3942_p_din53 = p_read51;

assign grp_AES_cipher_fu_3942_p_din54 = p_read52;

assign grp_AES_cipher_fu_3942_p_din55 = p_read53;

assign grp_AES_cipher_fu_3942_p_din56 = p_read54;

assign grp_AES_cipher_fu_3942_p_din57 = p_read55;

assign grp_AES_cipher_fu_3942_p_din58 = p_read56;

assign grp_AES_cipher_fu_3942_p_din59 = p_read57;

assign grp_AES_cipher_fu_3942_p_din6 = p_read4;

assign grp_AES_cipher_fu_3942_p_din60 = p_read58;

assign grp_AES_cipher_fu_3942_p_din61 = p_read59;

assign grp_AES_cipher_fu_3942_p_din62 = p_read60;

assign grp_AES_cipher_fu_3942_p_din63 = p_read61;

assign grp_AES_cipher_fu_3942_p_din64 = p_read62;

assign grp_AES_cipher_fu_3942_p_din65 = p_read63;

assign grp_AES_cipher_fu_3942_p_din66 = p_read64;

assign grp_AES_cipher_fu_3942_p_din67 = p_read65;

assign grp_AES_cipher_fu_3942_p_din68 = p_read66;

assign grp_AES_cipher_fu_3942_p_din69 = p_read67;

assign grp_AES_cipher_fu_3942_p_din7 = p_read5;

assign grp_AES_cipher_fu_3942_p_din70 = p_read68;

assign grp_AES_cipher_fu_3942_p_din71 = p_read69;

assign grp_AES_cipher_fu_3942_p_din72 = p_read70;

assign grp_AES_cipher_fu_3942_p_din73 = p_read71;

assign grp_AES_cipher_fu_3942_p_din74 = p_read72;

assign grp_AES_cipher_fu_3942_p_din75 = p_read73;

assign grp_AES_cipher_fu_3942_p_din76 = p_read74;

assign grp_AES_cipher_fu_3942_p_din77 = p_read75;

assign grp_AES_cipher_fu_3942_p_din78 = p_read76;

assign grp_AES_cipher_fu_3942_p_din79 = p_read77;

assign grp_AES_cipher_fu_3942_p_din8 = p_read6;

assign grp_AES_cipher_fu_3942_p_din80 = p_read78;

assign grp_AES_cipher_fu_3942_p_din81 = p_read79;

assign grp_AES_cipher_fu_3942_p_din82 = p_read80;

assign grp_AES_cipher_fu_3942_p_din83 = p_read81;

assign grp_AES_cipher_fu_3942_p_din84 = p_read82;

assign grp_AES_cipher_fu_3942_p_din85 = p_read83;

assign grp_AES_cipher_fu_3942_p_din86 = p_read84;

assign grp_AES_cipher_fu_3942_p_din87 = p_read85;

assign grp_AES_cipher_fu_3942_p_din88 = p_read86;

assign grp_AES_cipher_fu_3942_p_din89 = p_read87;

assign grp_AES_cipher_fu_3942_p_din9 = p_read7;

assign grp_AES_cipher_fu_3942_p_din90 = p_read88;

assign grp_AES_cipher_fu_3942_p_din91 = p_read89;

assign grp_AES_cipher_fu_3942_p_din92 = p_read90;

assign grp_AES_cipher_fu_3942_p_din93 = p_read91;

assign grp_AES_cipher_fu_3942_p_din94 = p_read92;

assign grp_AES_cipher_fu_3942_p_din95 = p_read93;

assign grp_AES_cipher_fu_3942_p_din96 = p_read94;

assign grp_AES_cipher_fu_3942_p_din97 = p_read95;

assign grp_AES_cipher_fu_3942_p_din98 = p_read96;

assign grp_AES_cipher_fu_3942_p_din99 = p_read97;

assign grp_AES_cipher_fu_3942_p_start = grp_AES_cipher_fu_1998_ap_start_reg;

assign icmp_ln1027_fu_2259_p2 = ((zext_ln1027_fu_2255_p1 == CB_blocks_V_1) ? 1'b1 : 1'b0);

assign zext_ln1027_3_fu_2271_p1 = ap_sig_allocacmp_i_8;

assign zext_ln1027_fu_2255_p1 = ap_sig_allocacmp_i_8;

always @ (posedge ap_clk) begin
    zext_ln1027_3_reg_3492[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter1_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter2_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter3_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter4_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter5_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter6_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter7_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter8_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter9_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter10_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter11_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter12_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter13_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln1027_3_reg_3492_pp0_iter14_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //GCM_AE_HW_1x8_GCTR_Pipeline_enc_CB_store
