-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_ad_reading is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_TVALID : IN STD_LOGIC;
    tmp_data_V_4 : IN STD_LOGIC_VECTOR (511 downto 0);
    trunc_ln1 : IN STD_LOGIC_VECTOR (120 downto 0);
    input_r_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    input_r_TREADY : OUT STD_LOGIC;
    input_r_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    input_r_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    input_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    temp_V_13_out : OUT STD_LOGIC_VECTOR (511 downto 0);
    temp_V_13_out_ap_vld : OUT STD_LOGIC;
    hw_AD_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    hw_AD_ce0 : OUT STD_LOGIC;
    hw_AD_we0 : OUT STD_LOGIC;
    hw_AD_d0 : OUT STD_LOGIC_VECTOR (127 downto 0);
    grp_convert_endian_128_hw_fu_331_p_din1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    grp_convert_endian_128_hw_fu_331_p_dout0 : IN STD_LOGIC_VECTOR (127 downto 0);
    grp_convert_endian_128_hw_fu_331_p_ready : IN STD_LOGIC );
end;


architecture behav of Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_ad_reading is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000000";
    constant ap_const_lv121_0 : STD_LOGIC_VECTOR (120 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv121_1 : STD_LOGIC_VECTOR (120 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv23_1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln383_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln387_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op30_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_convert_endian_128_hw_fu_144_val_r : STD_LOGIC_VECTOR (127 downto 0);
    signal val_5_fu_208_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal inp_V_fu_249_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln395_fu_217_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln388_fu_258_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal pos_fu_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal pos_6_fu_263_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_84 : STD_LOGIC_VECTOR (120 downto 0);
    signal i_6_fu_176_p2 : STD_LOGIC_VECTOR (120 downto 0);
    signal p_Val2_s_fu_88 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln387_fu_182_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_188_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln395_fu_213_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln628_fu_235_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln628_fu_239_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal lshr_ln628_fu_243_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal trunc_ln388_fu_254_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_248 : BOOLEAN;
    signal ap_condition_252 : BOOLEAN;
    signal ap_condition_255 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component Rocca_S_hw_v2_convert_endian_128_hw IS
    port (
        ap_ready : OUT STD_LOGIC;
        val_r : IN STD_LOGIC_VECTOR (127 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component Rocca_S_hw_v2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Rocca_S_hw_v2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_84 <= ap_const_lv121_0;
                elsif (((icmp_ln383_fu_171_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_84 <= i_6_fu_176_p2;
                end if;
            end if; 
        end if;
    end process;

    p_Val2_s_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    p_Val2_s_fu_88 <= tmp_data_V_4;
                elsif ((ap_const_boolean_1 = ap_condition_252)) then 
                    p_Val2_s_fu_88 <= input_r_TDATA;
                end if;
            end if; 
        end if;
    end process;

    pos_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    pos_fu_80 <= ap_const_lv32_200;
                elsif ((ap_const_boolean_1 = ap_condition_255)) then 
                    pos_fu_80 <= pos_6_fu_263_p2;
                elsif ((ap_const_boolean_1 = ap_condition_252)) then 
                    pos_fu_80 <= ap_const_lv32_80;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln387_fu_182_p2 <= std_logic_vector(unsigned(pos_fu_80) + unsigned(ap_const_lv32_7F));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, input_r_TVALID, ap_predicate_op30_read_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (input_r_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, input_r_TVALID, ap_predicate_op30_read_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (input_r_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, input_r_TVALID, ap_predicate_op30_read_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (input_r_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(input_r_TVALID, ap_predicate_op30_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op30_read_state2 = ap_const_boolean_1) and (input_r_TVALID = ap_const_logic_0));
    end process;


    ap_condition_248_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln383_fu_171_p2, ap_block_pp0_stage0)
    begin
                ap_condition_248 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln383_fu_171_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_252_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln383_fu_171_p2, icmp_ln387_fu_198_p2)
    begin
                ap_condition_252 <= ((icmp_ln387_fu_198_p2 = ap_const_lv1_0) and (icmp_ln383_fu_171_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_255_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln383_fu_171_p2, icmp_ln387_fu_198_p2)
    begin
                ap_condition_255 <= ((icmp_ln387_fu_198_p2 = ap_const_lv1_1) and (icmp_ln383_fu_171_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln383_fu_171_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln383_fu_171_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_predicate_op30_read_state2_assign_proc : process(icmp_ln383_fu_171_p2, icmp_ln387_fu_198_p2)
    begin
                ap_predicate_op30_read_state2 <= ((icmp_ln387_fu_198_p2 = ap_const_lv1_0) and (icmp_ln383_fu_171_p2 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    grp_convert_endian_128_hw_fu_144_val_r_assign_proc : process(icmp_ln387_fu_198_p2, val_5_fu_208_p1, inp_V_fu_249_p1, ap_condition_248)
    begin
        if ((ap_const_boolean_1 = ap_condition_248)) then
            if ((icmp_ln387_fu_198_p2 = ap_const_lv1_1)) then 
                grp_convert_endian_128_hw_fu_144_val_r <= inp_V_fu_249_p1;
            elsif ((icmp_ln387_fu_198_p2 = ap_const_lv1_0)) then 
                grp_convert_endian_128_hw_fu_144_val_r <= val_5_fu_208_p1;
            else 
                grp_convert_endian_128_hw_fu_144_val_r <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_convert_endian_128_hw_fu_144_val_r <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_convert_endian_128_hw_fu_331_p_din1 <= grp_convert_endian_128_hw_fu_144_val_r;

    hw_AD_address0_assign_proc : process(icmp_ln387_fu_198_p2, zext_ln395_fu_217_p1, zext_ln388_fu_258_p1, ap_condition_248)
    begin
        if ((ap_const_boolean_1 = ap_condition_248)) then
            if ((icmp_ln387_fu_198_p2 = ap_const_lv1_1)) then 
                hw_AD_address0 <= zext_ln388_fu_258_p1(6 - 1 downto 0);
            elsif ((icmp_ln387_fu_198_p2 = ap_const_lv1_0)) then 
                hw_AD_address0 <= zext_ln395_fu_217_p1(6 - 1 downto 0);
            else 
                hw_AD_address0 <= "XXXXXX";
            end if;
        else 
            hw_AD_address0 <= "XXXXXX";
        end if; 
    end process;


    hw_AD_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln383_fu_171_p2, icmp_ln387_fu_198_p2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln387_fu_198_p2 = ap_const_lv1_1) and (icmp_ln383_fu_171_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln387_fu_198_p2 = ap_const_lv1_0) and (icmp_ln383_fu_171_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hw_AD_ce0 <= ap_const_logic_1;
        else 
            hw_AD_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    hw_AD_d0 <= grp_convert_endian_128_hw_fu_331_p_dout0;

    hw_AD_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln383_fu_171_p2, icmp_ln387_fu_198_p2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln387_fu_198_p2 = ap_const_lv1_1) and (icmp_ln383_fu_171_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln387_fu_198_p2 = ap_const_lv1_0) and (icmp_ln383_fu_171_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hw_AD_we0 <= ap_const_logic_1;
        else 
            hw_AD_we0 <= ap_const_logic_0;
        end if; 
    end process;

    i_6_fu_176_p2 <= std_logic_vector(unsigned(i_fu_84) + unsigned(ap_const_lv121_1));
    icmp_ln383_fu_171_p2 <= "1" when (i_fu_84 = trunc_ln1) else "0";
    icmp_ln387_fu_198_p2 <= "1" when (signed(tmp_fu_188_p4) < signed(ap_const_lv23_1)) else "0";
    inp_V_fu_249_p1 <= lshr_ln628_fu_243_p2(128 - 1 downto 0);

    input_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, input_r_TVALID, ap_predicate_op30_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op30_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_TDATA_blk_n <= input_r_TVALID;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_r_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op30_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op30_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_TREADY <= ap_const_logic_1;
        else 
            input_r_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln628_fu_243_p2 <= std_logic_vector(shift_right(unsigned(p_Val2_s_fu_88),to_integer(unsigned('0' & zext_ln628_fu_239_p1(31-1 downto 0)))));
    pos_6_fu_263_p2 <= std_logic_vector(unsigned(pos_fu_80) + unsigned(ap_const_lv32_80));
    temp_V_13_out <= p_Val2_s_fu_88;

    temp_V_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln383_fu_171_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln383_fu_171_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            temp_V_13_out_ap_vld <= ap_const_logic_1;
        else 
            temp_V_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_188_p4 <= add_ln387_fu_182_p2(31 downto 9);
    trunc_ln388_fu_254_p1 <= i_fu_84(6 - 1 downto 0);
    trunc_ln395_fu_213_p1 <= i_fu_84(6 - 1 downto 0);
    trunc_ln628_fu_235_p1 <= pos_fu_80(9 - 1 downto 0);
    val_5_fu_208_p1 <= input_r_TDATA(128 - 1 downto 0);
    zext_ln388_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln388_fu_254_p1),64));
    zext_ln395_fu_217_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln395_fu_213_p1),64));
    zext_ln628_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln628_fu_235_p1),512));
end behav;
