// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_VITIS_LOOP_311_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        val_1,
        trunc_ln,
        val_3,
        trunc_ln322_1,
        xor_i_i719_phi_out,
        xor_i_i719_phi_out_ap_vld,
        call_i_i720_phi_out,
        call_i_i720_phi_out_ap_vld,
        call2_i_i721_phi_out,
        call2_i_i721_phi_out_ap_vld,
        call4_i_i722_phi_out,
        call4_i_i722_phi_out_ap_vld,
        call6_i_i723_phi_out,
        call6_i_i723_phi_out_ap_vld,
        call8_i_i724_phi_out,
        call8_i_i724_phi_out_ap_vld,
        call10_i_i725_phi_out,
        call10_i_i725_phi_out_ap_vld,
        hw_S_6_i,
        hw_S_6_o,
        hw_S_6_o_ap_vld,
        hw_S_1_i,
        hw_S_1_o,
        hw_S_1_o_ap_vld,
        hw_S_0_i,
        hw_S_0_o,
        hw_S_0_o_ap_vld,
        hw_S_2_i,
        hw_S_2_o,
        hw_S_2_o_ap_vld,
        hw_S_3_i,
        hw_S_3_o,
        hw_S_3_o_ap_vld,
        hw_S_4_i,
        hw_S_4_o,
        hw_S_4_o_ap_vld,
        hw_S_5_i,
        hw_S_5_o,
        hw_S_5_o_ap_vld,
        grp_hw_AES_fu_955_p_din1,
        grp_hw_AES_fu_955_p_din2,
        grp_hw_AES_fu_955_p_dout0,
        grp_hw_AES_fu_955_p_ready,
        grp_hw_AES_fu_960_p_din1,
        grp_hw_AES_fu_960_p_din2,
        grp_hw_AES_fu_960_p_dout0,
        grp_hw_AES_fu_960_p_ready,
        tmp_13_hw_AES_fu_965_p_din1,
        tmp_13_hw_AES_fu_965_p_din2,
        tmp_13_hw_AES_fu_965_p_dout0,
        tmp_13_hw_AES_fu_965_p_ready,
        tmp_s_hw_AES_fu_970_p_din1,
        tmp_s_hw_AES_fu_970_p_din2,
        tmp_s_hw_AES_fu_970_p_dout0,
        tmp_s_hw_AES_fu_970_p_ready
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] val_1;
input  [7:0] trunc_ln;
input  [127:0] val_3;
input  [7:0] trunc_ln322_1;
output  [127:0] xor_i_i719_phi_out;
output   xor_i_i719_phi_out_ap_vld;
output  [127:0] call_i_i720_phi_out;
output   call_i_i720_phi_out_ap_vld;
output  [127:0] call2_i_i721_phi_out;
output   call2_i_i721_phi_out_ap_vld;
output  [127:0] call4_i_i722_phi_out;
output   call4_i_i722_phi_out_ap_vld;
output  [127:0] call6_i_i723_phi_out;
output   call6_i_i723_phi_out_ap_vld;
output  [127:0] call8_i_i724_phi_out;
output   call8_i_i724_phi_out_ap_vld;
output  [127:0] call10_i_i725_phi_out;
output   call10_i_i725_phi_out_ap_vld;
input  [127:0] hw_S_6_i;
output  [127:0] hw_S_6_o;
output   hw_S_6_o_ap_vld;
input  [127:0] hw_S_1_i;
output  [127:0] hw_S_1_o;
output   hw_S_1_o_ap_vld;
input  [127:0] hw_S_0_i;
output  [127:0] hw_S_0_o;
output   hw_S_0_o_ap_vld;
input  [127:0] hw_S_2_i;
output  [127:0] hw_S_2_o;
output   hw_S_2_o_ap_vld;
input  [127:0] hw_S_3_i;
output  [127:0] hw_S_3_o;
output   hw_S_3_o_ap_vld;
input  [127:0] hw_S_4_i;
output  [127:0] hw_S_4_o;
output   hw_S_4_o_ap_vld;
input  [127:0] hw_S_5_i;
output  [127:0] hw_S_5_o;
output   hw_S_5_o_ap_vld;
output  [127:0] grp_hw_AES_fu_955_p_din1;
output  [127:0] grp_hw_AES_fu_955_p_din2;
input  [127:0] grp_hw_AES_fu_955_p_dout0;
input   grp_hw_AES_fu_955_p_ready;
output  [127:0] grp_hw_AES_fu_960_p_din1;
output  [127:0] grp_hw_AES_fu_960_p_din2;
input  [127:0] grp_hw_AES_fu_960_p_dout0;
input   grp_hw_AES_fu_960_p_ready;
output  [127:0] tmp_13_hw_AES_fu_965_p_din1;
output  [127:0] tmp_13_hw_AES_fu_965_p_din2;
input  [127:0] tmp_13_hw_AES_fu_965_p_dout0;
input   tmp_13_hw_AES_fu_965_p_ready;
output  [127:0] tmp_s_hw_AES_fu_970_p_din1;
output  [127:0] tmp_s_hw_AES_fu_970_p_din2;
input  [127:0] tmp_s_hw_AES_fu_970_p_dout0;
input   tmp_s_hw_AES_fu_970_p_ready;

reg ap_idle;
reg xor_i_i719_phi_out_ap_vld;
reg call_i_i720_phi_out_ap_vld;
reg call2_i_i721_phi_out_ap_vld;
reg call4_i_i722_phi_out_ap_vld;
reg call6_i_i723_phi_out_ap_vld;
reg call8_i_i724_phi_out_ap_vld;
reg call10_i_i725_phi_out_ap_vld;
reg[127:0] hw_S_6_o;
reg hw_S_6_o_ap_vld;
reg[127:0] hw_S_1_o;
reg hw_S_1_o_ap_vld;
reg[127:0] hw_S_0_o;
reg hw_S_0_o_ap_vld;
reg[127:0] hw_S_2_o;
reg hw_S_2_o_ap_vld;
reg[127:0] hw_S_3_o;
reg hw_S_3_o_ap_vld;
reg[127:0] hw_S_4_o;
reg hw_S_4_o_ap_vld;
reg[127:0] hw_S_5_o;
reg hw_S_5_o_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln311_fu_375_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state2;
wire    ap_block_state2_pp0_stage1_iter0;
reg   [127:0] tmp_13_reg_356;
reg   [127:0] hw_S_3_load_reg_966;
reg   [127:0] grp_hw_AES_fu_243_state;
reg   [127:0] grp_hw_AES_fu_243_key;
reg   [127:0] grp_hw_AES_fu_246_state;
reg   [127:0] grp_hw_AES_fu_246_key;
wire   [127:0] out_fu_537_p17;
wire   [127:0] out_1_fu_724_p17;
wire   [127:0] xor_ln234_fu_771_p2;
reg   [127:0] call10_i_i725_phi_fu_138;
reg   [127:0] call8_i_i724_phi_fu_142;
reg   [127:0] call6_i_i723_phi_fu_146;
reg   [127:0] call4_i_i722_phi_fu_150;
reg   [127:0] call2_i_i721_phi_fu_154;
reg   [127:0] call_i_i720_phi_fu_158;
reg   [127:0] xor_i_i719_phi_fu_162;
reg   [4:0] i_fu_166;
wire   [4:0] i_8_fu_381_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_7;
wire   [7:0] num_1_i_fu_397_p4;
wire   [7:0] num_2_i_fu_417_p4;
wire   [7:0] num_3_i_fu_437_p4;
wire   [7:0] num_4_i_fu_457_p4;
wire   [7:0] num_5_i_fu_477_p4;
wire   [7:0] num_6_i_fu_497_p4;
wire   [7:0] num_7_i_fu_517_p4;
wire   [7:0] num_8_i_fu_527_p4;
wire   [7:0] num_9_i_fu_507_p4;
wire   [7:0] num_10_i_fu_487_p4;
wire   [7:0] num_11_i_fu_467_p4;
wire   [7:0] num_12_i_fu_447_p4;
wire   [7:0] num_13_i_fu_427_p4;
wire   [7:0] num_14_i_fu_407_p4;
wire   [7:0] num_i_fu_387_p4;
wire   [7:0] num_1_i3_fu_584_p4;
wire   [7:0] num_2_i5_fu_604_p4;
wire   [7:0] num_3_i7_fu_624_p4;
wire   [7:0] num_4_i9_fu_644_p4;
wire   [7:0] num_5_i1_fu_664_p4;
wire   [7:0] num_6_i1_fu_684_p4;
wire   [7:0] num_7_i1_fu_704_p4;
wire   [7:0] num_8_i1_fu_714_p4;
wire   [7:0] num_9_i1_fu_694_p4;
wire   [7:0] num_10_i1_fu_674_p4;
wire   [7:0] num_11_i1_fu_654_p4;
wire   [7:0] num_12_i8_fu_634_p4;
wire   [7:0] num_13_i6_fu_614_p4;
wire   [7:0] num_14_i4_fu_594_p4;
wire   [7:0] num_i2_fu_574_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

Rocca_S_hw_v2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln311_fu_375_p2 == 1'd0)) begin
            i_fu_166 <= i_8_fu_381_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_166 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        call10_i_i725_phi_fu_138 <= grp_hw_AES_fu_960_p_dout0;
        call8_i_i724_phi_fu_142 <= grp_hw_AES_fu_955_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        call2_i_i721_phi_fu_154 <= grp_hw_AES_fu_960_p_dout0;
        call4_i_i722_phi_fu_150 <= grp_hw_AES_fu_955_p_dout0;
        call6_i_i723_phi_fu_146 <= tmp_13_hw_AES_fu_965_p_dout0;
        call_i_i720_phi_fu_158 <= tmp_s_hw_AES_fu_970_p_dout0;
        hw_S_3_load_reg_966 <= hw_S_3_i;
        tmp_13_reg_356 <= tmp_13_hw_AES_fu_965_p_dout0;
        xor_i_i719_phi_fu_162 <= xor_ln234_fu_771_p2;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_7 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_7 = i_fu_166;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        call10_i_i725_phi_out_ap_vld = 1'b1;
    end else begin
        call10_i_i725_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        call2_i_i721_phi_out_ap_vld = 1'b1;
    end else begin
        call2_i_i721_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        call4_i_i722_phi_out_ap_vld = 1'b1;
    end else begin
        call4_i_i722_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        call6_i_i723_phi_out_ap_vld = 1'b1;
    end else begin
        call6_i_i723_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        call8_i_i724_phi_out_ap_vld = 1'b1;
    end else begin
        call8_i_i724_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        call_i_i720_phi_out_ap_vld = 1'b1;
    end else begin
        call_i_i720_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_hw_AES_fu_243_key = hw_S_3_load_reg_966;
    end else if (((icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_hw_AES_fu_243_key = hw_S_6_i;
    end else begin
        grp_hw_AES_fu_243_key = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_hw_AES_fu_243_state = hw_S_4_i;
    end else if (((icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_hw_AES_fu_243_state = hw_S_2_i;
    end else begin
        grp_hw_AES_fu_243_state = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_hw_AES_fu_246_key = hw_S_4_i;
    end else if (((icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_hw_AES_fu_246_key = hw_S_0_i;
    end else begin
        grp_hw_AES_fu_246_key = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_hw_AES_fu_246_state = hw_S_5_i;
    end else if (((icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_hw_AES_fu_246_state = hw_S_1_i;
    end else begin
        grp_hw_AES_fu_246_state = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_S_0_o = xor_ln234_fu_771_p2;
    end else begin
        hw_S_0_o = hw_S_0_i;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_S_0_o_ap_vld = 1'b1;
    end else begin
        hw_S_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_S_1_o = tmp_s_hw_AES_fu_970_p_dout0;
    end else begin
        hw_S_1_o = hw_S_1_i;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_S_1_o_ap_vld = 1'b1;
    end else begin
        hw_S_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_S_2_o = grp_hw_AES_fu_960_p_dout0;
    end else begin
        hw_S_2_o = hw_S_2_i;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_S_2_o_ap_vld = 1'b1;
    end else begin
        hw_S_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_S_3_o = grp_hw_AES_fu_955_p_dout0;
    end else begin
        hw_S_3_o = hw_S_3_i;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        hw_S_3_o_ap_vld = 1'b1;
    end else begin
        hw_S_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_S_4_o = tmp_13_reg_356;
    end else begin
        hw_S_4_o = hw_S_4_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_S_4_o_ap_vld = 1'b1;
    end else begin
        hw_S_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_S_5_o = grp_hw_AES_fu_955_p_dout0;
    end else begin
        hw_S_5_o = hw_S_5_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_S_5_o_ap_vld = 1'b1;
    end else begin
        hw_S_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_S_6_o = grp_hw_AES_fu_960_p_dout0;
    end else begin
        hw_S_6_o = hw_S_6_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hw_S_6_o_ap_vld = 1'b1;
    end else begin
        hw_S_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        xor_i_i719_phi_out_ap_vld = 1'b1;
    end else begin
        xor_i_i719_phi_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start_int == 1'b1) & (icmp_ln311_fu_375_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign call10_i_i725_phi_out = call10_i_i725_phi_fu_138;

assign call2_i_i721_phi_out = call2_i_i721_phi_fu_154;

assign call4_i_i722_phi_out = call4_i_i722_phi_fu_150;

assign call6_i_i723_phi_out = call6_i_i723_phi_fu_146;

assign call8_i_i724_phi_out = call8_i_i724_phi_fu_142;

assign call_i_i720_phi_out = call_i_i720_phi_fu_158;

assign grp_hw_AES_fu_955_p_din1 = grp_hw_AES_fu_243_state;

assign grp_hw_AES_fu_955_p_din2 = grp_hw_AES_fu_243_key;

assign grp_hw_AES_fu_960_p_din1 = grp_hw_AES_fu_246_state;

assign grp_hw_AES_fu_960_p_din2 = grp_hw_AES_fu_246_key;

assign i_8_fu_381_p2 = (ap_sig_allocacmp_i_7 + 5'd1);

assign icmp_ln311_fu_375_p2 = ((ap_sig_allocacmp_i_7 == 5'd16) ? 1'b1 : 1'b0);

assign num_10_i1_fu_674_p4 = {{val_3[87:80]}};

assign num_10_i_fu_487_p4 = {{val_1[87:80]}};

assign num_11_i1_fu_654_p4 = {{val_3[95:88]}};

assign num_11_i_fu_467_p4 = {{val_1[95:88]}};

assign num_12_i8_fu_634_p4 = {{val_3[103:96]}};

assign num_12_i_fu_447_p4 = {{val_1[103:96]}};

assign num_13_i6_fu_614_p4 = {{val_3[111:104]}};

assign num_13_i_fu_427_p4 = {{val_1[111:104]}};

assign num_14_i4_fu_594_p4 = {{val_3[119:112]}};

assign num_14_i_fu_407_p4 = {{val_1[119:112]}};

assign num_1_i3_fu_584_p4 = {{val_3[15:8]}};

assign num_1_i_fu_397_p4 = {{val_1[15:8]}};

assign num_2_i5_fu_604_p4 = {{val_3[23:16]}};

assign num_2_i_fu_417_p4 = {{val_1[23:16]}};

assign num_3_i7_fu_624_p4 = {{val_3[31:24]}};

assign num_3_i_fu_437_p4 = {{val_1[31:24]}};

assign num_4_i9_fu_644_p4 = {{val_3[39:32]}};

assign num_4_i_fu_457_p4 = {{val_1[39:32]}};

assign num_5_i1_fu_664_p4 = {{val_3[47:40]}};

assign num_5_i_fu_477_p4 = {{val_1[47:40]}};

assign num_6_i1_fu_684_p4 = {{val_3[55:48]}};

assign num_6_i_fu_497_p4 = {{val_1[55:48]}};

assign num_7_i1_fu_704_p4 = {{val_3[63:56]}};

assign num_7_i_fu_517_p4 = {{val_1[63:56]}};

assign num_8_i1_fu_714_p4 = {{val_3[71:64]}};

assign num_8_i_fu_527_p4 = {{val_1[71:64]}};

assign num_9_i1_fu_694_p4 = {{val_3[79:72]}};

assign num_9_i_fu_507_p4 = {{val_1[79:72]}};

assign num_i2_fu_574_p4 = {{val_3[127:120]}};

assign num_i_fu_387_p4 = {{val_1[127:120]}};

assign out_1_fu_724_p17 = {{{{{{{{{{{{{{{{trunc_ln322_1}, {num_1_i3_fu_584_p4}}, {num_2_i5_fu_604_p4}}, {num_3_i7_fu_624_p4}}, {num_4_i9_fu_644_p4}}, {num_5_i1_fu_664_p4}}, {num_6_i1_fu_684_p4}}, {num_7_i1_fu_704_p4}}, {num_8_i1_fu_714_p4}}, {num_9_i1_fu_694_p4}}, {num_10_i1_fu_674_p4}}, {num_11_i1_fu_654_p4}}, {num_12_i8_fu_634_p4}}, {num_13_i6_fu_614_p4}}, {num_14_i4_fu_594_p4}}, {num_i2_fu_574_p4}};

assign out_fu_537_p17 = {{{{{{{{{{{{{{{{trunc_ln}, {num_1_i_fu_397_p4}}, {num_2_i_fu_417_p4}}, {num_3_i_fu_437_p4}}, {num_4_i_fu_457_p4}}, {num_5_i_fu_477_p4}}, {num_6_i_fu_497_p4}}, {num_7_i_fu_517_p4}}, {num_8_i_fu_527_p4}}, {num_9_i_fu_507_p4}}, {num_10_i_fu_487_p4}}, {num_11_i_fu_467_p4}}, {num_12_i_fu_447_p4}}, {num_13_i_fu_427_p4}}, {num_14_i_fu_407_p4}}, {num_i_fu_387_p4}};

assign tmp_13_hw_AES_fu_965_p_din1 = hw_S_3_i;

assign tmp_13_hw_AES_fu_965_p_din2 = out_1_fu_724_p17;

assign tmp_s_hw_AES_fu_970_p_din1 = hw_S_0_i;

assign tmp_s_hw_AES_fu_970_p_din2 = out_fu_537_p17;

assign xor_i_i719_phi_out = xor_i_i719_phi_fu_162;

assign xor_ln234_fu_771_p2 = (hw_S_6_i ^ hw_S_1_i);

endmodule //Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_VITIS_LOOP_311_1
