-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GCM_AE_HW_1x8_GHASH_multi_8x_Pipeline_Q_calc_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    X8_V : IN STD_LOGIC_VECTOR (127 downto 0);
    X7_V : IN STD_LOGIC_VECTOR (127 downto 0);
    X6_V : IN STD_LOGIC_VECTOR (127 downto 0);
    X5_V : IN STD_LOGIC_VECTOR (127 downto 0);
    X4_V : IN STD_LOGIC_VECTOR (127 downto 0);
    X3_V : IN STD_LOGIC_VECTOR (127 downto 0);
    X2_V : IN STD_LOGIC_VECTOR (127 downto 0);
    X1_V : IN STD_LOGIC_VECTOR (127 downto 0);
    no_block_ops_Q : IN STD_LOGIC_VECTOR (22 downto 0);
    hash_payload_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    hash_payload_0_ce0 : OUT STD_LOGIC;
    hash_payload_0_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    hash_payload_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    hash_payload_0_ce1 : OUT STD_LOGIC;
    hash_payload_0_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    hash_payload_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    hash_payload_1_ce0 : OUT STD_LOGIC;
    hash_payload_1_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    hash_payload_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    hash_payload_1_ce1 : OUT STD_LOGIC;
    hash_payload_1_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    hash_payload_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    hash_payload_2_ce0 : OUT STD_LOGIC;
    hash_payload_2_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    hash_payload_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    hash_payload_2_ce1 : OUT STD_LOGIC;
    hash_payload_2_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    hash_payload_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    hash_payload_3_ce0 : OUT STD_LOGIC;
    hash_payload_3_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    hash_payload_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    hash_payload_3_ce1 : OUT STD_LOGIC;
    hash_payload_3_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    H1_operand_V_1_0_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    H1_operand_V_1_0_out_ap_vld : OUT STD_LOGIC;
    H2_operand_V_1_0_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    H2_operand_V_1_0_out_ap_vld : OUT STD_LOGIC;
    H3_operand_V_1_0_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    H3_operand_V_1_0_out_ap_vld : OUT STD_LOGIC;
    H4_operand_V_1_0_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    H4_operand_V_1_0_out_ap_vld : OUT STD_LOGIC;
    H5_operand_V_1_0_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    H5_operand_V_1_0_out_ap_vld : OUT STD_LOGIC;
    H6_operand_V_1_0_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    H6_operand_V_1_0_out_ap_vld : OUT STD_LOGIC;
    H7_operand_V_1_0_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    H7_operand_V_1_0_out_ap_vld : OUT STD_LOGIC;
    H8_operand_V_1_0_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    H8_operand_V_1_0_out_ap_vld : OUT STD_LOGIC;
    H_matrix_7 : IN STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of GCM_AE_HW_1x8_GHASH_multi_8x_Pipeline_Q_calc_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_pp0_stage9 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_pp0_stage10 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv22_1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state14_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal icmp_ln496_reg_662 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage10 : signal is "none";
    signal ap_block_state11_pp0_stage10_iter0 : BOOLEAN;
    signal ap_block_pp0_stage10_subdone : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln496_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hash_payload_0_load_reg_706 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state13_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal hash_payload_1_load_reg_711 : STD_LOGIC_VECTOR (127 downto 0);
    signal hash_payload_2_load_reg_716 : STD_LOGIC_VECTOR (127 downto 0);
    signal hash_payload_3_load_reg_721 : STD_LOGIC_VECTOR (127 downto 0);
    signal hash_payload_0_load_1_reg_726 : STD_LOGIC_VECTOR (127 downto 0);
    signal hash_payload_1_load_1_reg_731 : STD_LOGIC_VECTOR (127 downto 0);
    signal hash_payload_2_load_1_reg_736 : STD_LOGIC_VECTOR (127 downto 0);
    signal hash_payload_3_load_1_reg_741 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal grp_H_operand_gen_8x_fu_330_ap_return_0 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_H_operand_gen_8x_fu_330_ap_return_1 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_H_operand_gen_8x_fu_330_ap_return_2 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_H_operand_gen_8x_fu_330_ap_return_3 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_H_operand_gen_8x_fu_330_ap_return_4 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_H_operand_gen_8x_fu_330_ap_return_5 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_H_operand_gen_8x_fu_330_ap_return_6 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_H_operand_gen_8x_fu_330_ap_return_7 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln499_fu_422_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln499_1_fu_436_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_84 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln496_fu_444_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (21 downto 0);
    signal H8_operand_V_fu_88 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_sig_allocacmp_H8_operand_V_load : STD_LOGIC_VECTOR (127 downto 0);
    signal H7_operand_V_fu_92 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_sig_allocacmp_H7_operand_V_load : STD_LOGIC_VECTOR (127 downto 0);
    signal H6_operand_V_fu_96 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_sig_allocacmp_H6_operand_V_load : STD_LOGIC_VECTOR (127 downto 0);
    signal H5_operand_V_fu_100 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_sig_allocacmp_H5_operand_V_load : STD_LOGIC_VECTOR (127 downto 0);
    signal H4_operand_V_fu_104 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_sig_allocacmp_H4_operand_V_load : STD_LOGIC_VECTOR (127 downto 0);
    signal H3_operand_V_fu_108 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_sig_allocacmp_H3_operand_V_load : STD_LOGIC_VECTOR (127 downto 0);
    signal H2_operand_V_fu_112 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_sig_allocacmp_H2_operand_V_load : STD_LOGIC_VECTOR (127 downto 0);
    signal H1_operand_V_fu_116 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_sig_allocacmp_H1_operand_V_load : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal zext_ln496_fu_400_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln499_fu_410_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln_fu_414_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln499_fu_430_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_state6_pp0_stage5_iter0 : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_state7_pp0_stage6_iter0 : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_state8_pp0_stage7_iter0 : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_block_state9_pp0_stage8_iter0 : BOOLEAN;
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal ap_block_state10_pp0_stage9_iter0 : BOOLEAN;
    signal ap_block_pp0_stage9_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GCM_AE_HW_1x8_H_operand_gen_8x IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        X1_operand : IN STD_LOGIC_VECTOR (127 downto 0);
        X2_operand : IN STD_LOGIC_VECTOR (127 downto 0);
        X3_operand : IN STD_LOGIC_VECTOR (127 downto 0);
        X4_operand : IN STD_LOGIC_VECTOR (127 downto 0);
        X5_operand : IN STD_LOGIC_VECTOR (127 downto 0);
        X6_operand : IN STD_LOGIC_VECTOR (127 downto 0);
        X7_operand : IN STD_LOGIC_VECTOR (127 downto 0);
        X8_operand : IN STD_LOGIC_VECTOR (127 downto 0);
        H8_operand_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        H7_operand_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        H6_operand_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        H5_operand_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        H4_operand_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        H3_operand_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        H2_operand_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        H1_operand_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        H_matrix_7 : IN STD_LOGIC_VECTOR (127 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (127 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component GCM_AE_HW_1x8_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    grp_H_operand_gen_8x_fu_330 : component GCM_AE_HW_1x8_H_operand_gen_8x
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        X1_operand => hash_payload_0_load_reg_706,
        X2_operand => hash_payload_1_load_reg_711,
        X3_operand => hash_payload_2_load_reg_716,
        X4_operand => hash_payload_3_load_reg_721,
        X5_operand => hash_payload_0_load_1_reg_726,
        X6_operand => hash_payload_1_load_1_reg_731,
        X7_operand => hash_payload_2_load_1_reg_736,
        X8_operand => hash_payload_3_load_1_reg_741,
        H8_operand_V_read => ap_sig_allocacmp_H8_operand_V_load,
        H7_operand_V_read => ap_sig_allocacmp_H7_operand_V_load,
        H6_operand_V_read => ap_sig_allocacmp_H6_operand_V_load,
        H5_operand_V_read => ap_sig_allocacmp_H5_operand_V_load,
        H4_operand_V_read => ap_sig_allocacmp_H4_operand_V_load,
        H3_operand_V_read => ap_sig_allocacmp_H3_operand_V_load,
        H2_operand_V_read => ap_sig_allocacmp_H2_operand_V_load,
        H1_operand_V_read => ap_sig_allocacmp_H1_operand_V_load,
        H_matrix_7 => H_matrix_7,
        ap_return_0 => grp_H_operand_gen_8x_fu_330_ap_return_0,
        ap_return_1 => grp_H_operand_gen_8x_fu_330_ap_return_1,
        ap_return_2 => grp_H_operand_gen_8x_fu_330_ap_return_2,
        ap_return_3 => grp_H_operand_gen_8x_fu_330_ap_return_3,
        ap_return_4 => grp_H_operand_gen_8x_fu_330_ap_return_4,
        ap_return_5 => grp_H_operand_gen_8x_fu_330_ap_return_5,
        ap_return_6 => grp_H_operand_gen_8x_fu_330_ap_return_6,
        ap_return_7 => grp_H_operand_gen_8x_fu_330_ap_return_7);

    flow_control_loop_pipe_sequential_init_U : component GCM_AE_HW_1x8_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage10_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    H1_operand_V_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                H1_operand_V_fu_116 <= X8_V;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                H1_operand_V_fu_116 <= grp_H_operand_gen_8x_fu_330_ap_return_7;
            end if; 
        end if;
    end process;

    H2_operand_V_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                H2_operand_V_fu_112 <= X7_V;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                H2_operand_V_fu_112 <= grp_H_operand_gen_8x_fu_330_ap_return_6;
            end if; 
        end if;
    end process;

    H3_operand_V_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                H3_operand_V_fu_108 <= X6_V;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                H3_operand_V_fu_108 <= grp_H_operand_gen_8x_fu_330_ap_return_5;
            end if; 
        end if;
    end process;

    H4_operand_V_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                H4_operand_V_fu_104 <= X5_V;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                H4_operand_V_fu_104 <= grp_H_operand_gen_8x_fu_330_ap_return_4;
            end if; 
        end if;
    end process;

    H5_operand_V_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                H5_operand_V_fu_100 <= X4_V;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                H5_operand_V_fu_100 <= grp_H_operand_gen_8x_fu_330_ap_return_3;
            end if; 
        end if;
    end process;

    H6_operand_V_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                H6_operand_V_fu_96 <= X3_V;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                H6_operand_V_fu_96 <= grp_H_operand_gen_8x_fu_330_ap_return_2;
            end if; 
        end if;
    end process;

    H7_operand_V_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                H7_operand_V_fu_92 <= X2_V;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                H7_operand_V_fu_92 <= grp_H_operand_gen_8x_fu_330_ap_return_1;
            end if; 
        end if;
    end process;

    H8_operand_V_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                H8_operand_V_fu_88 <= X1_V;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                H8_operand_V_fu_88 <= grp_H_operand_gen_8x_fu_330_ap_return_0;
            end if; 
        end if;
    end process;

    i_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln496_fu_404_p2 = ap_const_lv1_1))) then 
                    i_fu_84 <= add_ln496_fu_444_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_84 <= ap_const_lv22_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln496_reg_662 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                hash_payload_0_load_1_reg_726 <= hash_payload_0_q0;
                hash_payload_0_load_reg_706 <= hash_payload_0_q1;
                hash_payload_1_load_1_reg_731 <= hash_payload_1_q0;
                hash_payload_1_load_reg_711 <= hash_payload_1_q1;
                hash_payload_2_load_1_reg_736 <= hash_payload_2_q0;
                hash_payload_2_load_reg_716 <= hash_payload_2_q1;
                hash_payload_3_load_1_reg_741 <= hash_payload_3_q0;
                hash_payload_3_load_reg_721 <= hash_payload_3_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln496_reg_662 <= icmp_ln496_fu_404_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter0_stage2, ap_block_pp0_stage10_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_block_pp0_stage8_subdone, ap_block_pp0_stage9_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when ap_ST_fsm_pp0_stage9 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage9_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                end if;
            when ap_ST_fsm_pp0_stage10 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage10_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    H1_operand_V_1_0_out <= H1_operand_V_fu_116;

    H1_operand_V_1_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln496_reg_662, ap_block_pp0_stage2_11001)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            H1_operand_V_1_0_out_ap_vld <= ap_const_logic_1;
        else 
            H1_operand_V_1_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    H2_operand_V_1_0_out <= H2_operand_V_fu_112;

    H2_operand_V_1_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln496_reg_662, ap_block_pp0_stage2_11001)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            H2_operand_V_1_0_out_ap_vld <= ap_const_logic_1;
        else 
            H2_operand_V_1_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    H3_operand_V_1_0_out <= H3_operand_V_fu_108;

    H3_operand_V_1_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln496_reg_662, ap_block_pp0_stage2_11001)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            H3_operand_V_1_0_out_ap_vld <= ap_const_logic_1;
        else 
            H3_operand_V_1_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    H4_operand_V_1_0_out <= H4_operand_V_fu_104;

    H4_operand_V_1_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln496_reg_662, ap_block_pp0_stage2_11001)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            H4_operand_V_1_0_out_ap_vld <= ap_const_logic_1;
        else 
            H4_operand_V_1_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    H5_operand_V_1_0_out <= H5_operand_V_fu_100;

    H5_operand_V_1_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln496_reg_662, ap_block_pp0_stage2_11001)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            H5_operand_V_1_0_out_ap_vld <= ap_const_logic_1;
        else 
            H5_operand_V_1_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    H6_operand_V_1_0_out <= H6_operand_V_fu_96;

    H6_operand_V_1_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln496_reg_662, ap_block_pp0_stage2_11001)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            H6_operand_V_1_0_out_ap_vld <= ap_const_logic_1;
        else 
            H6_operand_V_1_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    H7_operand_V_1_0_out <= H7_operand_V_fu_92;

    H7_operand_V_1_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln496_reg_662, ap_block_pp0_stage2_11001)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            H7_operand_V_1_0_out_ap_vld <= ap_const_logic_1;
        else 
            H7_operand_V_1_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    H8_operand_V_1_0_out <= H8_operand_V_fu_88;

    H8_operand_V_1_0_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln496_reg_662, ap_block_pp0_stage2_11001)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            H8_operand_V_1_0_out_ap_vld <= ap_const_logic_1;
        else 
            H8_operand_V_1_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln496_fu_444_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv22_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage10 <= ap_CS_fsm(10);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage10_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage9_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage9_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage10_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage4_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage5_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage6_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage7_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage8_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, icmp_ln496_reg_662)
    begin
        if (((icmp_ln496_reg_662 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage10, ap_block_pp0_stage10_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage10_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage10))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_H1_operand_V_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, grp_H_operand_gen_8x_fu_330_ap_return_7, ap_block_pp0_stage2, H1_operand_V_fu_116)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_sig_allocacmp_H1_operand_V_load <= grp_H_operand_gen_8x_fu_330_ap_return_7;
        else 
            ap_sig_allocacmp_H1_operand_V_load <= H1_operand_V_fu_116;
        end if; 
    end process;


    ap_sig_allocacmp_H2_operand_V_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, grp_H_operand_gen_8x_fu_330_ap_return_6, ap_block_pp0_stage2, H2_operand_V_fu_112)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_sig_allocacmp_H2_operand_V_load <= grp_H_operand_gen_8x_fu_330_ap_return_6;
        else 
            ap_sig_allocacmp_H2_operand_V_load <= H2_operand_V_fu_112;
        end if; 
    end process;


    ap_sig_allocacmp_H3_operand_V_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, grp_H_operand_gen_8x_fu_330_ap_return_5, ap_block_pp0_stage2, H3_operand_V_fu_108)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_sig_allocacmp_H3_operand_V_load <= grp_H_operand_gen_8x_fu_330_ap_return_5;
        else 
            ap_sig_allocacmp_H3_operand_V_load <= H3_operand_V_fu_108;
        end if; 
    end process;


    ap_sig_allocacmp_H4_operand_V_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, grp_H_operand_gen_8x_fu_330_ap_return_4, ap_block_pp0_stage2, H4_operand_V_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_sig_allocacmp_H4_operand_V_load <= grp_H_operand_gen_8x_fu_330_ap_return_4;
        else 
            ap_sig_allocacmp_H4_operand_V_load <= H4_operand_V_fu_104;
        end if; 
    end process;


    ap_sig_allocacmp_H5_operand_V_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, grp_H_operand_gen_8x_fu_330_ap_return_3, ap_block_pp0_stage2, H5_operand_V_fu_100)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_sig_allocacmp_H5_operand_V_load <= grp_H_operand_gen_8x_fu_330_ap_return_3;
        else 
            ap_sig_allocacmp_H5_operand_V_load <= H5_operand_V_fu_100;
        end if; 
    end process;


    ap_sig_allocacmp_H6_operand_V_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, grp_H_operand_gen_8x_fu_330_ap_return_2, ap_block_pp0_stage2, H6_operand_V_fu_96)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_sig_allocacmp_H6_operand_V_load <= grp_H_operand_gen_8x_fu_330_ap_return_2;
        else 
            ap_sig_allocacmp_H6_operand_V_load <= H6_operand_V_fu_96;
        end if; 
    end process;


    ap_sig_allocacmp_H7_operand_V_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, grp_H_operand_gen_8x_fu_330_ap_return_1, ap_block_pp0_stage2, H7_operand_V_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_sig_allocacmp_H7_operand_V_load <= grp_H_operand_gen_8x_fu_330_ap_return_1;
        else 
            ap_sig_allocacmp_H7_operand_V_load <= H7_operand_V_fu_92;
        end if; 
    end process;


    ap_sig_allocacmp_H8_operand_V_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, grp_H_operand_gen_8x_fu_330_ap_return_0, ap_block_pp0_stage2, H8_operand_V_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_sig_allocacmp_H8_operand_V_load <= grp_H_operand_gen_8x_fu_330_ap_return_0;
        else 
            ap_sig_allocacmp_H8_operand_V_load <= H8_operand_V_fu_88;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_84, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv22_1;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_84;
        end if; 
    end process;

    hash_payload_0_address0 <= zext_ln499_1_fu_436_p1(8 - 1 downto 0);
    hash_payload_0_address1 <= zext_ln499_fu_422_p1(8 - 1 downto 0);

    hash_payload_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_payload_0_ce0 <= ap_const_logic_1;
        else 
            hash_payload_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hash_payload_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_payload_0_ce1 <= ap_const_logic_1;
        else 
            hash_payload_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    hash_payload_1_address0 <= zext_ln499_1_fu_436_p1(8 - 1 downto 0);
    hash_payload_1_address1 <= zext_ln499_fu_422_p1(8 - 1 downto 0);

    hash_payload_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_payload_1_ce0 <= ap_const_logic_1;
        else 
            hash_payload_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hash_payload_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_payload_1_ce1 <= ap_const_logic_1;
        else 
            hash_payload_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    hash_payload_2_address0 <= zext_ln499_1_fu_436_p1(8 - 1 downto 0);
    hash_payload_2_address1 <= zext_ln499_fu_422_p1(8 - 1 downto 0);

    hash_payload_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_payload_2_ce0 <= ap_const_logic_1;
        else 
            hash_payload_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hash_payload_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_payload_2_ce1 <= ap_const_logic_1;
        else 
            hash_payload_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    hash_payload_3_address0 <= zext_ln499_1_fu_436_p1(8 - 1 downto 0);
    hash_payload_3_address1 <= zext_ln499_fu_422_p1(8 - 1 downto 0);

    hash_payload_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_payload_3_ce0 <= ap_const_logic_1;
        else 
            hash_payload_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hash_payload_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_payload_3_ce1 <= ap_const_logic_1;
        else 
            hash_payload_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln496_fu_404_p2 <= "1" when (signed(zext_ln496_fu_400_p1) < signed(no_block_ops_Q)) else "0";
    or_ln499_fu_430_p2 <= (shl_ln_fu_414_p3 or ap_const_lv8_1);
    shl_ln_fu_414_p3 <= (trunc_ln499_fu_410_p1 & ap_const_lv1_0);
    trunc_ln499_fu_410_p1 <= ap_sig_allocacmp_i_5(7 - 1 downto 0);
    zext_ln496_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_5),23));
    zext_ln499_1_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln499_fu_430_p2),64));
    zext_ln499_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_414_p3),64));
end behav;
