-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GCM_AE_HW_1x1_AES_cipher is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    in_r : IN STD_LOGIC_VECTOR (127 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read34 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read35 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read36 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read37 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read38 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read39 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read40 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read41 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read42 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read43 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read44 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read45 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read46 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read47 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read48 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read49 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read50 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read51 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read52 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read53 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read54 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read55 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read56 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read57 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read58 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read59 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read60 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read61 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read62 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read63 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read64 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read65 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read66 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read67 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read68 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read69 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read70 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read71 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read72 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read73 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read74 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read75 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read76 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read77 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read78 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read79 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read80 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read81 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read82 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read83 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read84 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read85 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read86 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read87 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read88 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read89 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read90 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read91 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read92 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read93 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read94 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read95 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read96 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read97 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read98 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read99 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read100 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read101 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read102 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read103 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read104 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read105 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read106 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read107 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read108 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read109 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read110 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read111 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read112 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read113 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read114 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read115 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read116 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read117 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read118 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read119 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read120 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read121 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read122 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read123 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read124 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read125 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read126 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read127 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read128 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read129 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read130 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read131 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read132 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read133 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read134 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read135 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read136 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read137 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read138 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read139 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read140 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read141 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read142 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read143 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read144 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read145 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read146 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read147 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read148 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read149 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read150 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read151 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read152 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read153 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read154 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read155 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read156 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read157 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read158 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read159 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read160 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read161 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read162 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read163 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read164 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read165 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read166 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read167 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read168 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read169 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read170 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read171 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read172 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read173 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read174 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read175 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read176 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read177 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read178 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read179 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read180 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read181 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read182 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read183 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read184 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read185 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read186 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read187 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read188 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read189 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read190 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read191 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read192 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read193 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read194 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read195 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read196 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read197 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read198 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read199 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read200 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read201 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read202 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read203 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read204 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read205 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read206 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read207 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read208 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read209 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read210 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read211 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read212 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read213 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read214 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read215 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read216 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read217 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read218 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read219 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read220 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read221 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read222 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read223 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read224 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read225 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read226 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read227 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read228 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read229 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read230 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read231 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read232 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read233 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read234 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read235 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read236 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read237 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read238 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read239 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read240 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of GCM_AE_HW_1x1_AES_cipher is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal grp_Cipher_fu_1936_ap_start : STD_LOGIC;
    signal grp_Cipher_fu_1936_ap_done : STD_LOGIC;
    signal grp_Cipher_fu_1936_ap_idle : STD_LOGIC;
    signal grp_Cipher_fu_1936_ap_ready : STD_LOGIC;
    signal grp_Cipher_fu_1936_ap_ce : STD_LOGIC;
    signal grp_Cipher_fu_1936_ap_return : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_block_state1_pp0_stage0_iter0_ignore_call241 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call241 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call241 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call241 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call241 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call241 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call241 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call241 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8_ignore_call241 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9_ignore_call241 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10_ignore_call241 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11_ignore_call241 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12_ignore_call241 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13_ignore_call241 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14_ignore_call241 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp257 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to13 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GCM_AE_HW_1x1_Cipher IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        state : IN STD_LOGIC_VECTOR (127 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read21 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read23 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read24 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read25 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read27 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read28 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read29 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read31 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read32 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read33 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read34 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read35 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read36 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read37 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read38 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read39 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read40 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read41 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read42 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read43 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read44 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read45 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read46 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read47 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read48 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read49 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read50 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read51 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read52 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read53 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read54 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read55 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read56 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read57 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read58 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read59 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read60 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read61 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read62 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read63 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read64 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read65 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read66 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read67 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read68 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read69 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read70 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read71 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read72 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read73 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read74 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read75 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read76 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read77 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read78 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read79 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read80 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read81 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read82 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read83 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read84 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read85 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read86 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read87 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read88 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read89 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read90 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read91 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read92 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read93 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read94 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read95 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read96 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read97 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read98 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read99 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read100 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read101 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read102 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read103 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read104 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read105 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read106 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read107 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read108 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read109 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read110 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read111 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read112 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read113 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read114 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read115 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read116 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read117 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read118 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read119 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read120 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read121 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read122 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read123 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read124 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read125 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read126 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read127 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read128 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read129 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read130 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read131 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read132 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read133 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read134 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read135 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read136 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read137 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read138 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read139 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read140 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read141 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read142 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read143 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read144 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read145 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read146 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read147 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read148 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read149 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read150 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read151 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read152 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read153 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read154 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read155 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read156 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read157 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read158 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read159 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read160 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read161 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read162 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read163 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read164 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read165 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read166 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read167 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read168 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read169 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read170 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read171 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read172 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read173 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read174 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read175 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read176 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read177 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read178 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read179 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read180 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read181 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read182 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read183 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read184 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read185 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read186 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read187 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read188 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read189 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read190 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read191 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read192 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read193 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read194 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read195 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read196 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read197 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read198 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read199 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read200 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read201 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read202 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read203 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read204 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read205 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read206 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read207 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read208 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read209 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read210 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read211 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read212 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read213 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read214 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read215 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read216 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read217 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read218 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read219 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read220 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read221 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read222 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read223 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read224 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read225 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read226 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read227 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read228 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read229 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read230 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read231 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read232 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read233 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read234 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read235 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read236 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read237 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read238 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read239 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read240 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;



begin
    grp_Cipher_fu_1936 : component GCM_AE_HW_1x1_Cipher
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Cipher_fu_1936_ap_start,
        ap_done => grp_Cipher_fu_1936_ap_done,
        ap_idle => grp_Cipher_fu_1936_ap_idle,
        ap_ready => grp_Cipher_fu_1936_ap_ready,
        ap_ce => grp_Cipher_fu_1936_ap_ce,
        state => in_r,
        p_read1 => p_read1,
        p_read2 => p_read2,
        p_read3 => p_read3,
        p_read4 => p_read4,
        p_read5 => p_read5,
        p_read6 => p_read6,
        p_read7 => p_read7,
        p_read8 => p_read8,
        p_read9 => p_read9,
        p_read10 => p_read10,
        p_read11 => p_read11,
        p_read12 => p_read12,
        p_read13 => p_read13,
        p_read14 => p_read14,
        p_read15 => p_read15,
        p_read16 => p_read16,
        p_read17 => p_read17,
        p_read18 => p_read18,
        p_read19 => p_read19,
        p_read20 => p_read20,
        p_read21 => p_read21,
        p_read22 => p_read22,
        p_read23 => p_read23,
        p_read24 => p_read24,
        p_read25 => p_read25,
        p_read26 => p_read26,
        p_read27 => p_read27,
        p_read28 => p_read28,
        p_read29 => p_read29,
        p_read30 => p_read30,
        p_read31 => p_read31,
        p_read32 => p_read32,
        p_read33 => p_read33,
        p_read34 => p_read34,
        p_read35 => p_read35,
        p_read36 => p_read36,
        p_read37 => p_read37,
        p_read38 => p_read38,
        p_read39 => p_read39,
        p_read40 => p_read40,
        p_read41 => p_read41,
        p_read42 => p_read42,
        p_read43 => p_read43,
        p_read44 => p_read44,
        p_read45 => p_read45,
        p_read46 => p_read46,
        p_read47 => p_read47,
        p_read48 => p_read48,
        p_read49 => p_read49,
        p_read50 => p_read50,
        p_read51 => p_read51,
        p_read52 => p_read52,
        p_read53 => p_read53,
        p_read54 => p_read54,
        p_read55 => p_read55,
        p_read56 => p_read56,
        p_read57 => p_read57,
        p_read58 => p_read58,
        p_read59 => p_read59,
        p_read60 => p_read60,
        p_read61 => p_read61,
        p_read62 => p_read62,
        p_read63 => p_read63,
        p_read64 => p_read64,
        p_read65 => p_read65,
        p_read66 => p_read66,
        p_read67 => p_read67,
        p_read68 => p_read68,
        p_read69 => p_read69,
        p_read70 => p_read70,
        p_read71 => p_read71,
        p_read72 => p_read72,
        p_read73 => p_read73,
        p_read74 => p_read74,
        p_read75 => p_read75,
        p_read76 => p_read76,
        p_read77 => p_read77,
        p_read78 => p_read78,
        p_read79 => p_read79,
        p_read80 => p_read80,
        p_read81 => p_read81,
        p_read82 => p_read82,
        p_read83 => p_read83,
        p_read84 => p_read84,
        p_read85 => p_read85,
        p_read86 => p_read86,
        p_read87 => p_read87,
        p_read88 => p_read88,
        p_read89 => p_read89,
        p_read90 => p_read90,
        p_read91 => p_read91,
        p_read92 => p_read92,
        p_read93 => p_read93,
        p_read94 => p_read94,
        p_read95 => p_read95,
        p_read96 => p_read96,
        p_read97 => p_read97,
        p_read98 => p_read98,
        p_read99 => p_read99,
        p_read100 => p_read100,
        p_read101 => p_read101,
        p_read102 => p_read102,
        p_read103 => p_read103,
        p_read104 => p_read104,
        p_read105 => p_read105,
        p_read106 => p_read106,
        p_read107 => p_read107,
        p_read108 => p_read108,
        p_read109 => p_read109,
        p_read110 => p_read110,
        p_read111 => p_read111,
        p_read112 => p_read112,
        p_read113 => p_read113,
        p_read114 => p_read114,
        p_read115 => p_read115,
        p_read116 => p_read116,
        p_read117 => p_read117,
        p_read118 => p_read118,
        p_read119 => p_read119,
        p_read120 => p_read120,
        p_read121 => p_read121,
        p_read122 => p_read122,
        p_read123 => p_read123,
        p_read124 => p_read124,
        p_read125 => p_read125,
        p_read126 => p_read126,
        p_read127 => p_read127,
        p_read128 => p_read128,
        p_read129 => p_read129,
        p_read130 => p_read130,
        p_read131 => p_read131,
        p_read132 => p_read132,
        p_read133 => p_read133,
        p_read134 => p_read134,
        p_read135 => p_read135,
        p_read136 => p_read136,
        p_read137 => p_read137,
        p_read138 => p_read138,
        p_read139 => p_read139,
        p_read140 => p_read140,
        p_read141 => p_read141,
        p_read142 => p_read142,
        p_read143 => p_read143,
        p_read144 => p_read144,
        p_read145 => p_read145,
        p_read146 => p_read146,
        p_read147 => p_read147,
        p_read148 => p_read148,
        p_read149 => p_read149,
        p_read150 => p_read150,
        p_read151 => p_read151,
        p_read152 => p_read152,
        p_read153 => p_read153,
        p_read154 => p_read154,
        p_read155 => p_read155,
        p_read156 => p_read156,
        p_read157 => p_read157,
        p_read158 => p_read158,
        p_read159 => p_read159,
        p_read160 => p_read160,
        p_read161 => p_read161,
        p_read162 => p_read162,
        p_read163 => p_read163,
        p_read164 => p_read164,
        p_read165 => p_read165,
        p_read166 => p_read166,
        p_read167 => p_read167,
        p_read168 => p_read168,
        p_read169 => p_read169,
        p_read170 => p_read170,
        p_read171 => p_read171,
        p_read172 => p_read172,
        p_read173 => p_read173,
        p_read174 => p_read174,
        p_read175 => p_read175,
        p_read176 => p_read176,
        p_read177 => p_read177,
        p_read178 => p_read178,
        p_read179 => p_read179,
        p_read180 => p_read180,
        p_read181 => p_read181,
        p_read182 => p_read182,
        p_read183 => p_read183,
        p_read184 => p_read184,
        p_read185 => p_read185,
        p_read186 => p_read186,
        p_read187 => p_read187,
        p_read188 => p_read188,
        p_read189 => p_read189,
        p_read190 => p_read190,
        p_read191 => p_read191,
        p_read192 => p_read192,
        p_read193 => p_read193,
        p_read194 => p_read194,
        p_read195 => p_read195,
        p_read196 => p_read196,
        p_read197 => p_read197,
        p_read198 => p_read198,
        p_read199 => p_read199,
        p_read200 => p_read200,
        p_read201 => p_read201,
        p_read202 => p_read202,
        p_read203 => p_read203,
        p_read204 => p_read204,
        p_read205 => p_read205,
        p_read206 => p_read206,
        p_read207 => p_read207,
        p_read208 => p_read208,
        p_read209 => p_read209,
        p_read210 => p_read210,
        p_read211 => p_read211,
        p_read212 => p_read212,
        p_read213 => p_read213,
        p_read214 => p_read214,
        p_read215 => p_read215,
        p_read216 => p_read216,
        p_read217 => p_read217,
        p_read218 => p_read218,
        p_read219 => p_read219,
        p_read220 => p_read220,
        p_read221 => p_read221,
        p_read222 => p_read222,
        p_read223 => p_read223,
        p_read224 => p_read224,
        p_read225 => p_read225,
        p_read226 => p_read226,
        p_read227 => p_read227,
        p_read228 => p_read228,
        p_read229 => p_read229,
        p_read230 => p_read230,
        p_read231 => p_read231,
        p_read232 => p_read232,
        p_read233 => p_read233,
        p_read234 => p_read234,
        p_read235 => p_read235,
        p_read236 => p_read236,
        p_read237 => p_read237,
        p_read238 => p_read238,
        p_read239 => p_read239,
        p_read240 => p_read240,
        ap_return => grp_Cipher_fu_1936_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp257 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8_ignore_call241 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to13_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to13 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to13 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to13)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to13 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= grp_Cipher_fu_1936_ap_return;

    grp_Cipher_fu_1936_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_ce, ap_block_pp0_stage0_11001_ignoreCallOp257)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp257) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_Cipher_fu_1936_ap_ce <= ap_const_logic_1;
        else 
            grp_Cipher_fu_1936_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_Cipher_fu_1936_ap_start_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_Cipher_fu_1936_ap_start <= ap_const_logic_1;
        else 
            grp_Cipher_fu_1936_ap_start <= ap_const_logic_0;
        end if; 
    end process;

end behav;
