-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_VITIS_LOOP_311_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    val_1 : IN STD_LOGIC_VECTOR (127 downto 0);
    trunc_ln : IN STD_LOGIC_VECTOR (7 downto 0);
    val_3 : IN STD_LOGIC_VECTOR (127 downto 0);
    trunc_ln322_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    xor_i_i719_phi_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    xor_i_i719_phi_out_ap_vld : OUT STD_LOGIC;
    call_i_i720_phi_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    call_i_i720_phi_out_ap_vld : OUT STD_LOGIC;
    call2_i_i721_phi_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    call2_i_i721_phi_out_ap_vld : OUT STD_LOGIC;
    call4_i_i722_phi_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    call4_i_i722_phi_out_ap_vld : OUT STD_LOGIC;
    call6_i_i723_phi_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    call6_i_i723_phi_out_ap_vld : OUT STD_LOGIC;
    call8_i_i724_phi_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    call8_i_i724_phi_out_ap_vld : OUT STD_LOGIC;
    call10_i_i725_phi_out : OUT STD_LOGIC_VECTOR (127 downto 0);
    call10_i_i725_phi_out_ap_vld : OUT STD_LOGIC;
    hw_S_6_i : IN STD_LOGIC_VECTOR (127 downto 0);
    hw_S_6_o : OUT STD_LOGIC_VECTOR (127 downto 0);
    hw_S_6_o_ap_vld : OUT STD_LOGIC;
    hw_S_1_i : IN STD_LOGIC_VECTOR (127 downto 0);
    hw_S_1_o : OUT STD_LOGIC_VECTOR (127 downto 0);
    hw_S_1_o_ap_vld : OUT STD_LOGIC;
    hw_S_0_i : IN STD_LOGIC_VECTOR (127 downto 0);
    hw_S_0_o : OUT STD_LOGIC_VECTOR (127 downto 0);
    hw_S_0_o_ap_vld : OUT STD_LOGIC;
    hw_S_2_i : IN STD_LOGIC_VECTOR (127 downto 0);
    hw_S_2_o : OUT STD_LOGIC_VECTOR (127 downto 0);
    hw_S_2_o_ap_vld : OUT STD_LOGIC;
    hw_S_3_i : IN STD_LOGIC_VECTOR (127 downto 0);
    hw_S_3_o : OUT STD_LOGIC_VECTOR (127 downto 0);
    hw_S_3_o_ap_vld : OUT STD_LOGIC;
    hw_S_4_i : IN STD_LOGIC_VECTOR (127 downto 0);
    hw_S_4_o : OUT STD_LOGIC_VECTOR (127 downto 0);
    hw_S_4_o_ap_vld : OUT STD_LOGIC;
    hw_S_5_i : IN STD_LOGIC_VECTOR (127 downto 0);
    hw_S_5_o : OUT STD_LOGIC_VECTOR (127 downto 0);
    hw_S_5_o_ap_vld : OUT STD_LOGIC;
    grp_hw_AES_fu_955_p_din1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    grp_hw_AES_fu_955_p_din2 : OUT STD_LOGIC_VECTOR (127 downto 0);
    grp_hw_AES_fu_955_p_dout0 : IN STD_LOGIC_VECTOR (127 downto 0);
    grp_hw_AES_fu_955_p_ready : IN STD_LOGIC;
    grp_hw_AES_fu_960_p_din1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    grp_hw_AES_fu_960_p_din2 : OUT STD_LOGIC_VECTOR (127 downto 0);
    grp_hw_AES_fu_960_p_dout0 : IN STD_LOGIC_VECTOR (127 downto 0);
    grp_hw_AES_fu_960_p_ready : IN STD_LOGIC;
    tmp_13_hw_AES_fu_965_p_din1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    tmp_13_hw_AES_fu_965_p_din2 : OUT STD_LOGIC_VECTOR (127 downto 0);
    tmp_13_hw_AES_fu_965_p_dout0 : IN STD_LOGIC_VECTOR (127 downto 0);
    tmp_13_hw_AES_fu_965_p_ready : IN STD_LOGIC;
    tmp_s_hw_AES_fu_970_p_din1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    tmp_s_hw_AES_fu_970_p_din2 : OUT STD_LOGIC_VECTOR (127 downto 0);
    tmp_s_hw_AES_fu_970_p_dout0 : IN STD_LOGIC_VECTOR (127 downto 0);
    tmp_s_hw_AES_fu_970_p_ready : IN STD_LOGIC );
end;


architecture behav of Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_VITIS_LOOP_311_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln311_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal tmp_13_reg_356 : STD_LOGIC_VECTOR (127 downto 0);
    signal hw_S_3_load_reg_966 : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_hw_AES_fu_243_state : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_hw_AES_fu_243_key : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_hw_AES_fu_246_state : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_hw_AES_fu_246_key : STD_LOGIC_VECTOR (127 downto 0);
    signal out_fu_537_p17 : STD_LOGIC_VECTOR (127 downto 0);
    signal out_1_fu_724_p17 : STD_LOGIC_VECTOR (127 downto 0);
    signal xor_ln234_fu_771_p2 : STD_LOGIC_VECTOR (127 downto 0);
    signal call10_i_i725_phi_fu_138 : STD_LOGIC_VECTOR (127 downto 0);
    signal call8_i_i724_phi_fu_142 : STD_LOGIC_VECTOR (127 downto 0);
    signal call6_i_i723_phi_fu_146 : STD_LOGIC_VECTOR (127 downto 0);
    signal call4_i_i722_phi_fu_150 : STD_LOGIC_VECTOR (127 downto 0);
    signal call2_i_i721_phi_fu_154 : STD_LOGIC_VECTOR (127 downto 0);
    signal call_i_i720_phi_fu_158 : STD_LOGIC_VECTOR (127 downto 0);
    signal xor_i_i719_phi_fu_162 : STD_LOGIC_VECTOR (127 downto 0);
    signal i_fu_166 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_8_fu_381_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_7 : STD_LOGIC_VECTOR (4 downto 0);
    signal num_1_i_fu_397_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_2_i_fu_417_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_3_i_fu_437_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_4_i_fu_457_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_5_i_fu_477_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_6_i_fu_497_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_7_i_fu_517_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_8_i_fu_527_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_9_i_fu_507_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_10_i_fu_487_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_11_i_fu_467_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_12_i_fu_447_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_13_i_fu_427_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_14_i_fu_407_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_i_fu_387_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_1_i3_fu_584_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_2_i5_fu_604_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_3_i7_fu_624_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_4_i9_fu_644_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_5_i1_fu_664_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_6_i1_fu_684_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_7_i1_fu_704_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_8_i1_fu_714_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_9_i1_fu_694_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_10_i1_fu_674_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_11_i1_fu_654_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_12_i8_fu_634_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_13_i6_fu_614_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_14_i4_fu_594_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal num_i2_fu_574_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Rocca_S_hw_v2_hw_AES IS
    port (
        ap_ready : OUT STD_LOGIC;
        state : IN STD_LOGIC_VECTOR (127 downto 0);
        key : IN STD_LOGIC_VECTOR (127 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component Rocca_S_hw_v2_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Rocca_S_hw_v2_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_start_int = ap_const_logic_1) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln311_fu_375_p2 = ap_const_lv1_0)) then 
                    i_fu_166 <= i_8_fu_381_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_166 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                call10_i_i725_phi_fu_138 <= grp_hw_AES_fu_960_p_dout0;
                call8_i_i724_phi_fu_142 <= grp_hw_AES_fu_955_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                call2_i_i721_phi_fu_154 <= grp_hw_AES_fu_960_p_dout0;
                call4_i_i722_phi_fu_150 <= grp_hw_AES_fu_955_p_dout0;
                call6_i_i723_phi_fu_146 <= tmp_13_hw_AES_fu_965_p_dout0;
                call_i_i720_phi_fu_158 <= tmp_s_hw_AES_fu_970_p_dout0;
                hw_S_3_load_reg_966 <= hw_S_3_i;
                tmp_13_reg_356 <= tmp_13_hw_AES_fu_965_p_dout0;
                xor_i_i719_phi_fu_162 <= xor_ln234_fu_771_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_7_assign_proc : process(ap_CS_fsm_state1, i_fu_166, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_7 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_7 <= i_fu_166;
        end if; 
    end process;

    call10_i_i725_phi_out <= call10_i_i725_phi_fu_138;

    call10_i_i725_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            call10_i_i725_phi_out_ap_vld <= ap_const_logic_1;
        else 
            call10_i_i725_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    call2_i_i721_phi_out <= call2_i_i721_phi_fu_154;

    call2_i_i721_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            call2_i_i721_phi_out_ap_vld <= ap_const_logic_1;
        else 
            call2_i_i721_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    call4_i_i722_phi_out <= call4_i_i722_phi_fu_150;

    call4_i_i722_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            call4_i_i722_phi_out_ap_vld <= ap_const_logic_1;
        else 
            call4_i_i722_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    call6_i_i723_phi_out <= call6_i_i723_phi_fu_146;

    call6_i_i723_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            call6_i_i723_phi_out_ap_vld <= ap_const_logic_1;
        else 
            call6_i_i723_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    call8_i_i724_phi_out <= call8_i_i724_phi_fu_142;

    call8_i_i724_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            call8_i_i724_phi_out_ap_vld <= ap_const_logic_1;
        else 
            call8_i_i724_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    call_i_i720_phi_out <= call_i_i720_phi_fu_158;

    call_i_i720_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            call_i_i720_phi_out_ap_vld <= ap_const_logic_1;
        else 
            call_i_i720_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    grp_hw_AES_fu_243_key_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_CS_fsm_state2, hw_S_6_i, hw_S_3_load_reg_966)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_hw_AES_fu_243_key <= hw_S_3_load_reg_966;
        elsif (((icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_hw_AES_fu_243_key <= hw_S_6_i;
        else 
            grp_hw_AES_fu_243_key <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_hw_AES_fu_243_state_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_CS_fsm_state2, hw_S_2_i, hw_S_4_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_hw_AES_fu_243_state <= hw_S_4_i;
        elsif (((icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_hw_AES_fu_243_state <= hw_S_2_i;
        else 
            grp_hw_AES_fu_243_state <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_hw_AES_fu_246_key_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_CS_fsm_state2, hw_S_0_i, hw_S_4_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_hw_AES_fu_246_key <= hw_S_4_i;
        elsif (((icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_hw_AES_fu_246_key <= hw_S_0_i;
        else 
            grp_hw_AES_fu_246_key <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_hw_AES_fu_246_state_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_CS_fsm_state2, hw_S_1_i, hw_S_5_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_hw_AES_fu_246_state <= hw_S_5_i;
        elsif (((icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_hw_AES_fu_246_state <= hw_S_1_i;
        else 
            grp_hw_AES_fu_246_state <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_hw_AES_fu_955_p_din1 <= grp_hw_AES_fu_243_state;
    grp_hw_AES_fu_955_p_din2 <= grp_hw_AES_fu_243_key;
    grp_hw_AES_fu_960_p_din1 <= grp_hw_AES_fu_246_state;
    grp_hw_AES_fu_960_p_din2 <= grp_hw_AES_fu_246_key;

    hw_S_0_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, hw_S_0_i, xor_ln234_fu_771_p2)
    begin
        if (((icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            hw_S_0_o <= xor_ln234_fu_771_p2;
        else 
            hw_S_0_o <= hw_S_0_i;
        end if; 
    end process;


    hw_S_0_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            hw_S_0_o_ap_vld <= ap_const_logic_1;
        else 
            hw_S_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    hw_S_1_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, hw_S_1_i, tmp_s_hw_AES_fu_970_p_dout0)
    begin
        if (((icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            hw_S_1_o <= tmp_s_hw_AES_fu_970_p_dout0;
        else 
            hw_S_1_o <= hw_S_1_i;
        end if; 
    end process;


    hw_S_1_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            hw_S_1_o_ap_vld <= ap_const_logic_1;
        else 
            hw_S_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    hw_S_2_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, hw_S_2_i, grp_hw_AES_fu_960_p_dout0)
    begin
        if (((icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            hw_S_2_o <= grp_hw_AES_fu_960_p_dout0;
        else 
            hw_S_2_o <= hw_S_2_i;
        end if; 
    end process;


    hw_S_2_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            hw_S_2_o_ap_vld <= ap_const_logic_1;
        else 
            hw_S_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    hw_S_3_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, hw_S_3_i, grp_hw_AES_fu_955_p_dout0)
    begin
        if (((icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            hw_S_3_o <= grp_hw_AES_fu_955_p_dout0;
        else 
            hw_S_3_o <= hw_S_3_i;
        end if; 
    end process;


    hw_S_3_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            hw_S_3_o_ap_vld <= ap_const_logic_1;
        else 
            hw_S_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    hw_S_4_o_assign_proc : process(ap_CS_fsm_state2, hw_S_4_i, tmp_13_reg_356)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hw_S_4_o <= tmp_13_reg_356;
        else 
            hw_S_4_o <= hw_S_4_i;
        end if; 
    end process;


    hw_S_4_o_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hw_S_4_o_ap_vld <= ap_const_logic_1;
        else 
            hw_S_4_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    hw_S_5_o_assign_proc : process(ap_CS_fsm_state2, hw_S_5_i, grp_hw_AES_fu_955_p_dout0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hw_S_5_o <= grp_hw_AES_fu_955_p_dout0;
        else 
            hw_S_5_o <= hw_S_5_i;
        end if; 
    end process;


    hw_S_5_o_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hw_S_5_o_ap_vld <= ap_const_logic_1;
        else 
            hw_S_5_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    hw_S_6_o_assign_proc : process(ap_CS_fsm_state2, hw_S_6_i, grp_hw_AES_fu_960_p_dout0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hw_S_6_o <= grp_hw_AES_fu_960_p_dout0;
        else 
            hw_S_6_o <= hw_S_6_i;
        end if; 
    end process;


    hw_S_6_o_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            hw_S_6_o_ap_vld <= ap_const_logic_1;
        else 
            hw_S_6_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    i_8_fu_381_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_7) + unsigned(ap_const_lv5_1));
    icmp_ln311_fu_375_p2 <= "1" when (ap_sig_allocacmp_i_7 = ap_const_lv5_10) else "0";
    num_10_i1_fu_674_p4 <= val_3(87 downto 80);
    num_10_i_fu_487_p4 <= val_1(87 downto 80);
    num_11_i1_fu_654_p4 <= val_3(95 downto 88);
    num_11_i_fu_467_p4 <= val_1(95 downto 88);
    num_12_i8_fu_634_p4 <= val_3(103 downto 96);
    num_12_i_fu_447_p4 <= val_1(103 downto 96);
    num_13_i6_fu_614_p4 <= val_3(111 downto 104);
    num_13_i_fu_427_p4 <= val_1(111 downto 104);
    num_14_i4_fu_594_p4 <= val_3(119 downto 112);
    num_14_i_fu_407_p4 <= val_1(119 downto 112);
    num_1_i3_fu_584_p4 <= val_3(15 downto 8);
    num_1_i_fu_397_p4 <= val_1(15 downto 8);
    num_2_i5_fu_604_p4 <= val_3(23 downto 16);
    num_2_i_fu_417_p4 <= val_1(23 downto 16);
    num_3_i7_fu_624_p4 <= val_3(31 downto 24);
    num_3_i_fu_437_p4 <= val_1(31 downto 24);
    num_4_i9_fu_644_p4 <= val_3(39 downto 32);
    num_4_i_fu_457_p4 <= val_1(39 downto 32);
    num_5_i1_fu_664_p4 <= val_3(47 downto 40);
    num_5_i_fu_477_p4 <= val_1(47 downto 40);
    num_6_i1_fu_684_p4 <= val_3(55 downto 48);
    num_6_i_fu_497_p4 <= val_1(55 downto 48);
    num_7_i1_fu_704_p4 <= val_3(63 downto 56);
    num_7_i_fu_517_p4 <= val_1(63 downto 56);
    num_8_i1_fu_714_p4 <= val_3(71 downto 64);
    num_8_i_fu_527_p4 <= val_1(71 downto 64);
    num_9_i1_fu_694_p4 <= val_3(79 downto 72);
    num_9_i_fu_507_p4 <= val_1(79 downto 72);
    num_i2_fu_574_p4 <= val_3(127 downto 120);
    num_i_fu_387_p4 <= val_1(127 downto 120);
    out_1_fu_724_p17 <= (((((((((((((((trunc_ln322_1 & num_1_i3_fu_584_p4) & num_2_i5_fu_604_p4) & num_3_i7_fu_624_p4) & num_4_i9_fu_644_p4) & num_5_i1_fu_664_p4) & num_6_i1_fu_684_p4) & num_7_i1_fu_704_p4) & num_8_i1_fu_714_p4) & num_9_i1_fu_694_p4) & num_10_i1_fu_674_p4) & num_11_i1_fu_654_p4) & num_12_i8_fu_634_p4) & num_13_i6_fu_614_p4) & num_14_i4_fu_594_p4) & num_i2_fu_574_p4);
    out_fu_537_p17 <= (((((((((((((((trunc_ln & num_1_i_fu_397_p4) & num_2_i_fu_417_p4) & num_3_i_fu_437_p4) & num_4_i_fu_457_p4) & num_5_i_fu_477_p4) & num_6_i_fu_497_p4) & num_7_i_fu_517_p4) & num_8_i_fu_527_p4) & num_9_i_fu_507_p4) & num_10_i_fu_487_p4) & num_11_i_fu_467_p4) & num_12_i_fu_447_p4) & num_13_i_fu_427_p4) & num_14_i_fu_407_p4) & num_i_fu_387_p4);
    tmp_13_hw_AES_fu_965_p_din1 <= hw_S_3_i;
    tmp_13_hw_AES_fu_965_p_din2 <= out_1_fu_724_p17;
    tmp_s_hw_AES_fu_970_p_din1 <= hw_S_0_i;
    tmp_s_hw_AES_fu_970_p_din2 <= out_fu_537_p17;
    xor_i_i719_phi_out <= xor_i_i719_phi_fu_162;

    xor_i_i719_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln311_fu_375_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln311_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xor_i_i719_phi_out_ap_vld <= ap_const_logic_1;
        else 
            xor_i_i719_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln234_fu_771_p2 <= (hw_S_6_i xor hw_S_1_i);
end behav;
