-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Rocca_S_hw_v2_convert_endian_128_hw is
port (
    ap_ready : OUT STD_LOGIC;
    val_r : IN STD_LOGIC_VECTOR (127 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of Rocca_S_hw_v2_convert_endian_128_hw is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_43 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000011";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001011";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010011";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011011";
    constant ap_const_lv32_5C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011100";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101011";
    constant ap_const_lv32_6C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101100";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_73 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110011";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111011";
    constant ap_const_lv32_7C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111100";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal trunc_ln86_fu_158_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_148_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln_fu_138_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_3_fu_162_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_4_fu_172_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_5_fu_182_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_6_fu_192_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_7_fu_202_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_8_fu_212_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_9_fu_222_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_s_fu_232_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_10_fu_242_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_11_fu_252_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_12_fu_262_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_13_fu_272_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_14_fu_282_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_15_fu_292_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_16_fu_302_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_17_fu_312_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_18_fu_322_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_19_fu_332_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_20_fu_342_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_21_fu_352_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_22_fu_362_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_23_fu_372_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_24_fu_382_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_25_fu_392_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_26_fu_402_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln83_1_fu_412_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_1_fu_422_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_2_fu_432_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal val_assign_s_fu_442_p4 : STD_LOGIC_VECTOR (3 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= (((((((((((((((((((((((((((((((trunc_ln86_fu_158_p1 & tmp_fu_148_p4) & trunc_ln_fu_138_p4) & trunc_ln86_3_fu_162_p4) & trunc_ln86_4_fu_172_p4) & trunc_ln86_5_fu_182_p4) & trunc_ln86_6_fu_192_p4) & trunc_ln86_7_fu_202_p4) & trunc_ln86_8_fu_212_p4) & trunc_ln86_9_fu_222_p4) & trunc_ln86_s_fu_232_p4) & trunc_ln86_10_fu_242_p4) & trunc_ln86_11_fu_252_p4) & trunc_ln86_12_fu_262_p4) & trunc_ln86_13_fu_272_p4) & trunc_ln86_14_fu_282_p4) & trunc_ln86_15_fu_292_p4) & trunc_ln86_16_fu_302_p4) & trunc_ln86_17_fu_312_p4) & trunc_ln86_18_fu_322_p4) & trunc_ln86_19_fu_332_p4) & trunc_ln86_20_fu_342_p4) & trunc_ln86_21_fu_352_p4) & trunc_ln86_22_fu_362_p4) & trunc_ln86_23_fu_372_p4) & trunc_ln86_24_fu_382_p4) & trunc_ln86_25_fu_392_p4) & trunc_ln86_26_fu_402_p4) & trunc_ln83_1_fu_412_p4) & trunc_ln86_1_fu_422_p4) & trunc_ln86_2_fu_432_p4) & val_assign_s_fu_442_p4);
    tmp_fu_148_p4 <= val_r(7 downto 4);
    trunc_ln83_1_fu_412_p4 <= val_r(115 downto 112);
    trunc_ln86_10_fu_242_p4 <= val_r(47 downto 44);
    trunc_ln86_11_fu_252_p4 <= val_r(51 downto 48);
    trunc_ln86_12_fu_262_p4 <= val_r(55 downto 52);
    trunc_ln86_13_fu_272_p4 <= val_r(59 downto 56);
    trunc_ln86_14_fu_282_p4 <= val_r(63 downto 60);
    trunc_ln86_15_fu_292_p4 <= val_r(67 downto 64);
    trunc_ln86_16_fu_302_p4 <= val_r(71 downto 68);
    trunc_ln86_17_fu_312_p4 <= val_r(75 downto 72);
    trunc_ln86_18_fu_322_p4 <= val_r(79 downto 76);
    trunc_ln86_19_fu_332_p4 <= val_r(83 downto 80);
    trunc_ln86_1_fu_422_p4 <= val_r(119 downto 116);
    trunc_ln86_20_fu_342_p4 <= val_r(87 downto 84);
    trunc_ln86_21_fu_352_p4 <= val_r(91 downto 88);
    trunc_ln86_22_fu_362_p4 <= val_r(95 downto 92);
    trunc_ln86_23_fu_372_p4 <= val_r(99 downto 96);
    trunc_ln86_24_fu_382_p4 <= val_r(103 downto 100);
    trunc_ln86_25_fu_392_p4 <= val_r(107 downto 104);
    trunc_ln86_26_fu_402_p4 <= val_r(111 downto 108);
    trunc_ln86_2_fu_432_p4 <= val_r(123 downto 120);
    trunc_ln86_3_fu_162_p4 <= val_r(15 downto 12);
    trunc_ln86_4_fu_172_p4 <= val_r(19 downto 16);
    trunc_ln86_5_fu_182_p4 <= val_r(23 downto 20);
    trunc_ln86_6_fu_192_p4 <= val_r(27 downto 24);
    trunc_ln86_7_fu_202_p4 <= val_r(31 downto 28);
    trunc_ln86_8_fu_212_p4 <= val_r(35 downto 32);
    trunc_ln86_9_fu_222_p4 <= val_r(39 downto 36);
    trunc_ln86_fu_158_p1 <= val_r(4 - 1 downto 0);
    trunc_ln86_s_fu_232_p4 <= val_r(43 downto 40);
    trunc_ln_fu_138_p4 <= val_r(11 downto 8);
    val_assign_s_fu_442_p4 <= val_r(127 downto 124);
end behav;
