// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GCM_AE_HW_1x22_GHASH (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hash_payload_0_address0,
        hash_payload_0_ce0,
        hash_payload_0_q0,
        hash_payload_1_address0,
        hash_payload_1_ce0,
        hash_payload_1_q0,
        hash_payload_2_address0,
        hash_payload_2_ce0,
        hash_payload_2_q0,
        hash_payload_3_address0,
        hash_payload_3_ce0,
        hash_payload_3_q0,
        hblock_len,
        H_matrix_1,
        H_matrix_0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] hash_payload_0_address0;
output   hash_payload_0_ce0;
input  [127:0] hash_payload_0_q0;
output  [7:0] hash_payload_1_address0;
output   hash_payload_1_ce0;
input  [127:0] hash_payload_1_q0;
output  [7:0] hash_payload_2_address0;
output   hash_payload_2_ce0;
input  [127:0] hash_payload_2_q0;
output  [7:0] hash_payload_3_address0;
output   hash_payload_3_ce0;
input  [127:0] hash_payload_3_q0;
input  [25:0] hblock_len;
input  [127:0] H_matrix_1;
input  [127:0] H_matrix_0;
output  [127:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] hash_payload_0_address0;
reg hash_payload_0_ce0;
reg[7:0] hash_payload_1_address0;
reg hash_payload_1_ce0;
reg[7:0] hash_payload_2_address0;
reg hash_payload_2_ce0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [127:0] reg_183;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state15;
reg   [127:0] reg_189;
wire   [24:0] no_block_ops_Q_fu_195_p4;
reg   [24:0] no_block_ops_Q_reg_284;
wire   [0:0] ret_V_fu_205_p1;
reg   [0:0] ret_V_reg_289;
wire   [0:0] icmp_ln1035_fu_209_p2;
reg   [0:0] icmp_ln1035_reg_294;
wire   [127:0] ret_V_139_fu_223_p2;
wire    ap_CS_fsm_state14;
reg   [0:0] tmp_reg_314;
reg   [127:0] hash_payload_2_load_reg_334;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_done;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_idle;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_ready;
wire   [7:0] grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_0_address0;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_0_ce0;
wire   [7:0] grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_2_address0;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_2_ce0;
wire   [7:0] grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_1_address0;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_1_ce0;
wire   [7:0] grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_3_address0;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_3_ce0;
wire   [127:0] grp_GHASH_Pipeline_Q_calc_loop_fu_133_H1_operand_V_1_0_out;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_H1_operand_V_1_0_out_ap_vld;
wire   [127:0] grp_GHASH_Pipeline_Q_calc_loop_fu_133_H2_operand_V_1_0_out;
wire    grp_GHASH_Pipeline_Q_calc_loop_fu_133_H2_operand_V_1_0_out_ap_vld;
wire   [127:0] grp_GHASH_H2_fu_152_ap_return;
reg    grp_GHASH_H2_fu_152_ap_ce;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg   [127:0] grp_GHASH_H1_fu_159_X;
reg   [127:0] grp_GHASH_H1_fu_159_H_matrix_0;
wire   [127:0] grp_GHASH_H1_fu_159_ap_return;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_done;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_idle;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_ready;
wire   [127:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_166_X_V_out;
wire    grp_GHASH_Pipeline_Remainder_R_loop_fu_166_X_V_out_ap_vld;
wire   [127:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_166_grp_GHASH_H1_fu_159_p_din1;
wire   [127:0] grp_GHASH_Pipeline_Remainder_R_loop_fu_166_grp_GHASH_H1_fu_159_p_din2;
reg   [127:0] agg_result_0_reg_121;
reg    grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start_reg;
reg    grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start_reg;
wire   [63:0] zext_ln749_fu_245_p1;
wire   [7:0] lshr_ln1_fu_236_p4;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start_reg = 1'b0;
#0 grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start_reg = 1'b0;
end

GCM_AE_HW_1x22_GHASH_Pipeline_Q_calc_loop grp_GHASH_Pipeline_Q_calc_loop_fu_133(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start),
    .ap_done(grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_done),
    .ap_idle(grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_idle),
    .ap_ready(grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_ready),
    .X2_V(reg_189),
    .X1_V(reg_183),
    .no_block_ops_Q(no_block_ops_Q_reg_284),
    .hash_payload_0_address0(grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_0_address0),
    .hash_payload_0_ce0(grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_0_ce0),
    .hash_payload_0_q0(hash_payload_0_q0),
    .hash_payload_2_address0(grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_2_address0),
    .hash_payload_2_ce0(grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_2_ce0),
    .hash_payload_2_q0(hash_payload_2_q0),
    .hash_payload_1_address0(grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_1_address0),
    .hash_payload_1_ce0(grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_1_ce0),
    .hash_payload_1_q0(hash_payload_1_q0),
    .hash_payload_3_address0(grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_3_address0),
    .hash_payload_3_ce0(grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_3_ce0),
    .hash_payload_3_q0(hash_payload_3_q0),
    .H1_operand_V_1_0_out(grp_GHASH_Pipeline_Q_calc_loop_fu_133_H1_operand_V_1_0_out),
    .H1_operand_V_1_0_out_ap_vld(grp_GHASH_Pipeline_Q_calc_loop_fu_133_H1_operand_V_1_0_out_ap_vld),
    .H2_operand_V_1_0_out(grp_GHASH_Pipeline_Q_calc_loop_fu_133_H2_operand_V_1_0_out),
    .H2_operand_V_1_0_out_ap_vld(grp_GHASH_Pipeline_Q_calc_loop_fu_133_H2_operand_V_1_0_out_ap_vld),
    .H_matrix_1(H_matrix_1)
);

GCM_AE_HW_1x22_GHASH_H2 grp_GHASH_H2_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(grp_GHASH_Pipeline_Q_calc_loop_fu_133_H2_operand_V_1_0_out),
    .H_matrix_1(H_matrix_1),
    .ap_return(grp_GHASH_H2_fu_152_ap_return),
    .ap_ce(grp_GHASH_H2_fu_152_ap_ce)
);

GCM_AE_HW_1x22_GHASH_H1 grp_GHASH_H1_fu_159(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .X(grp_GHASH_H1_fu_159_X),
    .H_matrix_0(grp_GHASH_H1_fu_159_H_matrix_0),
    .ap_return(grp_GHASH_H1_fu_159_ap_return)
);

GCM_AE_HW_1x22_GHASH_Pipeline_Remainder_R_loop grp_GHASH_Pipeline_Remainder_R_loop_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start),
    .ap_done(grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_done),
    .ap_idle(grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_idle),
    .ap_ready(grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_ready),
    .agg_result_0(agg_result_0_reg_121),
    .ret_V(ret_V_reg_289),
    .tmp(tmp_reg_314),
    .hash_payload_0_load_1(reg_183),
    .hash_payload_1_load_1(reg_189),
    .hash_payload_2_load_1(hash_payload_2_load_reg_334),
    .X_V_out(grp_GHASH_Pipeline_Remainder_R_loop_fu_166_X_V_out),
    .X_V_out_ap_vld(grp_GHASH_Pipeline_Remainder_R_loop_fu_166_X_V_out_ap_vld),
    .H_matrix_0(H_matrix_0),
    .grp_GHASH_H1_fu_159_p_din1(grp_GHASH_Pipeline_Remainder_R_loop_fu_166_grp_GHASH_H1_fu_159_p_din1),
    .grp_GHASH_H1_fu_159_p_din2(grp_GHASH_Pipeline_Remainder_R_loop_fu_166_grp_GHASH_H1_fu_159_p_din2),
    .grp_GHASH_H1_fu_159_p_dout0(grp_GHASH_H1_fu_159_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start_reg <= 1'b1;
        end else if ((grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_ready == 1'b1)) begin
            grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start_reg <= 1'b1;
        end else if ((grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_ready == 1'b1)) begin
            grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1035_fu_209_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        agg_result_0_reg_121 <= 128'd0;
    end else if (((icmp_ln1035_reg_294 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        agg_result_0_reg_121 <= ret_V_139_fu_223_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        hash_payload_2_load_reg_334 <= hash_payload_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln1035_reg_294 <= icmp_ln1035_fu_209_p2;
        no_block_ops_Q_reg_284 <= {{hblock_len[25:1]}};
        ret_V_reg_289 <= ret_V_fu_205_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_183 <= hash_payload_0_q0;
        reg_189 <= hash_payload_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_reg_314 <= hblock_len[32'd1];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_GHASH_H1_fu_159_H_matrix_0 = grp_GHASH_Pipeline_Remainder_R_loop_fu_166_grp_GHASH_H1_fu_159_p_din2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_GHASH_H1_fu_159_H_matrix_0 = H_matrix_0;
    end else begin
        grp_GHASH_H1_fu_159_H_matrix_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_GHASH_H1_fu_159_X = grp_GHASH_Pipeline_Remainder_R_loop_fu_166_grp_GHASH_H1_fu_159_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_GHASH_H1_fu_159_X = grp_GHASH_Pipeline_Q_calc_loop_fu_133_H1_operand_V_1_0_out;
    end else begin
        grp_GHASH_H1_fu_159_X = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_GHASH_H2_fu_152_ap_ce = 1'b0;
    end else begin
        grp_GHASH_H2_fu_152_ap_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hash_payload_0_address0 = zext_ln749_fu_245_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        hash_payload_0_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_0_address0 = grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_0_address0;
    end else begin
        hash_payload_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        hash_payload_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_0_ce0 = grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_0_ce0;
    end else begin
        hash_payload_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hash_payload_1_address0 = zext_ln749_fu_245_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        hash_payload_1_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_1_address0 = grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_1_address0;
    end else begin
        hash_payload_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        hash_payload_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_1_ce0 = grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_1_ce0;
    end else begin
        hash_payload_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hash_payload_2_address0 = zext_ln749_fu_245_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_2_address0 = grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_2_address0;
    end else begin
        hash_payload_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        hash_payload_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hash_payload_2_ce0 = grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_2_ce0;
    end else begin
        hash_payload_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln1035_fu_209_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((icmp_ln1035_fu_209_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return = grp_GHASH_Pipeline_Remainder_R_loop_fu_166_X_V_out;

assign grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start = grp_GHASH_Pipeline_Q_calc_loop_fu_133_ap_start_reg;

assign grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start = grp_GHASH_Pipeline_Remainder_R_loop_fu_166_ap_start_reg;

assign hash_payload_3_address0 = grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_3_address0;

assign hash_payload_3_ce0 = grp_GHASH_Pipeline_Q_calc_loop_fu_133_hash_payload_3_ce0;

assign icmp_ln1035_fu_209_p2 = ((no_block_ops_Q_fu_195_p4 == 25'd0) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_236_p4 = {{hblock_len[9:2]}};

assign no_block_ops_Q_fu_195_p4 = {{hblock_len[25:1]}};

assign ret_V_139_fu_223_p2 = (grp_GHASH_H2_fu_152_ap_return ^ grp_GHASH_H1_fu_159_ap_return);

assign ret_V_fu_205_p1 = hblock_len[0:0];

assign zext_ln749_fu_245_p1 = lshr_ln1_fu_236_p4;

endmodule //GCM_AE_HW_1x22_GHASH
