// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_message_reading (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_TVALID,
        temp_V_13_reload,
        trunc_ln2,
        input_r_TDATA,
        input_r_TREADY,
        input_r_TKEEP,
        input_r_TSTRB,
        input_r_TLAST,
        temp_V_14_out,
        temp_V_14_out_ap_vld,
        hw_M_0_address0,
        hw_M_0_ce0,
        hw_M_0_we0,
        hw_M_0_d0,
        hw_M_1_address0,
        hw_M_1_ce0,
        hw_M_1_we0,
        hw_M_1_d0,
        grp_convert_endian_128_hw_fu_331_p_din1,
        grp_convert_endian_128_hw_fu_331_p_dout0,
        grp_convert_endian_128_hw_fu_331_p_ready
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   input_r_TVALID;
input  [511:0] temp_V_13_reload;
input  [120:0] trunc_ln2;
input  [511:0] input_r_TDATA;
output   input_r_TREADY;
input  [63:0] input_r_TKEEP;
input  [63:0] input_r_TSTRB;
input  [0:0] input_r_TLAST;
output  [511:0] temp_V_14_out;
output   temp_V_14_out_ap_vld;
output  [8:0] hw_M_0_address0;
output   hw_M_0_ce0;
output   hw_M_0_we0;
output  [127:0] hw_M_0_d0;
output  [8:0] hw_M_1_address0;
output   hw_M_1_ce0;
output   hw_M_1_we0;
output  [127:0] hw_M_1_d0;
output  [127:0] grp_convert_endian_128_hw_fu_331_p_din1;
input  [127:0] grp_convert_endian_128_hw_fu_331_p_dout0;
input   grp_convert_endian_128_hw_fu_331_p_ready;

reg ap_idle;
reg input_r_TREADY;
reg temp_V_14_out_ap_vld;
reg[8:0] hw_M_0_address0;
reg hw_M_0_ce0;
reg hw_M_0_we0;
reg[8:0] hw_M_1_address0;
reg hw_M_1_ce0;
reg hw_M_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln411_fu_207_p2;
wire   [0:0] icmp_ln415_fu_234_p2;
reg    ap_predicate_op30_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_r_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [127:0] grp_convert_endian_128_hw_fu_169_val_r;
wire   [127:0] val_2_fu_244_p1;
wire   [127:0] inp_V_fu_286_p1;
wire   [63:0] zext_ln423_fu_249_p1;
wire   [63:0] zext_ln416_fu_291_p1;
reg   [31:0] pos_fu_84;
wire   [31:0] pos_2_fu_301_p2;
wire    ap_loop_init;
reg   [120:0] i_fu_88;
wire   [120:0] i_2_fu_212_p2;
reg   [511:0] p_Val2_s_fu_92;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] trunc_ln423_fu_255_p1;
wire   [0:0] trunc_ln416_fu_297_p1;
wire   [31:0] add_ln415_fu_218_p2;
wire   [22:0] tmp_fu_224_p4;
wire   [8:0] grp_fu_176_p4;
wire   [8:0] trunc_ln628_fu_272_p1;
wire   [511:0] zext_ln628_fu_276_p1;
wire   [511:0] lshr_ln628_fu_280_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_277;
reg    ap_condition_285;
reg    ap_condition_288;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

Rocca_S_hw_v2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_88 <= 121'd0;
        end else if (((icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_88 <= i_2_fu_212_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_Val2_s_fu_92 <= temp_V_13_reload;
        end else if ((1'b1 == ap_condition_285)) begin
            p_Val2_s_fu_92 <= input_r_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            pos_fu_84 <= 32'd512;
        end else if ((1'b1 == ap_condition_288)) begin
            pos_fu_84 <= pos_2_fu_301_p2;
        end else if ((1'b1 == ap_condition_285)) begin
            pos_fu_84 <= 32'd128;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln411_fu_207_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_277)) begin
        if ((icmp_ln415_fu_234_p2 == 1'd1)) begin
            grp_convert_endian_128_hw_fu_169_val_r = inp_V_fu_286_p1;
        end else if ((icmp_ln415_fu_234_p2 == 1'd0)) begin
            grp_convert_endian_128_hw_fu_169_val_r = val_2_fu_244_p1;
        end else begin
            grp_convert_endian_128_hw_fu_169_val_r = 'bx;
        end
    end else begin
        grp_convert_endian_128_hw_fu_169_val_r = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_277)) begin
        if (((icmp_ln415_fu_234_p2 == 1'd1) & (trunc_ln416_fu_297_p1 == 1'd0))) begin
            hw_M_0_address0 = zext_ln416_fu_291_p1;
        end else if (((icmp_ln415_fu_234_p2 == 1'd0) & (trunc_ln423_fu_255_p1 == 1'd0))) begin
            hw_M_0_address0 = zext_ln423_fu_249_p1;
        end else begin
            hw_M_0_address0 = 'bx;
        end
    end else begin
        hw_M_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln415_fu_234_p2 == 1'd0) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln423_fu_255_p1 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln415_fu_234_p2 == 1'd1) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln416_fu_297_p1 == 1'd0)))) begin
        hw_M_0_ce0 = 1'b1;
    end else begin
        hw_M_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln415_fu_234_p2 == 1'd0) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln423_fu_255_p1 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln415_fu_234_p2 == 1'd1) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln416_fu_297_p1 == 1'd0)))) begin
        hw_M_0_we0 = 1'b1;
    end else begin
        hw_M_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_277)) begin
        if (((icmp_ln415_fu_234_p2 == 1'd1) & (trunc_ln416_fu_297_p1 == 1'd1))) begin
            hw_M_1_address0 = zext_ln416_fu_291_p1;
        end else if (((icmp_ln415_fu_234_p2 == 1'd0) & (trunc_ln423_fu_255_p1 == 1'd1))) begin
            hw_M_1_address0 = zext_ln423_fu_249_p1;
        end else begin
            hw_M_1_address0 = 'bx;
        end
    end else begin
        hw_M_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln415_fu_234_p2 == 1'd0) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln423_fu_255_p1 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln415_fu_234_p2 == 1'd1) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln416_fu_297_p1 == 1'd1)))) begin
        hw_M_1_ce0 = 1'b1;
    end else begin
        hw_M_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln415_fu_234_p2 == 1'd0) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln423_fu_255_p1 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln415_fu_234_p2 == 1'd1) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln416_fu_297_p1 == 1'd1)))) begin
        hw_M_1_we0 = 1'b1;
    end else begin
        hw_M_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op30_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_TDATA_blk_n = input_r_TVALID;
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op30_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_TREADY = 1'b1;
    end else begin
        input_r_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln411_fu_207_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_V_14_out_ap_vld = 1'b1;
    end else begin
        temp_V_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln415_fu_218_p2 = (pos_fu_84 + 32'd127);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_predicate_op30_read_state2 == 1'b1) & (input_r_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_predicate_op30_read_state2 == 1'b1) & (input_r_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_predicate_op30_read_state2 == 1'b1) & (input_r_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op30_read_state2 == 1'b1) & (input_r_TVALID == 1'b0));
end

always @ (*) begin
    ap_condition_277 = ((1'b0 == ap_block_pp0_stage0) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_285 = ((icmp_ln415_fu_234_p2 == 1'd0) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_288 = ((icmp_ln415_fu_234_p2 == 1'd1) & (icmp_ln411_fu_207_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op30_read_state2 = ((icmp_ln415_fu_234_p2 == 1'd0) & (icmp_ln411_fu_207_p2 == 1'd0));
end

assign grp_convert_endian_128_hw_fu_331_p_din1 = grp_convert_endian_128_hw_fu_169_val_r;

assign grp_fu_176_p4 = {{i_fu_88[9:1]}};

assign hw_M_0_d0 = grp_convert_endian_128_hw_fu_331_p_dout0;

assign hw_M_1_d0 = grp_convert_endian_128_hw_fu_331_p_dout0;

assign i_2_fu_212_p2 = (i_fu_88 + 121'd1);

assign icmp_ln411_fu_207_p2 = ((i_fu_88 == trunc_ln2) ? 1'b1 : 1'b0);

assign icmp_ln415_fu_234_p2 = (($signed(tmp_fu_224_p4) < $signed(23'd1)) ? 1'b1 : 1'b0);

assign inp_V_fu_286_p1 = lshr_ln628_fu_280_p2[127:0];

assign lshr_ln628_fu_280_p2 = p_Val2_s_fu_92 >> zext_ln628_fu_276_p1;

assign pos_2_fu_301_p2 = (pos_fu_84 + 32'd128);

assign temp_V_14_out = p_Val2_s_fu_92;

assign tmp_fu_224_p4 = {{add_ln415_fu_218_p2[31:9]}};

assign trunc_ln416_fu_297_p1 = i_fu_88[0:0];

assign trunc_ln423_fu_255_p1 = i_fu_88[0:0];

assign trunc_ln628_fu_272_p1 = pos_fu_84[8:0];

assign val_2_fu_244_p1 = input_r_TDATA[127:0];

assign zext_ln416_fu_291_p1 = grp_fu_176_p4;

assign zext_ln423_fu_249_p1 = grp_fu_176_p4;

assign zext_ln628_fu_276_p1 = trunc_ln628_fu_272_p1;

endmodule //Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_message_reading
