// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_VITIS_LOOP_298_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        call_i_i690757_reload,
        call2_i_i691761_reload,
        call10_i_i695755_reload,
        call6_i_i693765_reload,
        xor_i_i689759_reload,
        call8_i_i694767_reload,
        call4_i_i692763_reload,
        trunc_ln2,
        call_i_i709809_out,
        call_i_i709809_out_ap_vld,
        call2_i_i710807_out,
        call2_i_i710807_out_ap_vld,
        call10_i_i714805_out,
        call10_i_i714805_out_ap_vld,
        call6_i_i712803_out,
        call6_i_i712803_out_ap_vld,
        xor_i_i708801_out,
        xor_i_i708801_out_ap_vld,
        call8_i_i713799_out,
        call8_i_i713799_out_ap_vld,
        call4_i_i711797_out,
        call4_i_i711797_out_ap_vld,
        hw_M_0_address0,
        hw_M_0_ce0,
        hw_M_0_q0,
        hw_C_0_address0,
        hw_C_0_ce0,
        hw_C_0_we0,
        hw_C_0_d0,
        hw_M_1_address0,
        hw_M_1_ce0,
        hw_M_1_q0,
        hw_C_1_address0,
        hw_C_1_ce0,
        hw_C_1_we0,
        hw_C_1_d0,
        grp_hw_AES_fu_1690_p_din1,
        grp_hw_AES_fu_1690_p_din2,
        grp_hw_AES_fu_1690_p_dout0,
        grp_hw_AES_fu_1690_p_ce,
        grp_hw_AES_fu_1690_p_start,
        grp_hw_AES_fu_1690_p_ready,
        grp_hw_AES_fu_1690_p_done,
        grp_hw_AES_fu_1690_p_idle
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] call_i_i690757_reload;
input  [127:0] call2_i_i691761_reload;
input  [127:0] call10_i_i695755_reload;
input  [127:0] call6_i_i693765_reload;
input  [127:0] xor_i_i689759_reload;
input  [127:0] call8_i_i694767_reload;
input  [127:0] call4_i_i692763_reload;
input  [120:0] trunc_ln2;
output  [127:0] call_i_i709809_out;
output   call_i_i709809_out_ap_vld;
output  [127:0] call2_i_i710807_out;
output   call2_i_i710807_out_ap_vld;
output  [127:0] call10_i_i714805_out;
output   call10_i_i714805_out_ap_vld;
output  [127:0] call6_i_i712803_out;
output   call6_i_i712803_out_ap_vld;
output  [127:0] xor_i_i708801_out;
output   xor_i_i708801_out_ap_vld;
output  [127:0] call8_i_i713799_out;
output   call8_i_i713799_out_ap_vld;
output  [127:0] call4_i_i711797_out;
output   call4_i_i711797_out_ap_vld;
output  [8:0] hw_M_0_address0;
output   hw_M_0_ce0;
input  [127:0] hw_M_0_q0;
output  [8:0] hw_C_0_address0;
output   hw_C_0_ce0;
output   hw_C_0_we0;
output  [127:0] hw_C_0_d0;
output  [8:0] hw_M_1_address0;
output   hw_M_1_ce0;
input  [127:0] hw_M_1_q0;
output  [8:0] hw_C_1_address0;
output   hw_C_1_ce0;
output   hw_C_1_we0;
output  [127:0] hw_C_1_d0;
output  [127:0] grp_hw_AES_fu_1690_p_din1;
output  [127:0] grp_hw_AES_fu_1690_p_din2;
input  [127:0] grp_hw_AES_fu_1690_p_dout0;
output   grp_hw_AES_fu_1690_p_ce;
output   grp_hw_AES_fu_1690_p_start;
input   grp_hw_AES_fu_1690_p_ready;
input   grp_hw_AES_fu_1690_p_done;
input   grp_hw_AES_fu_1690_p_idle;

reg ap_idle;
reg call_i_i709809_out_ap_vld;
reg call2_i_i710807_out_ap_vld;
reg call10_i_i714805_out_ap_vld;
reg call6_i_i712803_out_ap_vld;
reg xor_i_i708801_out_ap_vld;
reg call8_i_i713799_out_ap_vld;
reg call4_i_i711797_out_ap_vld;
reg hw_M_0_ce0;
reg hw_C_0_ce0;
reg hw_C_0_we0;
reg hw_M_1_ce0;
reg hw_C_1_ce0;
reg hw_C_1_we0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state11_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln298_reg_568;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln298_fu_350_p2;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state10_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire   [63:0] zext_ln303_fu_365_p1;
reg   [63:0] zext_ln303_reg_572;
reg   [127:0] call4_i_i711797_load_reg_588;
wire    ap_block_pp0_stage2_11001;
reg   [127:0] call8_i_i713799_load_reg_594;
reg   [127:0] xor_i_i708801_load_1_reg_599;
reg   [127:0] hw_M_0_load_reg_605;
reg   [127:0] hw_M_1_load_reg_611;
reg   [127:0] call6_i_i712803_load_reg_617;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_11001;
reg   [127:0] call10_i_i714805_load_reg_623;
reg   [127:0] call2_i_i710807_load_1_reg_629;
reg    ap_enable_reg_pp0_iter0_reg;
wire    grp_hw_AES_fu_263_ap_ready;
reg   [127:0] grp_hw_AES_fu_263_state;
reg   [127:0] grp_hw_AES_fu_263_key;
reg    grp_hw_AES_fu_263_ap_start_reg;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_11001;
wire    ap_block_pp0_stage7_11001;
wire   [127:0] xor_ln303_fu_392_p2;
wire    ap_block_pp0_stage2;
wire   [127:0] xor_ln304_fu_415_p2;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
reg   [127:0] call4_i_i711797_fu_82;
wire    ap_loop_init;
reg   [127:0] call8_i_i713799_fu_86;
reg   [127:0] xor_i_i708801_fu_90;
wire   [127:0] xor_ln234_fu_432_p2;
reg   [127:0] call6_i_i712803_fu_94;
reg   [127:0] call10_i_i714805_fu_98;
reg   [127:0] call2_i_i710807_fu_102;
reg   [127:0] call_i_i709809_fu_106;
reg   [63:0] i_7_fu_110;
wire   [63:0] add_ln298_fu_371_p2;
wire    ap_block_pp0_stage2_01001;
wire   [120:0] zext_ln298_fu_346_p1;
wire   [8:0] lshr_ln2_fu_355_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_hw_AES_fu_263_ap_start_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

Rocca_S_hw_v2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hw_AES_fu_263_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln298_fu_350_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            grp_hw_AES_fu_263_ap_start_reg <= 1'b1;
        end else if ((grp_hw_AES_fu_263_ap_ready == 1'b1)) begin
            grp_hw_AES_fu_263_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call10_i_i714805_fu_98 <= call10_i_i695755_reload;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        call10_i_i714805_fu_98 <= grp_hw_AES_fu_1690_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call2_i_i710807_fu_102 <= call2_i_i691761_reload;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        call2_i_i710807_fu_102 <= grp_hw_AES_fu_1690_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call4_i_i711797_fu_82 <= call4_i_i692763_reload;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        call4_i_i711797_fu_82 <= grp_hw_AES_fu_1690_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            call6_i_i712803_fu_94 <= call6_i_i693765_reload;
        end else if (((icmp_ln298_reg_568 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            call6_i_i712803_fu_94 <= grp_hw_AES_fu_1690_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call8_i_i713799_fu_86 <= call8_i_i694767_reload;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        call8_i_i713799_fu_86 <= grp_hw_AES_fu_1690_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_i_i709809_fu_106 <= call_i_i690757_reload;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        call_i_i709809_fu_106 <= grp_hw_AES_fu_1690_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_7_fu_110 <= 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln298_fu_350_p2 == 1'd1))) begin
        i_7_fu_110 <= add_ln298_fu_371_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xor_i_i708801_fu_90 <= xor_i_i689759_reload;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        xor_i_i708801_fu_90 <= xor_ln234_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        call10_i_i714805_load_reg_623 <= call10_i_i714805_fu_98;
        call2_i_i710807_load_1_reg_629 <= call2_i_i710807_fu_102;
        call6_i_i712803_load_reg_617 <= call6_i_i712803_fu_94;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        call4_i_i711797_load_reg_588 <= call4_i_i711797_fu_82;
        call8_i_i713799_load_reg_594 <= call8_i_i713799_fu_86;
        hw_M_0_load_reg_605 <= hw_M_0_q0;
        hw_M_1_load_reg_611 <= hw_M_1_q0;
        xor_i_i708801_load_1_reg_599 <= xor_i_i708801_fu_90;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln298_reg_568 <= icmp_ln298_fu_350_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln298_fu_350_p2 == 1'd1))) begin
        zext_ln303_reg_572[8 : 0] <= zext_ln303_fu_365_p1[8 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd0) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        call10_i_i714805_out_ap_vld = 1'b1;
    end else begin
        call10_i_i714805_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        call2_i_i710807_out_ap_vld = 1'b1;
    end else begin
        call2_i_i710807_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        call4_i_i711797_out_ap_vld = 1'b1;
    end else begin
        call4_i_i711797_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        call6_i_i712803_out_ap_vld = 1'b1;
    end else begin
        call6_i_i712803_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        call8_i_i713799_out_ap_vld = 1'b1;
    end else begin
        call8_i_i713799_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        call_i_i709809_out_ap_vld = 1'b1;
    end else begin
        call_i_i709809_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_hw_AES_fu_263_key = call6_i_i712803_load_reg_617;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hw_AES_fu_263_key = call4_i_i711797_load_reg_588;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_hw_AES_fu_263_key = hw_M_1_load_reg_611;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_hw_AES_fu_263_key = call10_i_i714805_load_reg_623;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_hw_AES_fu_263_key = xor_i_i708801_load_1_reg_599;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_hw_AES_fu_263_key = hw_M_0_load_reg_605;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_hw_AES_fu_263_key = call2_i_i710807_fu_102;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_hw_AES_fu_263_key = xor_i_i708801_fu_90;
    end else begin
        grp_hw_AES_fu_263_key = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_hw_AES_fu_263_state = call8_i_i713799_load_reg_594;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hw_AES_fu_263_state = call6_i_i712803_load_reg_617;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_hw_AES_fu_263_state = call4_i_i711797_load_reg_588;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_hw_AES_fu_263_state = call2_i_i710807_load_1_reg_629;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_hw_AES_fu_263_state = call_i_i709809_fu_106;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_hw_AES_fu_263_state = xor_i_i708801_load_1_reg_599;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_hw_AES_fu_263_state = xor_ln304_fu_415_p2;
    end else if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_hw_AES_fu_263_state = xor_ln303_fu_392_p2;
    end else begin
        grp_hw_AES_fu_263_state = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        hw_C_0_ce0 = 1'b1;
    end else begin
        hw_C_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        hw_C_0_we0 = 1'b1;
    end else begin
        hw_C_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        hw_C_1_ce0 = 1'b1;
    end else begin
        hw_C_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd1) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        hw_C_1_we0 = 1'b1;
    end else begin
        hw_C_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hw_M_0_ce0 = 1'b1;
    end else begin
        hw_M_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hw_M_1_ce0 = 1'b1;
    end else begin
        hw_M_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln298_reg_568 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        xor_i_i708801_out_ap_vld = 1'b1;
    end else begin
        xor_i_i708801_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln298_fu_371_p2 = (i_7_fu_110 + 64'd2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign call10_i_i714805_out = call10_i_i714805_fu_98;

assign call2_i_i710807_out = call2_i_i710807_fu_102;

assign call4_i_i711797_out = call4_i_i711797_fu_82;

assign call6_i_i712803_out = call6_i_i712803_fu_94;

assign call8_i_i713799_out = call8_i_i713799_fu_86;

assign call_i_i709809_out = call_i_i709809_fu_106;

assign grp_hw_AES_fu_1690_p_ce = 1'b1;

assign grp_hw_AES_fu_1690_p_din1 = grp_hw_AES_fu_263_state;

assign grp_hw_AES_fu_1690_p_din2 = grp_hw_AES_fu_263_key;

assign grp_hw_AES_fu_1690_p_start = grp_hw_AES_fu_263_ap_start_reg;

assign grp_hw_AES_fu_263_ap_ready = grp_hw_AES_fu_1690_p_ready;

assign hw_C_0_address0 = zext_ln303_reg_572;

assign hw_C_0_d0 = (hw_M_0_load_reg_605 ^ grp_hw_AES_fu_1690_p_dout0);

assign hw_C_1_address0 = zext_ln303_reg_572;

assign hw_C_1_d0 = (hw_M_1_load_reg_611 ^ grp_hw_AES_fu_1690_p_dout0);

assign hw_M_0_address0 = zext_ln303_fu_365_p1;

assign hw_M_1_address0 = zext_ln303_fu_365_p1;

assign icmp_ln298_fu_350_p2 = ((trunc_ln2 > zext_ln298_fu_346_p1) ? 1'b1 : 1'b0);

assign lshr_ln2_fu_355_p4 = {{i_7_fu_110[9:1]}};

assign xor_i_i708801_out = xor_i_i708801_fu_90;

assign xor_ln234_fu_432_p2 = (call_i_i709809_fu_106 ^ call10_i_i714805_load_reg_623);

assign xor_ln303_fu_392_p2 = (call8_i_i713799_fu_86 ^ call4_i_i711797_fu_82);

assign xor_ln304_fu_415_p2 = (call6_i_i712803_fu_94 ^ call10_i_i714805_fu_98);

assign zext_ln298_fu_346_p1 = i_7_fu_110;

assign zext_ln303_fu_365_p1 = lshr_ln2_fu_355_p4;

always @ (posedge ap_clk) begin
    zext_ln303_reg_572[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //Rocca_S_hw_v2_Rocca_S_hw_v2_Pipeline_VITIS_LOOP_298_1
